### ISSUE TITLE
add browsertime blacklist option

### ISSUE THREAD

**Issue by JimmyG3** [sitespeedio/sitespeed.io#1090]
Is it possible to add the browsertime blacklist option to sitespeed.io?  It would be awesome to see all of the great sitespeed.io reports after blocking several crummy third part add-ins on our site.

**Comment by soulgalore** [comment]
Hey @JimmyG3 
not right now because we haven't implemented that yet in browsertime 1.0 (but have it on the 2do list). When we have it you will be able to use it with --browsertime.YYY (whatever name it will have) because all config with browsertime will be passed on.

If you are using sitespeed.io 3 you can pass parameters to browsertime using a file (it uses browsertime 0.9) so you can use the blacklist (but I dont have exactly in my head and I'm almost offline this week).

Best 
Peter

**Comment by aderumier** [comment]
Hi,
it could be great to have also a whitelist option. (only browse defined domains).
Can be usefull for websites with a lots of adds,social links and other craps

**Comment by JimmyG3** [comment]
Thanks, I see the docs says --btConfig <FILE> for additional BrowserTime JSON configuration.  I'm having some trouble figuring out the JSON format to blacklist.  I've tried variations of this: 
{"blacklist" : ".*google-analytics.*"}
without any luck.  Any pointers are much appreciated

**Comment by JimmyG3** [comment]
I must have missed my morning coffee, because this does the trick.  
{ 
"blacklist" : ".*google-analytics.*"
}

**Comment by soulgalore** [comment]
@JimmyG3 ah good :)

@aderumier yes I agree. We should use the same as in https://github.com/sitespeedio/sitespeed.io/blob/master/lib/support/cli.js#L289 

Here's the original issue if you have time to help out: https://github.com/sitespeedio/browsertime/issues/156

**Comment by soulgalore** [comment]
track this in browsertime
