### ISSUE TITLE
Won't phantomjs support in 4.0 or later?

### ISSUE THREAD

**Issue by zhangzhaoaaa** [sitespeedio/sitespeed.io#1112]
I find in 4.0 version that it doesn't support phantomjs.
I want to know if you won't support it.
If I delopy my nodejs project in a linux server with sitespeed.io ,it will fail.
I really want to know how to do it.

**Comment by soulgalore** [comment]
Hey @zhangzhaoaaa ,
we will not have phantomjs built in 4.0 because it lacks so much of what we need (correct size of assets, understanding http/2 etc).  But if you really want to use it you can add your own plugin.

On Linux you can install Firefox/Chrome and use XVFB as screen. You can checkout the Docker hub to see how you can do it. https://hub.docker.com/u/sitespeedio/

Best
Peter
