### ISSUE TITLE
Let plugins output metrics/data/HTML in the HTML output

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1141]
One thing missing today is the ability to run a plugin and let it output metrics/data in the summary and page for a run. That would be an awesome feature.

**Comment by beenanner** [comment]
This would be nice to also somehow interface with the TSDB plugins so that these custom plugins can also send their data to the TSDB as well. So we have 2 pieces with the first one being a higher priority.

- The interface with outputting standard metrics/data and HTML reporting
- Sending those metrics/data to any of the configured TSDB if specified during the run.

**Comment by soulgalore** [comment]
I think we can do this in at least two different ways:
* A super generic solution where every plugin can create a page, and everything today will use that new solution. This will need a lot of work.
* When we do the change for 6.0 renaming tabs to be more usable (video/waterfall etc) we add an extra tab called extras, where all plugins can report to. That will make it easier (I think) but not as open as no 1. But does it need to be?

**Comment by soulgalore** [comment]
WOHO released in 6.0
