### ISSUE TITLE
Requested size exceeds screen size error [Firefox]

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1143]
We have this upstream thing mozilla/geckodriver#56

What happens right now is that when you open FF with larger window than the screen, we get an error and fails. It's fixed but not released in FF so we should probably change the default width we set (or at least make sure the Docker container works out of the box).

**Comment by beenanner** [comment]
https://www.x.org/archive/X11R7.6/doc/man/man1/Xvfb.1.xhtml The default is 1280x1024x8 which is what docker would use correct?

**Comment by soulgalore** [comment]
It's 1366x768x16 but lets change that and change default in sitespeed.io to the same!

**Comment by soulgalore** [comment]
And we need to trim ffmpeg so it's some work to make sure it works fine.

**Comment by soulgalore** [comment]
In the new Docker file we have better default for xvfb, then later on when the fix lands in Firefox/Marionette/Gecko, lets change at our end.

**Comment by soumyamulu** [comment]
Do we know whether the fix for the window size error is done or rolled back. I am currently using FF 48+ and Selenium(2.53.1, 3.0.0-beta(123)) all give me the same exception unless i set the window size to 1024X768. This is breaking my tests because the elements are out of the window scope.

According to this bug 1280101 they rolled back the changes? Anyone else seeing this problem?

**Comment by soulgalore** [comment]
hey @soumyamulu I think they fixed it in Marionette but it's waiting to get out in coming Firefox.

**Comment by soumyamulu** [comment]
Thank you for the clarification. Till then do we have any workaround for this problem? 
for some reason I can no longer specifiy the binary path as the Firefox developer edition in selenium 3.0+ it always seems to use the real FF. I was wondering if  I can see this fix in the dev version?

**Comment by soulgalore** [comment]
Do you need a workaround for sitespeed.io or selenium? :)

I think (if I remember correctly) that we also need a new version of the Geckodriver, best to check with the Firefox team.

**Comment by tobli** [comment]
@soumyamulu The binary path config was changed quite recently in selenium git, so can't give any general advice. You need to check the source code/git logs for whatever exact revision your running. And also make sure you run a corresponding version of geckodriver. Should work, but haven't checked myself. Note that the latest change are not yet in Browsertime/Sitespeed.io, since they're not released to npm yet.

**Comment by soumyamulu** [comment]
Thank you for the clarification @soulgalore  and @tobli 
I meant more on the lines of do you have any workaround you heard that is working for this problem till new FF is released? 
I did post the same question to the FF team as well on the bug 1280101.

@tobli yes I did verify that but did not see any specifics around this change and yes I am running the corresponding geckodriver (v0.10.0) for sel 3.0+ as well.
