### ISSUE TITLE
--requestHeaders no longer present in v4

### ISSUE THREAD

**Issue by danut-iosif** [sitespeedio/sitespeed.io#1214]
Hello!

I'm using SiteSpeed.io inside the official Docker images, and when going from 3.11.5 to beta.1, I cannot use the --requestHeaders argument, to pass a .JSON with my needed cookies.

How would I go about adding a cookie .JSON in beta.1?

Thanks in advance!

**Comment by soulgalore** [comment]
Hey @danut-iosif 
it's tracked here: https://github.com/sitespeedio/browsertime/issues/155

Can you give an example where you need it? If it's for login I hope the preScript feature can help you in 4.0.

Best
Peter

**Comment by danut-iosif** [comment]
Hello, @soulgalore!

Sorry for polluting the Issues section, then.

Yes, it's for login. The app that I'm trying to benchmark is behind login, but from a platform. How it all looks is like this... You login to the initial platform, it redirects you to its Dashboard, and then from a side panel you can access the URL for the actual site I'm testing, with the platform setting up your cookies properly for this redirect.

I've tried a preScript with beta.1 but my Selenium-foo is probably not that good, because I can do the Login on the platform, but movement through the following Dashboard, I could not do. It always says that it can't find my elements, even with xPath...

Kind regards!

**Comment by soulgalore** [comment]
Hey @danut-iosif 
ah sorry didn't that you are polluting the issue tracker :)

Ah I see. In 3.x we had support in BrowserMobProxy to add request headers, but we stopped using that since it doesn't support http2 and was screwing up response headers. We don't have a clean way to do it today for both browser, but it seems doable from a plugin in Firefox. I have't seen the use case before so I have down prioritized it, but lets see when we can try out doing in at least one browser.

Best
Peter

**Comment by soulgalore** [comment]
Lets track this in Browsertime.
