### ISSUE TITLE
Add WebPageTest to Docker Setup

### ISSUE THREAD

**Issue by derekperkins** [sitespeedio/sitespeed.io#1282]
While the setup is built in to use the WebPageTest API, I think it would be awesome to have a Docker container pre-built that would integrate out of the box, maybe with a simple Docker Swarm setup file.

**Comment by beenanner** [comment]
@derekperkins could you clarify just a bit or let me know if I'm off on your request? Are you thinking of the docker-compose also setting up a private instance of WebPageTest? I think that would be super cool, but haven't seen much movement on dockerizing WPT yet. The closest thing I've come across is https://hub.docker.com/r/nowol/webpagetest/ which seems to suggest it's possible. I think the agents and configuring them would the blocker to automating something like that.

**Comment by derekperkins** [comment]
Yes, that's exactly what I was suggesting, and that was the most popular Docker image I found too.

**Comment by beenanner** [comment]
Just a note if you are not aware both @pmeenan / @soulgalore have posted on how to setup private instances fairly easily in the past using AWS. I would highly recommend due to the easy of deployment via the official AMIs released.

http://calendar.perfplanet.com/2014/webpagetest-private-instances-in-five-minutes/
https://www.peterhedenskog.com/blog/2015/07/private-wpt-instance/

I think if a viable WPT docker setup becomes available. It should be added to our compose file right away. ;-)

**Comment by soulgalore** [comment]
Yes, the https://hub.docker.com/r/nowol/webpagetest/  is only the server right? When there's one for agents it would be cool to add one. Closing this for now but lets re-open when there's one available.
