### ISSUE TITLE
Document the order of preScript, script, postScript and pageCompleteCheck

### ISSUE THREAD

**Issue by gajus** [sitespeedio/sitespeed.io#1325]
It is not clear at the moment in what order these events are executed.

It is safe to assume that `preScript` runs before `script` and `postScript`.

I am also assuming that `postScript` runs after `pageCompleteCheck`.

However, it is not clear in what order are `script`(s) called and how to delay their execution to capture asynchronous data.

**Comment by siejas** [comment]
Since we're talking on `preScript`, I'm using it to authenticate on login page and later using input file with list of URLs.
It's unclear if there's an option to chain these URLs together in one go as in `preScript,URL1,URL2,URL3 `
or each will have to be preceded with preScript like
`preScript,URL1,preScript,URL2,preScript,URL3`
so I'm authenticating for each URL separately.

Also wondered if there's an option to use webdriver while going through the pages - I would like to open specific button on a page which open new page.

**Comment by soulgalore** [comment]
I think this has been fixed with:
https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/
https://www.sitespeed.io/documentation/sitespeed.io/scripting/
