### ISSUE TITLE
WPT plugin : collect additional WPT metrics (not the custom ones)

### ISSUE THREAD

**Issue by jpvincent** [sitespeedio/sitespeed.io#1338]
Hi

The WebPageTest metrics sent to Graphite now are the median SpeedIndex, render, TTFB and some others. I would need some more metrics WPT calculates, like `fullyLoadedCPUms` or `score_cache`.

In the documentation, and from the code I was able to understand, it looks like there is currently no way to collect more default WPT metrics.
Currently, the way I do it is by editing the `lib/plugins/webpagetest/index.js` file and modifying `DEFAULT_METRICS` directly. For instance I added 
```
const DEFAULT_METRICS = [
…
  'data.median.*.domContentLoadedEventEnd',
  'data.median.*.fullyLoadedCPUms',
  'data.median.*.score_cache',
  'data.median.*.score_gzip',
…
];
```

Could we think to a way to configure more metrics to collect, without modifying the code ? Something like 
```console
--webpagetest.WPTMetrics="['data.median.*.domContentLoadedEventEnd','data.median.*.fullyLoadedCPUms','data.median.*.score_cache','data.median.*.score_gzip']"
```

**Comment by jpvincent** [comment]
I think I could provide a patch for this

**Comment by soulgalore** [comment]
Hey @jpvincent before you start, you can change what metrics to send using configuration! We should make the documentation clearer on that, do you any suggestion how we can do that?

Checkout this thread: https://github.com/sitespeedio/sitespeed.io/issues/1312 and the original docs: https://www.sitespeed.io/documentation/sitespeed.io/metrics/ 

You can supply which metrics to send and you can use the config.json file to make that clean (I will make docs for that in the coming weeks) so that you can supply a default json files with most of config and don't have to pass that command line each and every time.

Let me know how it works out for you.

Best
Peter

**Comment by jpvincent** [comment]
RTFM, like always, sorry :)
However, it doesnt seem to support multiple filters at once (I separated them by space)

to sum it up, that works : 
```json
"metrics.filter":"webpagetest.pageSummary.data.median.*.domContentLoadedEventEnd",
```
that does not : 
```json
"metrics.filter":"webpagetest.pageSummary.data.median.*.domContentLoadedEventEnd webpagetest.pageSummary.data.median.*.fullyLoadedCPUms webpagetest.pageSummary.data.median.*.score_cache webpagetest.pageSummary.data.median.*.score_gzip",
```

**Comment by soulgalore** [comment]
Np there's a lot of documentation and I think we can make it cleaner. I'll focus on first how to run multiple tests after each other, @tobli has clean way of doing that and I need document that first.

For metrics, if you add "" the cli options will take that as one parameter (everything inside) so think in your config you should have an array with multipe items like (haven't tested it though):
<pre>
"metrics.filter":["webpagetest.pageSummary.data.median.*.domContentLoadedEventEnd", "webpagetest.pageSummary.data.median.*.fullyLoadedCPUms", "webpagetest.pageSummary.data.median.*.score_cache", "webpagetest.pageSummary.data.median.*.score_gzip"]
</pre>

**Comment by jpvincent** [comment]
Yes I'm using a config file, and this syntax does work, many thanks
