### ISSUE TITLE
No files created in sitespeed-result when running cron job - Graphite not saved

### ISSUE THREAD

**Issue by namnn96** [sitespeedio/sitespeed.io#1350]
Hi @soulgalore,

I am running sitespeed.io via crontab job. Data is still sent to graphite, but nothing is created under sitespeed-result folder.

If I run the command manually, it generates files under sitespeed-result. Also, I can only retrieve data for one day, previous days' data was not saved. This is my storage-schema.conf file:

```
[carbon]
pattern = ^carbon\.
retentions = 60:90d

[default_1min_for_1day]
pattern = .*
retentions = 1m:1d,10m:30d,1d:2y
```

Thanks in advance.

Best regards,

**Comment by soulgalore** [comment]
Hey @namnn96 ,
could it be that you run the crontab as another user, so the results ends up somewhere else? Can you try setting the <code>--outputFolder</code> to an absolute path.

For the Graphite config setup, check https://github.com/sitespeedio/docker-graphite-statsd 

Best
Peter

**Comment by namnn96** [comment]
Hi @soulgalore,

I am testing this using aws ec2, no elastic ip. 

I actually read really carefully about the retention, and as far as I understand, 1m:1d,10m:30d,1d:2y means create data point every 1 minute, store for 1 day, create data point every 10m, store for 30days. But my data is never saved for more than 24 hours.

This is what I did, but I don't think it is optimized. I add cronjob for urls to the crontab and run these jobs every 5 minutes. I understand that would make the server very slow when there are multiple urls. Is there a better way you would suggest me to do? would adding all the urls to 1 file and run 1 sitespeed command for just the file be better?

Thanks in advance

**Comment by softwareklinic** [comment]
@namnn96 

I have over 200 urls that we track... the way we have achieved is based on the category e.g. if i have all accessories related urls -- kept them separate v/s the plans based urls... v/s some of the marketing landing pages... etc...

Also, keeping all URLs in 1 text file is not a good idea --- since we have seen issues while writing the results towards the END. I'm not sure if that implementation has changed @soulgalore - can add more here.

We have split the list into more manageable files e.g. 30-40 / file and under different more meaningful namespaces when it comes to graphite/grafana.

Also, we are running multiple jobs @ different times eg... every 15th, 30th, 45th, 0th minute of an hour.. and sitespeed is just running fine without any hiccups .. all 3 images (sitespeed/graphite/grafana) are running on a 4cpu 16gb memory AWS RHEL instance.

Let me know if this helps of any other Q...

**Comment by soulgalore** [comment]
thanks @softwareklinic for sharing!

@namnn96 I will go over the Graphite setup this weekend and check. It's strange that you only get one day. On https://dashboard.sitespeed.io/ we run the exact setup of https://github.com/sitespeedio/docker-graphite-statsd

**Comment by namnn** [comment]
Thanks @softwareklinic  and @soulgalore,

I really appreciate your help.

**Comment by softwareklinic** [comment]
What is.your current setup -.is.it.all docker.or via local npm sitespeed , graphite and grafana running on.a.local system

**Comment by namnn** [comment]
I setup graphite and grafana on my aws server.

I use docker to run sitespeed, with graphite host is my server ip

**Comment by softwareklinic** [comment]
You want to try out with Graphite & Grafana docker? --- atleast graphite docker for now...

**Comment by namnn** [comment]
Is that possible that I only use docker image for sitespeed and setup graphite/grafana myself on server?

**Comment by softwareklinic** [comment]
Yes It is possible - but I have usually found Graphite to be a pain in xxxxx to setup... so always used Graphite and Grafana Docker with Sitespeed docker... so basically all 3 docker images... its FAST to get up and running with docker.

**Comment by soulgalore** [comment]
hey @namnn96 how often do run your tests? I think the retentions you have can mess that up: 1m:1d,10m:30d,1d:2y

Everything older than 1 day you will use the storage-aggregation conf to get the value right. That configuration chooses how your data will be aggrgated. And since you said data for 1 d is ok, it seems like that kicks in for the next conf.

**Comment by soulgalore** [comment]
Checkout Timos desciption field on how everything works: https://phabricator.wikimedia.org/T114974

**Comment by namnn** [comment]
Thanks @soulgalore,

I run it every 5 minutes. I haven't touched the storage-aggregation.conf, would that cause trouble?

And I notice something that recently, when I run sitespeed via docker, I always got 500 Internal Server Error for 	/api/datasources/proxy/1/render in Grafana. It seems to be graphite issue, though the metric structures are all there, I just cannot display the mean, sum, etc of each metric

**Comment by namnn** [comment]
Thanks @softwareklinic,

I tried to run graphite via docker and there are a couple of issues. Which graphite docker image did you use

**Comment by soulgalore** [comment]
@namnn96 what does your storage-aggregation.conf look like? Is the xfactor 0.5 ? If so, change that to 0.0.

Best
Peter

**Comment by namnn** [comment]
Hi @soulgalore, yes, the xfactor is 0.5.

The 500 issue was related to the postgres database corruption. I delete the database then create a new one and it seems to be fine. But I wonder for what reason did the db corrupt? Was it because of Graphite storing all history datapoint even if I delete everything under whisper folder (except carbon)?

Thanks

**Comment by soulgalore** [comment]
Closing, let us know if this is still a problem.
