### ISSUE TITLE
Run on multiple URLs is broken for WPT plugin (at least)

### ISSUE THREAD

**Issue by jpvincent** [sitespeedio/sitespeed.io#1367]
I am using sitespeed by giving it a .txt file that has multiple URLs, [as per the doc](https://www.sitespeed.io/documentation/sitespeed.io/configuration/#analyze-by-urls), together with webpagetest.
By adding the `-v` (verbose) option, I see that multiple WPT tests are correctly sent, and when going on the actual WPT server, I can confirm when they are finished. However the sitespeed.js never ends, as if it was waiting webpagetest forever, even if it correctly ended

Having only one URL in the .txt file works fine though, but it obviously defeats the purpose of having a file.
Tested with SiteSpeed.io 4.0.7 and 4.1.3

**Comment by soulgalore** [comment]
ok, let me test that when I get back to town this weekend. so you simply have a list of URLs in your text file and nothing more than that right?

**Comment by jpvincent** [comment]
That's it. Eg : 
````
http://www.vogue.fr/
http://www.vogue.fr/lifestyle/voyages/diaporama/les-plus-beaux-hotels-sur-les-iles-ou-partir-en-hiver/39332#le-six-senses-zil-payson-sur-lile-felicite-aux-seychelles

````
(final CR included, but with only one URL, it does work)

**Comment by soulgalore** [comment]
This is because of kind of an evil approach in the WebPageTest NodeJS API, remember I seen it before. 

First run, the options looks like this:
<pre>{"host":"https://www.webpagetest.org","location":"Dulles:Chrome","connectivity":"Cable","runs":3,"pollResults":10,"timeout":600,"includeRepeatView":false,"private":true,"aftRenderingTime":true,"video":true,"key":"MASKED","firstViewOnly":true}
</pre>

And next time:
<pre>
{"host":"https://www.webpagetest.org","location":"Dulles:Chrome","connectivity":"Cable","runs":3,"pollResults":10000,"timeout":600000,"includeRepeatView":false,"private":true,"aftRenderingTime":true,"video":true,"key":"MASKED","firstViewOnly":true}
</pre>

Look have pollResults and timout changed to ms.

**Comment by soulgalore** [comment]
will roll out a the fix tonight or early tomorrow, thanks @jpvincent for reporting!
