### ISSUE TITLE
Recreating Sitespeed scorecards in Grafana

### ISSUE THREAD

**Issue by TJ71** [sitespeedio/sitespeed.io#1378]
Hi,

I'm a non tech looking for a little help/guidance.

I wondering if it is possible to recreate the PAGES, ASSETS, and TOP/HOTLIST within Grafana?

I have looked at Grafana and tried to set up a basic table showing all assets and their size. To date though I have failed miserably. Is it achievable to recreate or is it far simpler to just use the HTML pages provided.

Any info appreciated, thanks

**Comment by soulgalore** [comment]
Hey @TJ71 have you tried or ready made dashboards? that fixes the pages, for the others you need to hack them. We don't send asset info per default because it overloads Graphite.

Best
Peter

**Comment by TJ71** [comment]
@soulgalore Thanks for the reply, where can I find the ready made dashboard?

I've looked at the ones that I've been provided with in Grafana and they don't give me what I'm after.
I found a few links to on the Sitespeed site alluding to ready-made dashboards but the links were dead or broken.

Thanks

**Comment by soulgalore** [comment]
You can use our docker compose to get them: https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#docker-compose-file

Or get them yourself: https://github.com/sitespeedio/grafana-bootstrap-docker

**Comment by TJ71** [comment]
Thanks for these, unfortunately they don't seem to offer the same tables/data.

I'm looking for something that simply shows all the assets used on a page - file name(s) and size(s).

**Comment by lbod** [comment]
@soulgalore I'm actually a colleague of TJ71's so maybe I can explain what he's after, though I'm not sure if it's even possible.

Just to clarify, we have this running in the cloud via the docker containers. I'd also ran a ``--metrics.list``, ``--metrics.filterList`` etc to figure out what filters we could use and what we had running. Currently we're now collecting all metrics.

What TJ71 wants is to mirror some of the data from the html reports in graphite/grafana, in particular the "toplist" e.g. http://examples.sitespeed.io/4.2/2016-12-13-12-50-13/toplist.html
So we have the some data that gets us closer 
``sitespeed_io.default.summary.mysite.chrome.native.largestassets.css.0.contentSize`` however that's keyed on index and we can't get the file name from it. 
Whereas we have ``sitespeed_io.default.summary.mysite.chrome.native.aggregateassets.http___www_google-analytics_com_analytics_js.size`` which gives us the asset name (though underscored) but doesn't tell us the content type  (this https://github.com/sitespeedio/sitespeed.io/pull/1341 seems to be relevant too)

I'm still learning graphite (and grafana) at the moment but graphite appears to only be for numerical data (min/max etc), however I have seen that influxdb can store string data too. 

At the moment we're thinking that we'll need a mix of the generated html reports as well as sending some data to graphite so TJ71 gets everything he's after.

However, what's your thoughts on me doing a PR to add the asset name to largestassets? e.g. ``...largestassets.css.0.contentSize.name``, could that even be used by graphite and would it even make sense in that context?

**Comment by soulgalore** [comment]
@lbod we will do a release today (4.2) with the fix "The keys for assets in PageXray was broken when we sent them to Graphite, because we couldn't identify which asset we sent, instead of the URL we used the position in the array. We fixed that now, BUT: Please don't send all the assets to Graphite, it will fill your disk! #1341"

That will send all assets for the first run you do for a URL (but you still need to configure that), lets sync after we done the release and see if that works out for you!

**Comment by soulgalore** [comment]
hehe ah see now that you referenced that fix, sorry. Hoepfully you can use that.

For adding the URL to the toplist, really want to avoid that. The reason is that for now it's a way to graph largest assets by type and still have the same amount of data stored in Graphite. If we have the URL it will change over time (or even worse per run) and it will not scale. The aim for us now with Graphite is that per default the data will be the same.

**Comment by soulgalore** [comment]
We won't start sending lists to Graphite since it will make the data grow out of control. Maybe we could have a plugin that stores those kind of lists elsewhere?
