### ISSUE TITLE
Is it possible to open browser via sitespeed on a cloud like Saucelabs

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/sitespeed.io#1393]
Is it possible to run sitespeed.io locally, but opening browsers on saucelabs cloud? Has anyone run into this requirement?

**Comment by soulgalore** [comment]
Hey @abhagupta I think it should be possible by setting a Selenium server https://github.com/sitespeedio/browsertime/blob/master/lib/support/cli.js#L125 but I don't remember now how Saucelabs handles passwords, maybe it needs some hack?

One thing though: I think it only would work ok for checking metrics like Coach score, number of request, page size and not timing metrics, since I guess you will hit different servers/hardware each time and those values will be unstable (I haven't tried but in theory at least it wouldn't work).

Let us know if you need any help to try it out.

Best
Peter

**Comment by soulgalore** [comment]
Saucelabs is probably not we wanna support since the metrics will be out of control (we will hit different instances per run), but please re-open if I'm wrong and there's an use case for it!

Best
Peter

**Comment by abhagupta** [comment]
@soulgalore  sorry to re-visit this issue again.  I agree that numbers will be too flaky but this might come handy if you want to run sitespeed in a CI environment which runs multiple browsers parallely.  This also becomes an important feature if mobile browsers are considered since setting up local device farm can become cumbersome. Saucelabs has started supporting real devices and I am trying to use that as our device farm.  (This might also raise a question whether sitespeed supports appium, but that is a seperate issue).  

IMO, if the sauce connection time can be considered as constant, we might be able to see some good perf results in saucelabs.

I gave it a shot and ran sitespeed to point to saucelabs to run a simple web test. It worked. It actually does not need any code change. The settings for saucelabs can be just sent in the `options`. I can send a PR of documentation if you want.

**Comment by soulgalore** [comment]
Hey @abhagupta aha cool, yes PR for updated docs would be great! Do you know if you can hit the same device when you test or is it chosen by Saucelabs?

**Comment by abhagupta** [comment]
https://github.com/sitespeedio/browsertime/pull/325 is the PR.  I am sure its opening a new/different VM for each tests.  I am not yet running tests on android device on Saucelabs.
