### ISSUE TITLE
Using Docker & Sitespeed on Windows

### ISSUE THREAD

**Issue by rschoessler** [sitespeedio/sitespeed.io#1397]
This is more of a question than an issue...

I'm new to Docker.  Running Windows 7 so needed to install the Docker Toolbox to get set up.  I'm all set up, run the Docker Quickstart Terminal, use the commands that you recommend on the [Running in Docker documentation](https://www.sitespeed.io/documentation/sitespeed.io/docker/), I see sitespeed run like normal in the terminal, but....

...i can't locate my results anywhere.

Some other interesting and maybe not helpful things...when I open Docker terminal, it defaults to a network drive where my desktop, My Docs are all set up, instead of a regular C:\drive.  I have tried to `cd /c` and then run the command from there, but to no avail.  Clearly I am in over my head.  Any help would be great.

**Comment by soulgalore** [comment]
Hey @rschoessler 
wanna check did you mount a volume for the result? Like <code>-v "$(pwd)":/sitespeed.io</code>? That means that on the server/host where you run sitespeed, map the directory where you are (pwd) to /sitespeed.io inside the container. By default the sitespeed.io inside docker writes to /sitespeed.io so that need to be mapped. Not 100% sure now how that works in Windows, in older version of Mac OS X there was a limit that the mounted directory needed to be inside your users home directory. 

You can also try to set an absolute path. It will be the same for example if you run other Docker containers and want to change configuration, then you mount a config file on the host (or config dir) inside the container. Hope that helps!

Best
Peter

**Comment by tobli** [comment]
Hi @rschoessler!
I'll be closing this issue now, hoping this worked out ok for you.

/Tobias
