### ISSUE TITLE
Create my own html template

### ISSUE THREAD

**Issue by Miladkhoshdel** [sitespeedio/sitespeed.io#1400]
Hello

As you know html report files store in sitespeed-result/www.sitespeed.io/2016-12-29-22-19-53/ by default and it is the default html template style for sitespeed.

Can i change the html report files? for example, i want to have my logo and my own html template with another language. is there any solution for that ?

best regards

**Comment by soulgalore** [comment]
Hey @Miladkhoshdel there's no clean way to do it today, but it would be nice to have. I've been thinking of ways to make it easy to override. CSS would be easy but the pug files is harder. Maybe we could add blocks for header/footer ala https://pugjs.org/language/inheritance.html and then have the possibility to override templates? @tobli @beenanner do you have a good solution how we should do it?

We also have the big thing left to solve (that we wanna do): have the ability to add pug templates from other plugins, so that if you create a plugin, you also can add that data/metrics to the HTML result. But that is another issue.

Best
Peter

**Comment by soulgalore** [comment]
In 6.0 you can add CSS as a plugin that overrides the current version, checkout https://github.com/sitespeedio/sitespeed.io/pull/1787/files
