### ISSUE TITLE
error on engine.js

### ISSUE THREAD

**Issue by kisin** [sitespeedio/sitespeed.io#1401]
just installed sitespeed.io and tried to run it for the first time and i get the error:

`options.postScript.unshift(...videoPostScripts);`

on engine.js:133

what im doing wrong?

**Comment by tobli** [comment]
Hi @kisin!
Could you please provide more detail. Like what version of sitespeed.io, what platform you're running it on, preferably the exact command you used to start it etc.
Thanks

**Comment by kisin** [comment]
just installed the master branch and running it on macOs sierra.
no matter what i try i keep getting the error.

for example: running the command
`sitespeed.io -h`

**Comment by tobli** [comment]
Could you please elaborate more. Are you planning on doing development on sitespeed.io? If not it's not recommended to run from the master branch, but rather to install one of the release versions. Either via npm or Docker as noted on https://www.sitespeed.io. Docker will give you more features (e.g. video) without installing additional dependencies, so that's a better option in many cases.

The command you're quoting (`sitespeed.io -h`) suggests you're not running from the master git branch, but from a `npm install -g`version. Running from a master branch checkout would be `bin/sitespeed.js -h`.

**Comment by tobli** [comment]
It could be that your node version is to old, check by running `node --version`. You need 6.9.1 or newer to run sitespeed.io (the Docker version included all dependencies, including node).

**Comment by kisin** [comment]
you are right. i updated the node to latest version and it works.
thanks man.

**Comment by tobli** [comment]
Great! We should make the mode version requirement clear in the documentation.
