### ISSUE TITLE
Whisper DB size per page with standard metrics is roughly 25mb

### ISSUE THREAD

**Issue by lbod** [sitespeedio/sitespeed.io#1416]
Using docker/sitespeed version v4.3.7

This is more of a general question, probably a discussion group/forum question but I don't think there is one.
I'm newish to Graphite as well as the Whisper DB so I've just began to understand Whisper's architecture/design but it appears for a new page with standard, out of the box set sitespeed metrics, a new page will add about 25mb in size.

In the space of about 6 days (using the docker install of v4.3.7) the docker volume/whisper DB is now 13gb, this was a new machine, everything installed from scratch. We haven't been running it very often either, however there's probably between 600-700 unique pages crawled (in total across several sites).
From the Whisper docs it appears space shouldn't increase much more on successive tests against the same page (or data points). Is that correct?

Should I be expecting this to level out if we've covered most of the pages we'll crawl in future? 

Or is this excessive disk usage? It's what it currently looks like to me.

We're trying to size how much storage is needed and at the moment it just seems like a "suck it and see" thing.
Any advice is appreciated, if there is a discussion group/forum please let me know and close this issue.

**Comment by soulgalore** [comment]
Hey @lbod 
I'll make a long answer tomorrow (getting late here) but can you show me more how you run, what config etc? Then I can compare how we run on dashboard.sitespeed.io and make a better answer! 

Thanks
Peter

**Comment by lbod** [comment]
Hey @soulgalore and thanks.
What is it you need to see? The cron jobs for the sitespeed jobs, config for docker-compose, docker compose version, or container config overrides (or anything else)?

**Comment by soulgalore** [comment]
Hello @lbod 
I was curious about the config how you run sitespeed.io if you choose what metrics to send etc? 

This is how it works, I'll add this thread to the docs when you feel you got what you need: With 4.x we try to send a moderated number of metrics per URL but you can change that yourself following https://www.sitespeed.io/documentation/sitespeed.io/metrics/

When you store metrics for URL in Graphite you decide from the beginning how long time you want to store the data and how often in [storage-schemas.conf](https://github.com/sitespeedio/docker-graphite-statsd/blob/master/conf/graphite/storage-schemas.conf). In our example Graphite setup every key under sitespeed_io is caught by:
<pre>
[sitespeed]
pattern = ^sitespeed_io\.
retentions = 10m:60d,30m:90d
</pre>
meaning for every metric that is sent Graphite following the pattern we prepare storage for it every ten minutes the first 60 days, after that Graphite uses the configuration in [storage-aggregation.conf](https://github.com/sitespeedio/docker-graphite-statsd/blob/master/conf/graphite/storage-aggregation.conf) to aggregate/downsize the metrics the next 90 days.

Depending on how often you run your analyze you wanna change the storage-schemas.conf. With the current config, if you analyze the same URL withing 10 minutes, one of the runs will be discarded. But if you know you only run once an hour, you could increase the numbers. Etsy has [good documentation](https://github.com/etsy/statsd/blob/master/docs/graphite.md) on how to configure Graphite.

Normally I don't recommend crawling and sending the metrics to Graphite because when sitespeed.io finds a new URL and sends it to Graphite, it will prepare storage for the amount of runs you configured in storage-schemas.conf. In your example, if one URL takes 25 mb, if that URL is crawled only once a week, it will still take the 25 mb. When I used crawling I done it only by analyzing the HTML. 

BUT there could be a solution (as you probably already thought of): If you don't want to store the metrics for so long time (would love to know more how you use the data!) say keeping one week of data, you can configure that in storage-schemas.conf and each tested URL will take smaller space. It all depends on how often you want to run and how long time you want to store the metrics. You could set up another namespace (start of the key) and catch metrics that you only store for a short time. 

One thing to know if you change your Graphite configuration: ["Any existing metrics created will not automatically adopt the new schema. You must use whisper-resize.py to modify the metrics to the new schema. The other option is to delete existing whisper files (/opt/graphite/storage/whisper) and restart carbon-cache.py for the files to get recreated again."](http://mirabedini.com/blog/?p=517)

Let me know if it's understandable!
Best
Peter

**Comment by soulgalore** [comment]
I cleaned up comment and added it to the docs: https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#configure-graphite

**Comment by lbod** [comment]
Thanks again!. We were looking at the retentions config yesterday so we'll have a play with that.

However I wasn't sure about one part of the documentation:

> Normally we don’t recommend crawling and sending the metrics to Graphite because each URL will take the full amount of space meaning if you test one URL only once, it will still take the same amount of space as if you test it multiple times (following the configuration).

I'm not sure what you mean re "we don’t recommend crawling and sending the metrics to Graphite", by crawling I meant a sitespeed run, how else would we send the metrics to Graphite?

**Comment by soulgalore** [comment]
Let me re-phrase that in the documentation so that is clear. What I meant by crawling for example a news site, and you will hit new article pages every day, maybe every run. If you run that with the default configuration, it will use a lot of space for metrics that you don't use.

> by crawling I meant a sitespeed run, how else would we send the metrics t

You can feed with a list of URLs so that you test the same URLs all the time. I'm just curious of your use case, I understand you can crawl and get the data into graphite, more interested how you see that helps you or what you do with that :)

**Comment by lbod** [comment]
Ah ok, I fully understand now and sorry, my fault for calling it crawling. Yes we run our jobs by supplying it a file with a number of fixed URLs.

Interestingly enough, we were planning on running the cron jobs once a week, mainly because of concern over disk space with the html reports, but it appears now we could run the jobs hourly, run a job to delete unwanted html reports, and still be able to hit a sweet spot of disk usage for the DB which won't be affected.

Thanks v much for updating the docs.
