### ISSUE TITLE
Plugin proposal : measure CPU consumed by 3rd parties

### ISSUE THREAD

**Issue by jpvincent** [sitespeedio/sitespeed.io#1423]
Hi
Lot of websites today include 3rd parties scripts, and it happens more than once that they freeze the interface, or that the total load is not sustainable to expect a fluid navigation. On some sites with ads, widgets and tracking, assuming the connection is fast enough, it can take more time to execute scripts than to download assets. 
All in all, I think that 3rd party monitoring is the new WebPerf battle, as it destroys the UX and is hard to spot. I [use a script](https://github.com/jpvincent/3rd-party-cpu-abuser) that get the chrome dev tools timeline and attribute CPU consumption to a domain. Nice for a one shot analysis, but I would like to monitor each domain in the long run.

The sitespeed.io plugin system seems appropriate, but I would need some help to write it because the current documentation is not very clear to me … Can you help me for the steps I wrote below ? I will update the documentation once I've got it, if you will.

Goal : get the raw timeline data from the chrome devs tools, analyse it with package `3rd-party-cpu-abuser`, have the information visible to grafana

Steps :
* run the plugin explicitely (say --getCPUPerDomain ? any naming convention ? )
* if the plugin is explicitely called, enable the timeline on Chrome :
** on browsertime, by setting a chrome flag (to find)
** on WPT, adding the option `webpagetest.timeline:true`
* run the plugin implicitely if following conditions are met :
** browser is chrome
** the test has a chrome dev tools timeline JSON file, from browsertime (`case 'browsertime.har'` or equivalent in plugin/index.js ?) or a WPT result with timeline enabled
* get the file chrome dev tools timeline JSON file
** WPT results has the file URL, download it
** get it from browsertime
* run an external nodeJS package : `3rd-party-cpu-abuser`. I maintain it on NPM, it just attributes CPU usage to a domain, from the dev tools timeline JSON analysis.
* convert the stats to something that can be sent to graphite ( plugins/aggregator.js ?)
* optional : display the information in the HTML result file

**Comment by soulgalore** [comment]
Hey @jpvincent ,
that sounds really cool!

First I think we maybe need to make it possible to configure Browsertime to get more logs from Chrome. Have a look at the <code>--experimental.dumpChromePerflog</code> flag for Browsertime, is that what you need or do we need to change the config? Here's an example to do that: https://github.com/sitespeedio/browsertime/blob/meaningfulPaint/lib/core/webdriver/chrome.js#L68-L69

First I would just make everything work and then we can help you fine tune it could be that we need to fix the user flow, so that now first you just add the --browsertime.experimental.dumpChromePerflog flag to get the log.

We can fix so that the data is automatically sent to Graphite, if you configure the data, we can help out with that.

Plugins haven't support for HTML yet and don't have a nice solution for that yet but it would be super cool to add.

Can you drop me an email peter [AT] soulgalore [dot] com then I can easier support you.

Best
Peter

**Comment by cgoldberg** [comment]
measuring 3rd party content sounds beneficial, but is CPU utilization really the right metric?  I think having the latency measurement for network transfer, parsing, and rendering, per domain is what to look at.

**Comment by beenanner** [comment]
@cgoldberg agreed that having those other measurements would help give a clearer picture. I think having both features in one or multiple plugins would be phenomenal!

**Comment by xavier-medioni** [comment]
Hi @jpvincent,
Yes, it sounds great to be able to measure processing consuming for long run / scan.
And if there is a way to measure memory consuming too for a whole scan, you will make me as happy as it gets ! ;-)

**Comment by jpvincent** [comment]
hi @cgoldberg hi @xavier-medioni 

Latency for the 3rd party servers is definitely something I would like to monitor, but maybe not in this plugin, I would do another fork for that.
Parsing, rendering and forced layouts on a per domain basis would be really useful in this plugin, I "just" have to read more about how to detect it automatically and will add it in the [script I use](https://github.com/jpvincent/3rd-party-cpu-abuser) then the mapping to grafana should be easy

Memory would be a good idea, but probably in a 3rd phase : until now I never encountered a client's site that was consuming so much memory that it would let the device lagging.

thanks for the suggestion

**Comment by soulgalore** [comment]
This is perfect as a plugin outside of sitespeed.io
