### ISSUE TITLE
Graphite/Grafana is very slow rendering visuals

### ISSUE THREAD

**Issue by davidbonnici1984** [sitespeedio/sitespeed.io#1491]
I noticed a sudden performance drop. As you can notice from the image below request to graphite are taking long, what's the best practice to debug such situation?

Keep up the good work! ;)

Thanks
David

![image](https://cloud.githubusercontent.com/assets/905774/23542704/efd8759a-ffee-11e6-8e1f-578fcef7a4ca.png)

**Comment by soulgalore** [comment]
Hey @davidbonnici1984 
thanks :)

What's your graphite setup, and how many metrics do you collect? Is it for all data or just one dashboard/graph? You can setup memcached for Graphite (http://graphite.readthedocs.io/en/latest/config-local-settings.html) but that only make requests faster the second time.

Best
Peter

**Comment by davidbonnici1984** [comment]
I'm using SiteSpeed default setup and default metrics for collection. It's for all the dashboards. I will continue looking into a solution and will let you know what's the root cause. I will close this since it's not an issue per se, but I will contact you with the outcomes.

Cheers
//David

**Comment by davidbonnici1984** [comment]
Hi @soulgalore,

As I mentioned already I am using the default metrics for collection, is there anyone experiencing this problem?
I did some maths about total metrics, is this correct?

What's the best setup for graphite for this tons of data?

What are other practices that you have to apply apart from memcached for graphite as you recommended?

![image](https://cloud.githubusercontent.com/assets/905774/23650150/6c3b35a2-0321-11e7-8964-0d47249b8be7.png)

**Comment by soulgalore** [comment]
Hey @davidbonnici1984 I wouldn't use Graphite when crawling (I wrote about it here before https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#crawling-and-graphite but I will update the docs tonight and add a best practice section for setup) since you can pick up new URLS for each run. When you add metrics to Graphite, it will prepare space for that metrics depending on your storage conf (in Graphite). If you configured Graphite to store individual metrics every 15 minutes for 60 days, Graphite will allocate storage for that URL: 4 (per hour) * 24 (hours per day) *60 (days) even though you maybe will only test that URL once.  You can tweak that but when crawling I think there are better storage solutions. We don't support one right now but with the plugin structure it's possible to add that.

I'll ping this issue when I've added the docs!

Best
Peter

**Comment by soulgalore** [comment]
I don't remember what I should. I think the solution for this is outside of sitespeed.io :) But if find a good setup I would if you could send a PR for the documentation.
