### ISSUE TITLE
How use resultBaseURL

### ISSUE THREAD

**Issue by Wofik29** [sitespeedio/sitespeed.io#1499]
Hello. I can not understand how to use `resultBaseURL` options.
I use docker + sitespeed.io + sitespeedio/graphite + grafana.
Which server must be in url? Specific ftp? May i use cloud storage or file hosting or it working only with S3?
For example [Seafile](https://www.seafile.com/en/home/).
I've build simple docker image from seafile and opened port 8000 and named "report".
Inside graphite container I use wget to http://report:8000 and it works - I get html.
But when i launch docker sitespeed.io, I get error below
`Got error from Graphite when sending annotation Error: connect ECONNREFUSED 172.18.0.3:8080`
I've tried indicated resultBaseURL to http://report:8000, and to local ip, and domain name, but it useless.

**Comment by soulgalore** [comment]
Hey @Wofik29 
The result base URL is right now only used when sending an annotation to Graphite, so that when you click on the link in the annotation, you will get to that URL ("Result 21 run(s)":

<img width="314" alt="screen shot 2017-03-09 at 08 52 11" src="https://cloud.githubusercontent.com/assets/540757/23740845/bfe7ba6a-04a5-11e7-8d81-41d7f491f220.png">

Right now we only support uploading by default to S3 but it would be cool to have more uploaders. A generic FTP upload sounds like a good idea. If you have specific needs, you can build a plugin that uploads the files to that host. 

That other issue: Sitespeed.io tries to send an annotation to Graphite, using the same IP you configured with <code>graphite.host</code> but the annotation API talks HTTP so if you don't run with default settings, set <code>graphite.httpPort</code> and if it is behind Basic Auth set <code>graphite.auth</code>. There are some docs [here](https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#annotations) but we probably should add more.

Best
Peter

**Comment by Wofik29** [comment]
I see. It's clear.
For example. When I launch this way:
`docker-compose run  --rm sitespeed.io -v -n 1 --graphite.host=graphite-test --speedIndex --graphite.namespace="sitespeed_io.test" $URLS`
It's ok, working. No questions.
But if add `--resultBaseURL http://report:8000`, then I get error.

Now I will understand, now support only S3.
Will other uploaders be supported? if yes, then when?

Thanks for the answer!

**Comment by soulgalore** [comment]
> But if add --resultBaseURL http://report:8000, then I get error.

If you configure the resultBaseURL together with Graphite it will automatically try to send annotations

> Will other uploaders be supported? if yes, then when?

yes that would be cool. as we get a PRs and can test them :) Uploaders will also work great as plugins so it doesn't have to be shipped within sitespeed.io

**Comment by soulgalore** [comment]
@Wofik29 do you need anything else? If your looking for other uploaders, it would be super if you could create a issue for that!

**Comment by soulgalore** [comment]
closing, please re-open if you need more info!

**Comment by Algram** [comment]
@soulgalore What would be the best way for me to add functionality for a local nginx server instead of S3? I would like to submit the PR but don't know where to start.

**Comment by tobli** [comment]
@Algram if it's nginx serving local files (i.e. you don't need to upload files to a remote server) you don't need any additional functionality. Either configure nginx to serve files from the default output directory, or use --outputFolder to direct the output to where nginx is reading from. Then use --resultBaseURL to set whatever base URL you've set up for your local nginx.

**Comment by Algram** [comment]
@tobli that's exactly what I am doing. The local nginx is working and --resultBaseURL is set. Still I do not see annotations in Grafana.

**Comment by soulgalore** [comment]
@Algram ok, can you check the log of sitespeed.io that the annotation is sent (if you use Graphite as backend you should see *Sent annotation to Graphite* in the log? Do you use the default Grafana templates or do you do your own (trying to track down the problem)?

**Comment by Algram** [comment]
@soulgalore Thank you for the tip. Indeed it shows
```
ERROR: Got 401 from Graphite when sending annotation
```
in the log, although I do not know why I am not allowed to send annotations to Graphite but other data is okay.

**Comment by soulgalore** [comment]
I think your Graphite is behind basic auth? See https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#annotations 

If you use our Graphite Docker container it is, check the docs for the container!

Best
Peter

**Comment by Algram** [comment]
@soulgalore I had that thought aswell, but even with `--graphite.auth sitespeedio:hdeAga76VG6ga7plZ1` added for the default user and pw, I still get the 401.

**Comment by soulgalore** [comment]
@Algram that is the default password for Grafana right, the default basic auth for Graphite can be found here: https://hub.docker.com/r/sitespeedio/graphite/ (and then you change it by feeding your own .htpasswd file).

**Comment by Algram** [comment]
Ah perfect, it is working now.
Thank you very much!
