### ISSUE TITLE
getting cookie error in sitespeed docker browser

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1520]
Hi,

Hi ran some tests over my company aws and when I got a screenshot and video of pages that required a cookie I got the below error:

![image](https://cloud.githubusercontent.com/assets/22225816/24002073/29c45ce6-0a36-11e7-8516-039d7ab1eb8b.png)

The test is able to access the site and log in, the problem occurs (it appears) that the cookie is not being saved? For Authentication/session handling which is required by the URLs that need to be tested.

I am using the sitespeed docker container with all defaults. Is there something I can do to avoid this problem?

Thanks,

**Comment by soulgalore** [comment]
Hi @ppcuenca can you show us how we can reproduce it? The cookies should live between preScript, when the URL is tested and postScript. We have runs on https://dashboard.sitespeed.io/ where it works for us, so I don't think cookies is the problem, but let us test.

Best
Peter

**Comment by ppcuenca** [comment]
Hi @soulgalore 

I can't share details here but I can email you privately if that works?

**Comment by soulgalore** [comment]
Can you check first that your login script really works? There's kind of a bug in Selenium that makes promises not work as they should (@tobli do we have an issue for that in Browsertime to see if we can test out the new config to fix that?), so for example it works for Wikipedia (the example script) since it is so fast but if your site is slowish, it can return before the page has loaded (there has been one/two issues with that problem).

**Comment by soulgalore** [comment]
@ppcuenca did you find if the login worked or not?

**Comment by ppcuenca** [comment]
Hi @soulgalore 

Sorry for the delay, I use the same script locally and I have no issues there :(

**Comment by soulgalore** [comment]
Ok so you mean if you run the script locally with sitespeed.io everything works and then on your test  server it fails? It's something with the environment then?

**Comment by soulgalore** [comment]
I don't see this is a problem with sitespeed.io.
