### ISSUE TITLE
Tests on Android phones via docker sitespeed.io

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/sitespeed.io#1573]
@soulgalore  Amazing job on adding Android phones for testing.  https://www.sitespeed.io/documentation/sitespeed.io/mobile-phones/ ..  You don't know how big of a problem you have solved for us.  Works like a charm.   

I just wanted to know if its possible to run a test on Android device from sitespeed running in docker container.  Obviously, it has to communicate with `adb` and then reach the device.  I tried it and it failed complaining about  `unknown error: Failed to run adb command, is the adb server running?` . Have you tried this? Is there a newer docker image for this?  These are my configurations:
`nodejs: v4.5.0 sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-beta.1 coach: 0.24.5`

**Comment by soulgalore** [comment]
HI @abhagupta great that it works for you! In the coming 5.0 (that I hope we will be able to release next week), we've added video and SpeedIndex to Chrome on Android. I've only tested it on one device so far, so would love feedback :) By the way, do you have a way to throttle the connection or do you run on the connectivity on that device?

@beenanner started to test abd in Docker running on Ubuntu. I tested on Mac and couldn't get it to work (I cannot get the Docker container to get hold of the USB device). I think Jonathan got so far that he could list devices but didn't get the full chain to work, but I'm not 100% sure. It would be super to get it to work on Docker since for SpeedIndex you need [all the dependencies](https://github.com/sitespeedio/docker-visualmetrics-deps/blob/master/Dockerfile) for VisualMetrics. If we get it to work, we will create another Docker file. When we tested it we used https://github.com/sitespeedio/browsertime/pull/304/commits/3ea1fb72599541774de44d5f7074c7f731f0f811 

In that Docker file I added Java, ADB and a start script that starts the adb server, I think that should do but maybe I'm missing something. When I researched it seems like people used adb on Docker but couldn't see a working example. If you find something let us know. I would love to get it to work :)

**Comment by abhagupta** [comment]
@soulgalore we would like to eventually throttle the network speed, but at this point, we are just running using existing connectivity on device.

**Comment by soulgalore** [comment]
Let us look into https://groups.google.com/forum/#!msg/docker-user/UsekCwA1CSI/RtgmyJOsRtIJ and  https://github.com/sorccu/docker-adb

**Comment by soulgalore** [comment]
This will be the issue for implementing it: https://github.com/sitespeedio/browsertime/issues/312

**Comment by abhagupta** [comment]
Thanks @soulgalore . Yes the google group post describes the problem and solution precisely. I am having hard time finding the `/dev/bus/usb` on a MAC at this moment. Do you know whats the alternative of finding usb location in mac.

**Comment by soulgalore** [comment]
@abhagupta I haven't found a working example that it should work on Mac :( There are some issues in the forums at Docker but not a solution. Only examples for Ubuntu.

**Comment by soulgalore** [comment]
@abhagupta about setting connectivity: One way to do it is to run [TSProxy](https://github.com/WPO-Foundation/tsproxy) and bind it to your ip. My local IP is 10.0.1.7 and I start it like this (by default it uses port 8080): 
<code>python tsproxy.py -vvvv --bind 10.0.1.7 --rtt=10 --inkbps=1600 --outkbps=768</code>

Then when starting Chrome on Android I add a flag (my phone is on the same WIFI):
<code>bin/browsertime.js --chrome.android.package com.android.chrome https://en.m.wikipedia.org/wiki/Barack_Obama --chrome.args proxy-server="socks://10.0.1.7:1080"</code> 

Locally on my Mac I've had problems running TSProxy together with Selenium, I couldn't get it to work as expected but maybe use it as a proxy works better and there's also an issue on Github that Pat is working on. TSProxy isn't 100% perfect but I think it will be better than just use the phones connectivity and it's really easy to get going.

**Comment by abhagupta** [comment]
Thanks @soulgalore  I am going to give it a try

**Comment by abhagupta** [comment]
I can close this issue for now since I have started testing android with non-docker version for now. I see you guys have done some work lately for adb on docker which I am gonna look at. Thanks for this one..

**Comment by soulgalore** [comment]
@abhagupta yes it works now using Docker as long as you run Docker on Linux. Browsertime is released and it will come in the next sitespeed.io release. Do you use video/SpeedIndex?

**Comment by abhagupta** [comment]
We keep track of rumSpeedIndex. Not video at this time.
