### ISSUE TITLE
Question: Is IE still supported with sitespeed.io?

### ISSUE THREAD

**Issue by ppcuenca** [sitespeedio/sitespeed.io#1578]
Hi,

I did see some previous documentation that included gathering metrics with Internet Explorer. Is IE still supported?

Thanks,

**Comment by soulgalore** [comment]
Hey @ppcuenca in 3.x you could run IE to collect metrics. The problem for me was that when we had a bug on Windows, it took me really long time to fix them since it is 12-15 years ago I used Windows. 

However: We use Selenium so we could add IE or Edge whatever works with Selenium. What's missing is a way to collect the HAR file (but maybe there's a way to do that nowadays in IE/Edge?). And then it would be some work to get FFMPEG to work. We need to have a contributor/team member that can contribute time to fix and create those things on Windows. I don't know anyone but maybe you @ppcuenca or @auchenberg could help us get hold of someone who want to drive performance on Windows :)

Best
Peter

**Comment by auchenberg** [comment]
I have forward this to the right folks internally on the Edge team. Stay tuned.

**Comment by InstyleVII** [comment]
Following up here, while I can't speak for IEDriver, MicrosoftWebDriver.exe (which is for Edge) currently doesn't have this capability. While it might be interesting to add a command for this, or to allow automation of the devtools to do something like this it's not currently on our radar.

**Comment by soulgalore** [comment]
thanks @InstyleVII 

For minimum support we need webdriver/Selenium bindings for Edge but that exists now right?

Then for getting a HAR out of Egde: For Chrome we parse the internal Chrome trace log, for Firefox we use [an extension](https://github.com/firebug/har-export-trigger) but later this year Firefox will only support [WebExtensions](https://developer.mozilla.org/sv-SE/Add-ons/WebExtensions) and there are some limited support there to get an HAR as long as you have your devtools open (at least moment, hope that can change in the future). I'm not up to speed with Edge plans to support WebExtensions?

**Comment by InstyleVII** [comment]
Yes Selenium support for Edge has been there since our first release so you should be good to go there.

**Comment by soulgalore** [comment]
Closing this since we don't support IE.
