### ISSUE TITLE
Graphite webHost returns undefined

### ISSUE THREAD

**Issue by cambiph** [sitespeedio/sitespeed.io#1587]
Using the latest docker image (sitespeed 5.0.0) there seems to be a problem using graphite.webHost.
When I use --graphite.webHost graphite.***** the logfile shows the following:

> [2017-04-24 12:40:00] INFO: [sitespeedio.plugin.graphite] Send data to Graphite undefined:2003

When I use --graphite.host graphite.**** all is well:

> [2017-04-24 12:43:17] INFO: [sitespeedio.plugin.graphite] Send data to Graphite http://graphite.****:2003

**Comment by soulgalore** [comment]
Hi @cambiph ,
it is two different things: the host is the host where you send the metrics to Carbon, that one always need to be set. 

The webhost is where you send the annotation. By default that is the same as the host, but if you run a large Graphite setup you could have that separated from Carbon, that's why we have that options.

Best
Peter

**Comment by tobli** [comment]
Missing today are checks that all required parameters (i.e. host) are past, so you'd get a proper error message. Most other plugins have that, so it's an easy fix.

**Comment by soulgalore** [comment]
Ah I see you can activate the plugin by only supplying the port. Yep we should fix that!

**Comment by soulgalore** [comment]
Pushed the check in https://github.com/sitespeedio/sitespeed.io/commit/e9ba9f308a75e3f57e3b8fc72a1dc5998f5c8519

**Comment by cambiph** [comment]
Ok thanks for the feedback. I was confused since the docs say that when you provide webHost it is also used as the host but the logfile shows undefined.

**Comment by soulgalore** [comment]
Maye the help is unclear, I'll try to make it cleaner.
