### ISSUE TITLE
--budget.configPath  does not work when sitespeed is run as module

### ISSUE THREAD

**Issue by abhagupta** [sitespeedio/sitespeed.io#1601]
Hi @soulgalore 
Looks like, the `--budget.configPath` does not work when you want to run sitespeed in non-cli form.

My code is below  

``` var options = {
            urls : ["http://www.google.com"],
            browsertime:{
                iterations: 1
            },
            budget :{
                configPath : './budget.json'
            }
        }
        sitespeed.run(options).then(function(results){
            console.log(results);
        }); 
```

Error  :  
```
[2017-05-05 10:17:22] ERROR: TypeError: Cannot read property 'browsertime.pageSummary' of undefined
    at verify (/Users/agupt13/Documents/workspace/experiment/saucelabs_android/node_modules/sitespeed.io/lib/plugins/budget/verify.js:34:16)
```
I do see that this parameter is only parsed here https://github.com/sitespeedio/sitespeed.io/blob/master/lib/support/cli.js#L279-L282
so CLI version works, but not if I am running it as a process ad a node module.

**Comment by abhagupta** [comment]
wrote a PR https://github.com/sitespeedio/sitespeed.io/pull/1602 .

**Comment by tobli** [comment]
Hi @abhagupta!
This is by design, the plugins shouldn't have to deal with parsing config. Instead just parse your config file as JSON, and pass that to as budget.config from your code. The documentation is focused on the cli use, so there are a few differences. The parameters webpagetest.file and webpagetest.script behaves in the same way: file is only applicable when calling the cli.

regards,
/Tobias

**Comment by abhagupta** [comment]
No issues. Thanks @tobli
