### ISSUE TITLE
Question: interpreting metrics in har

### ISSUE THREAD

**Issue by kchoi01** [sitespeedio/sitespeed.io#1655]
Hi, this is a question about how to read the results in general. I am referring to the metrics in the har files (browsertime and webpagetest).

This question comes from the fact that when using multiple tools (e.g. Lighthouse, sitespeed.io, WPT) to measure the same page and then look at metrics that supposedly measure the same thing, they often have very different values. For example, all 3 have speed index but they give vastly different numbers. I suppose they are calculated very differently? Another example is _visualComplete85 in browsertime and _visualComplete85 in WPT. From the name, it sounds like they should be the same metrics but browsertime has a value of 667 (in an example I am currently looking at) and WPT has a value of 7400. And I am guessing the unit is in ms?

I guess my question is if there is any documentations about what these metrics are actually measuring, how they are calculated, what the units are etc.? And how do we combine the results from multiple tools into a coherent narrative?

**Comment by soulgalore** [comment]
Hi @kchoi01 
first explaining the metrics etc: When you do a run there's a file called help.html where we have most definitions of the metrics (and if you click on the metric name from the detailed summary page etc you will end up there). You can check it out here https://examples.sitespeed.io/5.0/2017-04-24-04-44-04/help.html 

All timing metrics is reported in ms and weight in kb (if it doesn't say anything else).

> This question comes from the fact that when using multiple tools (e.g. Lighthouse, sitespeed.io, WPT) to measure the same page and then look at metrics that supposedly measure the same thing, they often have very different values

This is really good and valid question, thanks for asking. I'll try to explain the difference as I see them and then maybe the people behind Lighthouse/WPT can give use their view.

## Lighthouse
SpeedIndex in Lighthouse is created using screenshots from the Chrome devtools timeline (using [Speedline](https://github.com/paulirish/speedline). I personally think that is cool and can produce good metrics. Using Lighthouse is good to like get a feeling for the SpeedIndex for the page, but what's lacking is a way to set constant connectivity, and make multiple runs so you can get consistent values. For other timing metrics for Lighthouse I would personally not use them since they (FCP/FMP calculated internally in Chrome) have been totally off for sites like Wikipedia. I think and hope it will work in the future (it will be really cool to get those values for RUM). 

## WebPageTest
You can set the connectivity and choose different amount of runs, the SpeedIndex is calculated using the recorded video. I think the video is 10 fps for desktop and 60 for mobile. VisualComplete 85% is when 85% (or more) of the current viewport is ready.

## sitespeed.io/browsertime
You can set the connectivity (make sure you use Docker networks and that they really work), choose how many runs and we will record a video of 60fps. VisualComplete85 is the same as for WPT. Right now we use [VisualMetrics](https://github.com/WPO-Foundation/visualmetrics) to calculate SpeedIndex and other visual metrics (created by Pat Meenan who also created WebPageTest). 

I don't think getting consistent values between tools is the right because it will depend on the connectivity you set and CPU power. It's most important to get consistent values and the best way to do that is to use WPT or sitespeed.io. Lighthouse has other good things, like the Coach inspired accessibility etc, so I think you can use Lighthouse for that, but you shouldn't use it to collect SpeedIndex and other timing metrics.

Best
Peter

**Comment by kchoi01** [comment]
Hey Peter, thanks for your detailed reply. 

Speaking of speed index, I wonder how we should interpret this metric and other visual metrics for pages with lots of animations? An example will be Amazon homepage. They have a large image at the top that auto scrolls. Looking at the video, I would consider the page to be visually complete at about 2.8s (in a particular WPT run I am looking at) but because of the changing image, the test considers the last frame to be at about 14s. The speed index then is way higher than what it should be. I would like to hear your thoughts.

**Comment by soulgalore** [comment]
Hey @kchoi01 
I think [Sergey](https://twitter.com/sergeyche) has an idea how it can be solved in the future, there's no tool that supports it today: https://www.youtube.com/watch?v=t6l9U5bC8jA
Best
Peter

**Comment by soulgalore** [comment]
Please re-open if there's something more to be done in this issue!
