### ISSUE TITLE
WPT loadTime not included in the default metrics captured.

### ISSUE THREAD

**Issue by UltraNemesis** [sitespeedio/sitespeed.io#1704]
I noticed that when testing with the WPT integration, the "loadTime" metric is not in the default metrics list and not present int the Grafana dashboard templates either. 

Any reason for this. This metric is one of the reasons I use WPT because in 99% of the cases, it gives me the point when the page has become usable for the user. Value of "fullyLoaded" gets affected if you have any async scripts or continuous ajax polling in your pages. 

Can this metric be added to the default list?

**Comment by soulgalore** [comment]
Hi @UltraNemesis thanks for the report. The history is that we wanted to minimize data sent to Graphite so we focused on the "new" metrics like SpeedIndex since pageLoad isn't a perfect metric, see http://www.stevesouders.com/blog/2013/05/13/moving-beyond-window-onload/ 

But I agree we should add it, let me do that next week so it's there for the next release, then WPT and Browsertime metrics are more inline with each other.

Best
Peter

**Comment by soulgalore** [comment]
This was released yesterday, I've added it to our example dashboard: 
https://dashboard.sitespeed.io/dashboard/db/webpagetest-page-summary
 
Dashboards will be updated next week.
