### ISSUE TITLE
largestassets.summary.json is broken (at least for yahoo.com)

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1718]
The JSON output is broken (at least for yahoo):
`sitespeed.io https://www.yahoo.com/ --plugins.load analysisstorer` as reported by @tufandevrim in #1710.

I did a quick check to verify and the output is broken.

**Comment by tobli** [comment]
Could you please attach a broken file? Seems strange, since the file data is created using JSON.stringify(data)

**Comment by soulgalore** [comment]
https://gist.github.com/soulgalore/6ef372b929f48d6a084d80b544a26889

**Comment by soulgalore** [comment]
Maybe I should add the raw version to, unformated so my formatter doesn't some extra things.

**Comment by tobli** [comment]
😮

**Comment by tobli** [comment]
Ok, I think I understand what happens now. File names and paths are generated based on message type and (optionally url/run). Since some summary messages are sent once per group (per domain + “total”), a number of threads will try to write to the same file name (with different data) at the same time. Hence the mix of chunks from different json structures intermixed. Group needs to be included when building file names.

**Comment by soulgalore** [comment]
ah great @tobli ! I can have a look this weekend and see if there’s a easy fix.

**Comment by soulgalore** [comment]
Actually I think we should add the toplists to the ignore list in https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/analysisstorer/index.js#L8 since it is aggregated data @tobli . I missed that when I created the lists.

**Comment by soulgalore** [comment]
fixed and release some time ago
