### ISSUE TITLE
Something is consuming to much Space on disk

### ISSUE THREAD

**Issue by joside** [sitespeedio/sitespeed.io#1742]
Hi,

I set up sitespeed to watch some metrics of some of our domains. I am using docker-compose, a urls file and a config.json.

In config.json I disabled the html plugin to save disk space (I just need some values for graphite) but the disk space is getting lower and lower.
Is there something else I should disable?

Every hint is welcome.

**Comment by soulgalore** [comment]
Hi @joside 
when I run sitespeed.io for myself I push to S3 and configure it to store the data for X days.

You can disable screenshot and harstorer but I think the best way is to keep the data for a couple days (depending on how much disk you have) and then remove the result dirs that are older than x days. I like to store the result so if I find a regression or a problem I can look at the result.

Best
Peter

**Comment by soulgalore** [comment]
We need more info to help out. Please re-open if you need more help!

**Comment by soulgalore** [comment]
Hi @rohitsethitcs it's better if you create a new issue since your problem doesn't seems related to the problem in the original issue. That's makes it easier for people searching for the same problem etc.

If you mount S3 to your server, you don't need to configure the upload, that should just work. If you mount, you don't need to upload the files in sitespeed.io. If you share how you run, it's easier to help. We have a section on the documentation https://www.sitespeed.io/documentation/sitespeed.io/bug-report/ that helps you write reports that makes it easier for us to help you.

Best
Peter
