### ISSUE TITLE
ERROR: Specified HTML directory '/var/jenkins_home/workspace/performance-tests/output' does not exist.

### ISSUE THREAD

**Issue by joacim-boive** [sitespeedio/sitespeed.io#1774]
Tried following your guide here:
https://www.sitespeed.io/documentation/sitespeed.io/continuous-integration/

I set the properties in the Script Console of Jenkins 2.87:
` System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "sandbox allow-scripts; style-src 'unsafe-inline' *;script-src 'unsafe-inline' *;")`

And I trigger the job using:
`docker run --privileged -v ${WORKSPACE}:/sitespeed.io sitespeedio/sitespeed.io --outputFolder output https://www.sitespeed.io/ -n 1`

I can find the files as expected under "output".

But htmlpublisher still fails:

```
14:52:26 Started by user Joacim Boive
14:52:26 Building in workspace /var/jenkins_home/workspace/performance-tests
14:52:26 [performance-tests] $ /bin/sh -xe /tmp/jenkins619138959100728924.sh
14:52:26 + pwd
14:52:26 + docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock --rm -v /var/jenkins_home/workspace/performance-tests:/sitespeed.io sitespeedio/sitespeed.io https://www.sitespeed.io
14:52:27 Google Chrome 60.0.3112.78 
14:52:27 Mozilla Firefox 54.0
14:52:28 [2017-11-03 13:52:28] INFO: Versions OS: linux 4.9.49-moby nodejs: v6.11.1 sitespeed.io: 5.6.5 browsertime: 1.9.4 coach: 0.36.0
14:52:28 [2017-11-03 13:52:28] INFO: Starting chrome for analysing https://www.sitespeed.io 3 time(s)
14:52:28 [2017-11-03 13:52:28] INFO: Testing url https://www.sitespeed.io run 1
14:52:32 [2017-11-03 13:52:32] INFO: Testing url https://www.sitespeed.io run 2
14:52:36 [2017-11-03 13:52:36] INFO: Testing url https://www.sitespeed.io run 3
14:52:40 [2017-11-03 13:52:40] INFO: 10 requests, 96.60 kb, backEndTime: 775ms (±42.34ms), firstPaint: 825ms (±46.15ms), DOMContentLoaded: 791ms (±43.11ms), Load: 895ms (±43.35ms), rumSpeedIndex: 835 (±48.59) (3 runs)
14:52:42 [2017-11-03 13:52:42] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2017-11-03-13-52-28
14:52:42 [2017-11-03 13:52:42] INFO: Finished analysing https://www.sitespeed.io
14:52:43 + test -d reports
14:52:43 Build step 'Execute shell' marked build as failure
14:52:43 [htmlpublisher] Archiving HTML reports...
14:52:43 [htmlpublisher] Archiving at PROJECT level /var/jenkins_home/workspace/performance-tests/output to /var/jenkins_home/jobs/performance-tests/htmlreports/HTML_Report
14:52:43 ERROR: Specified HTML directory '/var/jenkins_home/workspace/performance-tests/output' does not exist.
14:52:43 Finished: FAILURE
```

**Comment by soulgalore** [comment]
Hej @joacim-boive thanks for reporting, hmm I wonder if something changed in the HTML plugin? I'll add this to my task list for next week, I haven't had Jenkins up and running for a while now, so I need some time to just get it going.

Best
Peter

**Comment by soulgalore** [comment]
Hi @joacim-boive put some time on this yesterday, just getting Jenkins to work (upgrading Java 1.7 etc) took a while. I wonder if the HTML-plugin changed or else did something really stupid in the docs. The HTMLplugin reads the files relative to the workspace so changing to just include the output folder works for me:
<img width="855" alt="screen shot 2017-11-05 at 2 36 56 pm" src="https://user-images.githubusercontent.com/540757/32415259-0fcb74c8-c237-11e7-9086-c42dd5845955.png">

I'll update the docs, let me know that it also works for you so that I can close the issue.

Best
Peter

**Comment by joacim-boive** [comment]
Thanks for the input!

But after playing some more with this the actual problem seems to be that no files, or directories, are created.

If I run this on my mac it works as expected:
`docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --outputFolder output https://www.sitespeed.io -n 1`

The output-folder is created, where I issued the command. and populated with the results.

But doing the same in the docker container doesn't create anything.
Even when logged in as root - everything looks like it works:

```
Google Chrome 60.0.3112.78
Mozilla Firefox 54.0
[2017-11-06 09:05:07] INFO: Versions OS: linux 4.9.49-moby nodejs: v6.11.1 sitespeed.io: 5.6.5 browsertime: 1.9.4 coach: 0.36.0
[2017-11-06 09:05:08] INFO: Starting chrome for analysing https://www.sitespeed.io 1 time(s)
[2017-11-06 09:05:08] INFO: Testing url https://www.sitespeed.io run 1
[2017-11-06 09:05:12] INFO: 10 requests, 96.64 kb, backEndTime: 616ms, firstPaint: 655ms, DOMContentLoaded: 633ms, Load: 732ms, rumSpeedIndex: 671
[2017-11-06 09:05:13] INFO: HTML stored in /sitespeed.io/output
[2017-11-06 09:05:13] INFO: Finished analysing https://www.sitespeed.io
root@a7fcf0083db8:/home#
```

Any ideas?

**Comment by soulgalore** [comment]
Ok, if I understand correctly:
1. In Jenkins everything run (the user in Jenkins can use the Docker command) and when you check the logs on Jenkins you can see that everything is ok?
2. But then when you check the actual folder there is no data there?

Where you run the script in Jenkins, can you echo the workpace and ls the output dir? Something like echo ${WORKSPACE} and ls -la ${WORKSPACE}\output just so we know that we are looking at the right place?

**Comment by joacim-boive** [comment]
To leave out any Jenkins config problems I'm issuing the commands manually in the terminal of the Jenkins Docker Container.

I do: pwd and it shows me that I'm in: ~/workspace/performance
Which is the correct catalog.

I can do sudo docker run hello-world and it works.

If I do:
`sudo docker run --privileged -v /var/jenkins_home/workspace/performance:/sitespeed.io sitespeedio/sitespeed.io --outputFolder /var/jenkins_home/workspace/performance/output https://www.sitespeed.io -n 1`

No files are created (I'm standing in /var/jenkins_home/workspace/performance when I issue the above command.)

**Comment by soulgalore** [comment]
@joacim-boive in the example you mix paths both inside and outside the container. Let me try to explain it better. Inside the Docker container, the container has it own folder structure, with -v we map a folder from your physical server inside your container, so inside your container you cannot use the paths that you use on your physical server. Ehh, sorry bad explanation, let me show you instead:
**--outputFolder /var/jenkins_home/workspace/performance/output** doesn't exist inside the container.  When you add **-v /var/jenkins_home/workspace/performance:/sitespeed.io ** that path in the container is called **/sitespeed.io**.

So if you run: `sudo docker run --privileged -v /var/jenkins_home/workspace/performance:/sitespeed.io sitespeedio/sitespeed.io --outputFolder output https://www.sitespeed.io -n 1` that should just work (because in our Docker file we have /sitespeed.io as the [working directory](https://github.com/sitespeedio/sitespeed.io/blob/master/Dockerfile#L24).

If you want you can also get rid of sudo by [something like this](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04#step-2-—-executing-the-docker-command-without-sudo-optional).

I cross my fingers that it works now :)

**Comment by joacim-boive** [comment]
Nope, didn't work.

I created a docker image from what I base my Jenkins setup on to try and get to the root of the problem:

```
from debian
USER root

RUN apt-get update -y
RUN apt-get install -y \
     apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common

RUN curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add -
RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
   $(lsb_release -cs) \
   stable"

RUN apt-get update -y

RUN apt-get install -y \
	nano \
	docker-ce

# Start the docker service
RUN service docker start
```

Build it:
`docker build -t debian-test .`

Then run it:
`docker run -it -v /var/run/docker.sock:/var/run/docker.sock debian-test`

Here I can do:
`docker run hello-world`

And it works. :)

But, if I try and do:
```
cd home
sudo docker run --privileged -v "$(pwd}"/sitespeed:/sitespeed.io sitespeedio/sitespeed.io --outputFolder output https://www.sitespeed.io -n 1
```

It runs the sitespeed test fine but doesn't create any files/folders in the running directory.

What am I missing? :)

**Comment by soulgalore** [comment]
Hehe :)

But if the files isn't created you should get an error message from sitespeed? You don't get that?

Can we simplify by just removing as much as possible, so try:

`sudo docker run  -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --outputFolder output https://www.sitespeed.io -n 1`

I've removed privileged because that's only needed when you changing networks and changed path to the folder. If that doesn't work for you, what happens if you just don't add that extra folder?
`sudo docker run  -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://www.sitespeed.io -n 1`

**Comment by joacim-boive** [comment]
Both run without any issues but none of the produce and folders or files.

Have you had a chance to test with the Dockerfile provided? Does that work for you?
I tried using Ubuntu as well as the "From", but no difference.

**Comment by soulgalore** [comment]
ping @beenanner do you have any fresh ideas why the mapping doesn't work for @joacim-boive 

@joacim-boive can you try with an absolute path? so `-v /this/is/the/path:/sitespeed.io`. What OS do you run on your host server? Docker version?

**Comment by joacim-boive** [comment]
@soulgalore I use macOS High Sierra 10.13.1 with Docker CE Version 17.09.0-ce-mac35 (19611)

**Comment by soulgalore** [comment]
ok I thought the problem was on a production server. in the old days at least you could only mount files from your users home dir on Mac, but I think that has been fixed?

**Comment by joacim-boive** [comment]
@soulgalore That would be before my time. :)
Mounting volumes and directories work fine on Mac, it's what I use to run Jenkins and that works perfectly. Jenkins has no problem creating directories and files in my mounted volumes.

**Comment by joacim-boive** [comment]
Well, this was embarrassing... :)

I expected to see the output as you do above, in the directory you're executing the command.
But on Mac I need to do: `screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty`

Then `cd /home/sitespeed`

And the files are created there.

**Comment by beenanner** [comment]
All good @joacim-boive let us know if you run into anything else!
