### ISSUE TITLE
Use Grafana annotations

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1826]
The annotations today use Graphite/InfluxDB. It would be cool to start use the generic Grafana ones (released in 4.6.0) so that we have generic annotations for all Grafana supported storages.

**Comment by kkopachev** [comment]
Hi Peter
Is it possible for short-term soolution is to add new config variable which will switch the endpoint used to submit annotations from current `/events/` to what grafana expects `/api/annotations/graphite`  ?https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/graphite/send-annotation.js#L37
Not ideal, but could be fast and cheap win. We already have `graphite.webHost` and port configurable.

I am only running full-blown graphite only to store these annotations and nothing else, since metrics go to [go-carbon](https://github.com/lomik/go-carbon/).

Thoughts?

**Comment by soulgalore** [comment]
Hi @kkopachev I see. Let me have a try during the weekend, thinking maybe a Grafana plugin would be nice, it will add extra config but makes things cleaner in the future.

Best
Peter

**Comment by soulgalore** [comment]
@kkopachev I'm thinking like this: If you configure --grafana.host all annotations will be sent to Grafana (if you also add resultBaseURL as before). If you leave out the grafana host, it will be sent to Graphite/InfluxDB.

**Comment by soulgalore** [comment]
@kkopachev have a working branch but  I cannot see that Grafana support tags that are templates? Do you know? http://docs.grafana.org/reference/annotations/ if that is right the current version need tag names instead of template variables, meaning it will not work.

**Comment by soulgalore** [comment]
Yep we need to wait for https://github.com/grafana/grafana/pull/10163

**Comment by kkopachev** [comment]
Oh, okay. Thanks for implementing. Hope templated annotations can make it to grafana 5.0

**Comment by soulgalore** [comment]
It looks like Grafana will support this in the next release (or it will sooon be merged).

**Comment by soulgalore** [comment]
This was released I late 7.x versions.
