### ISSUE TITLE
Does sitespeed save resource URL?

### ISSUE THREAD

**Issue by bharat129** [sitespeedio/sitespeed.io#1846]
Hi @soulgalore ,

We are trying to identify which resource/image has the largest size?

When sitespeed stores the results, does it save the size of each resource (img, css,js) with the URL?
so that we can query in the graphite DB and show it in dashboard.

Currently, I am not able to query the graphite DB for this info.

PS: we are not looking for the HAR, we are looking for information against each resource URL.

Regards,
Bharat

**Comment by soulgalore** [comment]
Hi @bharat129 ,
it's configurable to send the size of each asset to graphite but it's not recommended since it will not scale in Graphite. For every unique asset URL Graphite will prepare the size depending on your configuration, so if your site has banners with unique resources it will take up space for one resource even though it is only used once. I think we send the largest size and that you can configure to send the top ten, but not the URL, then if you have an asset that is really large, you need to go to the HTML report (or the HAR) and checkout which one that's the problem.

Best
Peter

**Comment by bharat129** [comment]
Thanks @soulgalore . We are creating custom script taking inputs from HAR file.
