### ISSUE TITLE
Reduce (or delete) the output: parameters, influence to metrics collecting 

### ISSUE THREAD

**Issue by suratovvlad** [sitespeedio/sitespeed.io#1869]
I couldn't find info in documentation about what's happen if use "--browsertime.skipHar", "--no-browsertime.video" and "--plugins.remove html,screenshot,coach" flags for sitespeed.io.

As I can see, the produced resulting folder has smaller size, but I can't figure out which metrics wouldn't be calculated.

Could you give more information about these parameters, please?

Also, is there any way to disable folder output or setup cleaning after analyzing?

**Comment by soulgalore** [comment]
Hi @suratovvlad 
let me add a section for that on https://www.sitespeed.io/documentation/sitespeed.io/best-practice/ I hope to do that tonight or tomorrow.

First just so I understand:
You want to collect some metrics and keep the result/memory footprint as small as possible?  Can you tell me a little more about how you plan to run your test and how you want to use the result?
There are configs options to minimize the result, but I personally really like having the output for some time so it's easy to find regressions or just to verify that the tests are running as they should. That's why I like dumping the result to S3 and then configure the data only to live a couple of weeks or whatever so you have a maximum cost.

However, if you really wanna remove data, I think the video and the screenshot(s) take most space.
`--browsertime.video false --browsertime.speedIndex true ` will record a video but remove it after Visual Metrics has analyzed the video (we need to update the CLI docs here).

If also add `--browsertime.videoParams.createFilmstrip false` it will remove the small screenshots.

Then for the main screenshots, you can either compress them more, or just remove them by disabling the plugin.

**--browsertime.skipHar** will not produce a HAR = you will not get any timings per request and per domain.

**--no-browsertime.video** should be **--browsertime.video false** to not store the video.

**--plugins.remove html,screenshot,coach** is removing pluging. Removing the HTML plugin will remove the creation of HTML, screenshit will remove the creation of the screenshot and removing the coach will remove fetching all the metrics coach uses. What metrics will you focus on?

If you push the HTML result to S3 you can cleanup with **--s3.removeLocalResult** .

Best
Peter

**Comment by suratovvlad** [comment]
Hi @soulgalore 
Thank you very much for the quite carefull explanation about these options!

Yes, you understand me right, I want to collect metrics every 5 or 10 minutes and keep the result as small as possible, because the size of resulting folder becomes huge after several days of collection process.

I've set up graphite port and host to store collected metrics inside graphite database and I don't need for any files from sitespeed such as video, HAR files and any size of screenshots, however I'm interested in several metrics: 
-pageTimings (DOM, backEnd, frontEnd), 
-a lot of navigationTimings (with response, dom, domain, load and connect), 
-and such timings as fully loaded and first-contentful-page.

If I understand you right, most of these metrics wouldn't be collected if I set "--browsertime.skipHar" parameter, however I only want to get these metrics from graphite and don't want to keep the file.

It would be great if sitespeed has the option to clenup result (including har and logs) after sending metrics to graphite

**Comment by soulgalore** [comment]
I would just run it as default and then **rm -fR ...** on the result dir when your run is finished, then there is no fuss :)

>  I want to collect metrics every 5 or 10 minute

Do you test the same site, how often do you push releases? :) 5-10 seems really often to test, I usually run ones an hour (with a couple of runs) but I guess it depends on the use case.

**Comment by soulgalore** [comment]
@suratovvlad I finally got around to update the docs, it will be live in a couple of minutes, look under https://www.sitespeed.io/documentation/sitespeed.io/best-practice/#handling-big-amount-of-data

Let me know if you need more info, else I'll close the issue.

**Comment by suratovvlad** [comment]
@soulgalore Hi! Thank you very much, the docs became more helpful, and there is much less output with this configuration! I think I don't need more info!

**Comment by soulgalore** [comment]
Perfect.
