### ISSUE TITLE
Incorrectly generated report with multiple urls, and url contains parameters

### ISSUE THREAD

**Issue by mgasiorowski** [sitespeedio/sitespeed.io#1872]
When I use multiple urls and urls contain parameters, report is generated incorrectly. All pages in Pages view in report file contains only one analyzed url.

For example, in report I have three pages:
- Inbox
- Contacts
- Message_view
<img width="983" alt="screen shot 2018-01-11 at 13 14 29" src="https://user-images.githubusercontent.com/1914132/34825089-65237258-f6d1-11e7-9cfd-131ccc17f15e.png">

When I go for example to Contacts I gets Message_view.

I reproduced this on:
- Mac OS X 10.12.6,
- CentOS Linux release 7.4.1708 (Core),
- Docker version 17.12.0-ce, build c97c6d6,
- Sitespeed version 5.6.5 and 6.2.3,

I attach code to reproduce this problem
[sitespeed.zip](https://github.com/sitespeedio/sitespeed.io/files/1622483/sitespeed.zip)

Command
`docker run --rm --shm-size=1g -v $(pwd):/sitespeed.io sitespeedio/sitespeed.io:6.2.3 urls.txt --browser chrome --connectivity native -m 1 -n 1 --preScript loginToMail.js`

And generated report
[2018-01-11-11-48-29.zip](https://github.com/sitespeedio/sitespeed.io/files/1622500/2018-01-11-11-48-29.zip)

**Comment by soulgalore** [comment]
Thank you @mgasiorowski for the report and thanks for attaching the results, that really helps!
 
It looks like we handle the different URLs on the pages level, but we don't generate them individually. Originally we treated all URLs with hashbangs the same, but then we added the ability to give them simple names (as you used) and it seems to work except that we don't generate single reports for each URLs (or generate them with the same name, since we ignore everything after the hashbang). 

A simple ugly hack for you would be to add an extra query parameter to each URL you test, I think it then will generate the individual URLs (queryparameters are used to generate the metrics on file), until we have looked at it and see if there's an easy way to fix that. Can you test that and get back so I know if it works or not?

All the best
Peter

**Comment by soulgalore** [comment]
yep with different parameters on different URLs so that the URL is unique without everything after the #, hmm ok, let me have a look tonight or tomorrow. thanks for trying it out.

Best
Peter

**Comment by soulgalore** [comment]
@mgasiorowski I think the hack should work, I just tested.

Not working
```
https://www.sitespeed.io#plain plain
https://www.sitespeed.io#more more
```
Adding fake parameter, generating the pages
```
https://www.sitespeed.io?apa=hepp#plain plain
https://www.sitespeed.io?apa=hepp2#more more
```

Don't mean that it is right, but at least then I think you can continue with your testing :)

Best
Peter

**Comment by mgasiorowski** [comment]
Yes, that work. I put in it the wrong place.

Correct example
`https://mail.yandex.com/?uid=586653896&login=sitespeedtest?parameter=1#inbox Inbox
https://mail.yandex.com/?uid=586653896&login=sitespeedtest?parameter=2#contacts Contacts
https://mail.yandex.com/?uid=586653896&login=sitespeedtest?parameter=3#message/164381386399023106 Message_view`

Thank you very much ;)

Best,
Maciej

**Comment by a-venger** [comment]
Hello. I have the same problem.
Are there some changes since last reply?

**Comment by soulgalore** [comment]
@a-venger no, you need to do as Maciej for a workaround.

**Comment by a-venger** [comment]
@soulgalore ok. Thanks

**Comment by soulgalore** [comment]
This should work out of the box if you add `--spa`.
