### ISSUE TITLE
Files not corretly uploaded to S3

### ISSUE THREAD

**Issue by mglauche** [sitespeedio/sitespeed.io#1916]
Hi,

I'm having issues with the s3 upload engine, it often failes to upload all content from the local directory to the s3 bucket. 
For example if i specify "-n 3", i'm seeing 0.html, 1.html, 2.html, but the index.html is missing.
Similar problem exist when using -n 1, here the screenshot directoy is not transfered correctly.
Any idea how to debug these issues?

**Comment by soulgalore** [comment]
Hi @mglauche thanks for reporting! Have you been able to verify that it is the upload that fails (the files are created by sitspeed.io)? I think we have the s3 uploading logs disabled even on default because it logs so much, but I'll check if we can turn that on. Also you run version 6.x right or is it a earlier version of sitespeed.io? Also where is your bucket located. There are configurations you can add (like number or retries (I think three is default and that should be enough). We use https://www.npmjs.com/package/s3 for the upload.

No errors in the logs I guess then?

Best
Peter

**Comment by mglauche** [comment]
yes, the files are correctly generated in the local directory, for example:

-rw-r--r-- 1 root root  939611 Feb 14 14:04 0.html
-rw-r--r-- 1 root root  945784 Feb 14 14:04 1.html
-rw-r--r-- 1 root root  939113 Feb 14 14:04 2.html
drwxr-xr-x 4 root root    6144 Feb 14 14:04 data/
-rw-r--r-- 1 root root 2682246 Feb 14 14:04 index.html

data has:
-rw-r--r-- 1 root root 2603510 Feb 14 14:04 browsertime.har
drwxr-xr-x 2 root root    6144 Feb 14 14:04 screenshots/
-rw-r--r-- 1 root root 1247978 Feb 14 14:04 trace-0.json.gz
-rw-r--r-- 1 root root 1247657 Feb 14 14:04 trace-1.json.gz
-rw-r--r-- 1 root root 1260695 Feb 14 14:04 trace-2.json.gz
drwxr-xr-x 3 root root    6144 Feb 14 14:04 video/

however in s3, the screenshots directory, as well as the index.html is missing. I've now set up a small webserver via efs to serve the files without any problem.

**Comment by mglauche** [comment]
docker run --privileged --shm-size=1g --rm -v /var/www/html:/sitespeed.io --name sitespeed sitespeedio/sitespeed.io -V
Google Chrome 63.0.3239.132
Mozilla Firefox 54.0.1
6.3.5

**Comment by soulgalore** [comment]
Ok. We did a fix a while ago for the signatureVersion: 'v4' (that's needed for Frankfurt and all EU locations) where we override the setup with the aws-sdk (since the node version we use hasn't been updated for years). I think we need to move to another aws lib. Either use the aws-sdk directly or if find another one that is uptodate. @beenanner what do you think?

**Comment by wolframkriesing** [comment]
@mglauche as @soulgalore mentioned we also had an issue with uploading to older s3 buckets, like Frankfurt, so we just switched to one that uses v4, and it worked out of a box (i think we use dublin)

**Comment by soulgalore** [comment]
When I updated the s3 plugin (to use our own impl) I haven't seen this problem, so closing this, but please re-open if you have problem with 7.x
