### ISSUE TITLE
how to check speed index when have load balancer ?

### ISSUE THREAD

**Issue by spham** [sitespeedio/sitespeed.io#1932]
i m guess about speed index on load balancer ?

if we fetch data every hour , but it's not the same server.

so , how to consider this ?

**Comment by soulgalore** [comment]
Hi @spham 
but the servers are the same our do mean that one would be slower than the other? It depends on what you want to measure:
* Do you want to find regressions, then maybe you can test earlier on your flow like your stage server?
* If you want to test as it happens for a user, then I guess it is ok since users also will hit different servers?

Best
Peter

**Comment by spham** [comment]
i would like measure speedindex, but it will change bellow load of server.
