### ISSUE TITLE
S3 - Timeout Error

### ISSUE THREAD

**Issue by mbulfair** [sitespeedio/sitespeed.io#1962]
After providing the S3 credentials, I notice a issue, where it will say in the log.

![image](https://user-images.githubusercontent.com/5325543/37977732-5f6d5c4a-31b2-11e8-92c6-a6e7c4206511.png)
and 
![image](https://user-images.githubusercontent.com/5325543/37977790-802769ee-31b2-11e8-89f4-60391b486675.png)

What's weird is the files DO in fact get uploaded to my bucket. However the plugin doesn't seem to know it's done. 

I am running 6.5.1.

**Comment by soulgalore** [comment]
Hi @mbulfair ,
thanks for the report! I’ve seen we got the same in our logs since a while ago but haven’t spent any time understanding what’s going on. Changes I know we done in our env is that we upload from two different servers to the same bucket and I think a code change was pushed for s3 with the last release (but I don’t think it should cause it). Let me look at it tonight.
Best 
Peter

**Comment by mbulfair** [comment]
I would also point out that the version of the s3 plugin looks to be out of date, and may not be what the current AWS CLI needs to fully work.

**Comment by soulgalore** [comment]
We are using https://github.com/andrewrk/node-s3-client and patch with aws-sdk 2.168.0. I would love to switch to another module, if there is something out there, any recommendations? 

Maybe the SDK is better now, when I looked at it the last time it looked it was designed by Java developers ;D

**Comment by soulgalore** [comment]
In 7.x I've rewrote the S3 client, so we skipped using node-s3-client. So far I haven't seen any errors. Let me know if you still have the problem.
