### ISSUE TITLE
InfluxDB event annotations tags

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#1984]
Hi there.

I'm trying to visualize report URLs (--resultBaseURL ) on Grafana dashboard. I can see URLs in dashboard table but it's not possible to filter them by page, browser etc.

Looks like send-annotation.js pushing data to InfluxDB not in right format. 
Original lib send tags=\"native,chrome,sitespeed_io,_,default\"
I've updated it and tags are pushed this way "connectivity=\"native\",browser=\"chrome\",group=\"sitespeed_io\",page=\"_\"
and filtering by tags works perfect now.

Please take a look at updated lib.
[send-annotation.zip](https://github.com/sitespeedio/sitespeed.io/files/1925672/send-annotation.zip)

Best Regards.

**Comment by soulgalore** [comment]
Hi @Icecold777 
at the moment we filter them only on tag so getting the annotations looks like this: 
`select title, text, tags from events where $timeFilter AND "tags" =~ /$group/ AND "tags"  =~ /$page/ AND "tags" =~ /$browser/ AND "tags" =~  /$connectivity/ AND "tags" =~  /$category/`

If you can send a PR instead of a zip with the change and then also update the dashboard annotation in https://github.com/sitespeedio/grafana-bootstrap-docker/blob/master/dashboards/influxdb/pageSummary.json 

Thanks
Peter

**Comment by Icecold777** [comment]
Thank you for your answer. Your way of tagging is less excessive. I close the issue because it's not an issue at all.
