### ISSUE TITLE
custom plugin - API rest upload file in docker container

### ISSUE THREAD

**Issue by amic81** [sitespeedio/sitespeed.io#2044]
Hi,

I have created a script (launched as a plugin) that starts with the message 'html.finished' just before the end of the processing of sitespeed (INFO: Finished analysing).

This script makes an API call rest that as an operation uploads the file browsertime.har (POST).

```
var request = require('request');
	var fs = require("fs");

	var formDataHAR = {
	  file: fs.createReadStream(file_browsertime.har)
	};
	
	const optionsFormHAR = {
		url:'http://X.X.X.X:8080/api/X/save/file', 
		headers: {'X-Auth-Token': 'XauthToken'},
		qs: {
		  'requestId' : '1',
		  'fileType' : '2'
		},
		formData: formDataHAR};

	request.post(optionsFormHAR, function optionalCallback(err, httpResponse, body) {
	  if (err) {
		return console.error('upload failed:', err);
	  }
	  console.log('Upload successful!  Server responded with:', body);
	});
```

I verified launching the same script on the container (without the processing of sitespeed) and the API works correctly.
  
While when it is launched API at the end of sitespeed, container side ends without writing anything and server side (Java / jetty) generate the error

> org.eclipse.jetty.io.EofException: Early EOF

is there any active proxy? or other?

I hope I have given you all the information you need, otherwise let me know.

Thanks
amic81

**Comment by soulgalore** [comment]
Hi @amic81 
no no proxy.

>  API at the end of sitespeed,

So what does your plugin look like? What message do you act on (https://www.sitespeed.io/documentation/sitespeed.io/plugins/#important-messages)? 

FYI  you can use the sitspeed.io log and log what's happening in your plugin. Checkout this plugin how you can get hold of the log https://github.com/sitespeedio/plugin-third-party-decode/blob/master/lib/index.js#L15 - then when you run your plugin it's easier to follow what happens.

You should make sure that your plugin return a promise that resolves when the file is sent, so that the sitespeed.io waits for your plugin to actually finish before moving into the next phase.

Best
Peter

**Comment by soulgalore** [comment]
Did this work out for you @amic81 ? Else let us know if you need help.

**Comment by amic81** [comment]
Yes, it worked. Thank you so much for the support. ;-)

**Comment by soulgalore** [comment]
great!
