### ISSUE TITLE
Basic auth not working in pre-scripts

### ISSUE THREAD

**Issue by shiouen** [sitespeedio/sitespeed.io#2061]
Basic auth credentials are not used by pre-script driver.get(<url>).

- Sitespeed 6.2.3: pre script gets stuck at driver.get() forever.
- Sitespeed 7.0.0: pre script continues past driver.get() but the page is not loaded and the driver will be unable to do anything page related (e.g.: add a cookie).

Temporary solution: format the url with basic auth credentials https://username:password@www.example.com

I'm not sharing URLs as they are only reachable from the internal network.

**Comment by soulgalore** [comment]
Thanks @shiouen let us have look, this should actually be in Browsertime, I will link an issue there. Need to find a good example page(s) behind basic auth so we can have a working example.

**Comment by soulgalore** [comment]
It looks like the problem is in the Browsertime extension: We set the basic auth for the specific URL that you are testing: 
https://github.com/sitespeedio/browsertime-extension/blob/master/background.js#L27-L59

But in your case with a login URL that will not work.

@tobli @beenanner do you have an idea of how we can fix that? Can the URL have wildcards or just set on the top domain?

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onAuthRequired#Examples

**Comment by soulgalore** [comment]
With the "new" scripting functionality you can use basic auth direct in the script and get away fixing it that way.
