### ISSUE TITLE
execute sitespeed.io with docker-compose 

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#2064]
Hello, 
By default docker-compose.yml contains _command: -V_ line which works as expected. Then I can easily do _docker-compose run sitespeed.io https://sitespeed.io_ and it works perfect but creates new container.

I'm trying to run sitespeed.io reusing the same container after _docker-compose up -d sitespeed.io_.
So I replaced docker-compose.yml line with _command: https://sitespeed.io_ passing the URL to start.sh entrypoint right from container creation but see 

`Google Chrome 66.0.3359.181
sitespeed       | Mozilla Firefox 61.0
sitespeed       | [2018-05-29 16:54:56] INFO: Versions OS: linux 4.4.0-1060-aws nodejs: v8.11.1 sitespeed.io: 7.0.0 browsertime: 3.0.13 coach: 2.0.2
sitespeed       | [2018-05-29 16:54:57] INFO: Starting chrome for analysing https://sitespeed.io 3 time(s)
sitespeed       | [2018-05-29 16:54:57] INFO: Testing url https://sitespeed.io iteration 1
sitespeed       | [2018-05-29 16:55:01] ERROR: UrlLoadError: Failed to load/verify https://sitespeed.io uri:chrome-error://chromewebdata/
sitespeed       |     at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:194:15)
sitespeed       |     at <anonymous>
sitespeed       |     at process._tickCallback (internal/process/next_tick.js:188:7)`

docker inspect of both containers shows me the same args list. 
What is going wrong?

PS. The reason I'm trying it is I want to use sitespeed.io as service with _docker-compose start sitespeed.io_ without creating new containers. Please let me know if such approach is totally wrong.

**Comment by soulgalore** [comment]
Hi @Icecold777 
I'm not sure, I need to look into it. Our current Docker setup is built upon creating a new container per test you run. What worked well with that approach is that everything is cleaned up and we know that we start with a new fresh container for each run.

So we don't recommend people running sitespeed.io with docker compose (I'll update the docs, I know its there) since then you probably run other containers on the same machine? For best performance and more stable metrics it's better to run sitespeed on a standalone server (docker run ...) and then I don't think there's a use case for compose, or am I missing something? Maybe I am :)

Best
Peter
