### ISSUE TITLE
Send metrics/video on timeout

### ISSUE THREAD

**Issue by scabenga** [sitespeedio/sitespeed.io#2078]
Hi Guys,

Once again, thanks so much for this valuable application 👍 
This isn't so much an issue, just a query.

Is it possible to send/save metrics/annotations/video/har etc even though there is a timeout when the page is loading.  I think this is useful to see if there are any errors in the page during the loading process to assist with troubleshooting.

Forgive me if this has been asked before however i can't find anything.

Thanks,
scabenga

**Comment by scabenga** [comment]
Hi @soulgalore 

Thanks for the information.  I am currently stating my test should end using "--browsertime.pageCompleteCheck".  This happens when a specific class is available.  However the problem comes in when there is an error prior to the class is available and the test times-out and ends, thus we are unsure what exactly caused the page to not load fully.

Would the pageLoadStrategy help in this regard?

I hope this makes sense.

Thanks!

**Comment by soulgalore** [comment]
Yes try out just change the pageLoadStrategy. You can also increase the timeouts:
https://www.sitespeed.io/documentation/browsertime/configuration/ (checkout timeouts section and add a browsertime before the timeouts). Else if you could share the URL and the check I can have a look if I understand what goes wrong.

Best
Peter

**Comment by scabenga** [comment]
Hi @soulgalore , i've tried this out and it doesn't seem to do what i need.  In essence, i would like still collect all stats, video and screenshot when the error "{ "browsertime": "UrlLoadError" }" is thrown.  Currently it doesn't send any metrics to Graphite/InfluxDB and doesn't create a video or screenshot.

**Comment by soulgalore** [comment]
Yeah but I don't know if it works or not, can you share the URL and the script you are running so we can help you?

**Comment by scabenga** [comment]
Hi @soulgalore , i've substituted my URI for another one, however it has the same results.

`docker run --shm-size=2g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.0.0 https://news.sky.com --browsertime.viewPort 1334x750 --browsertime.userAgent "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0 like Mac OS X) AppleWebKit/602.1.38 (KHTML, like Gecko) Version/10.0 Mobile/14A5297c Safari/602.1" -n 1 -c custom --browsertime.connectivity.downstreamKbps 9800 --browsertime.connectivity.upstreamKbps 4900 --browsertime.connectivity.latency 50 --html.showAllWaterfallSummary true --video --har --browsertime.pageCompleteCheck 'return (document.getElementsByClassName("background-scaling").length > 1)' --browsertime.timeouts.pageCompleteCheck 60000 --plugins.remove coach --browsertime.pageLoadStrategy none --verbose`

**Comment by soulgalore** [comment]
Hi @scabenga thanks, I'll try to break it down step by step:

If the pageCompleteCheck never will be true, the page will timeout = the page wasn't loaded according to the rules we have setup. So in the case of trying to get the element on sitespeed.io it will always timeout since the criteria in the check will never be true. Browsertime will run that script in the browser over and over until the timeout kicks in. So this will only work on a page that has two  elements with the classname background-scaling? Do you see how the page complete check work or can I try to explain it better? You can also check the docs https://www.sitespeed.io/documentation/sitespeed.io/browsers/#choose-when-to-end-your-test

Conceptuelly we need to know when a page has finished loading because that's when we can start to run the scripts we execute to measure things. If we don't end the tests at the same times between runs, that can give us different results.

One last things, do you set the connectivy on the outside? Right now it looks like you set different connectivity settings but you doesn't change the connectivity engine. We should add a log so it is clear when that happens. In 6.0 we removed the default tc setting in Docker and you need to either use Docker networks or Throttle checkout the connectivity page: https://www.sitespeed.io/documentation/sitespeed.io/connectivity/

Best
Peter

**Comment by scabenga** [comment]
Hi @soulgalore the page has the element which is presented when the page becomes interactive.  During the loading process there is a login which happens amongst other things.  If there is an error during on of these the class will never be true.  Which is why i'm after a way for browsertime to still gather the har, screenshot etc even though there is a timeout.

**Comment by beenanner** [comment]
@scabenga I think the pageCompleteCheck needs to finish successfully for the graphite plugin to kick in. Could you try tweaking your browsertime.pageCompleteCheck to make sure it always returns true by adding the timeout logic to it?

Something like
```
return ((document.getElementsByClassName("background-scaling").length > 1) || (performance.now() > 60000))
```
See if that gets you closer to your goal and let us know!

**Comment by scabenga** [comment]
Hi @soulgalore and @beenanner this is now working as i expected.  Thanks for the assist.
On another note, are there any plans to add 4G/LTE to Throttle?

**Comment by soulgalore** [comment]
Great! No, but we can do that, but you should be able to set your own settings, so you can choose upstream/downstream?

Best
Peter

**Comment by scabenga** [comment]
Cool, thanks, yeah i've been reading up.
Just to confirm, i can add an alias by adding the below?
--browsertime.connectivity.alias 4G

**Comment by scabenga** [comment]
Confirmed, this is how i add the alias :)

**Comment by beenanner** [comment]
Yep you got it! Glad everything is working for you. Happy testing! :-)
