### ISSUE TITLE
How see datas in Graphite ?

### ISSUE THREAD

**Issue by gpapis** [sitespeedio/sitespeed.io#2082]
Hi !
I don't understand how can I see my test datas in graphite interface (and clean or purge old datas).
For the moment, I'm using test with this procedure : https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-almost-5-minutes
When this step will be done I'm going to begin steps to production use (today not so clear for me...)
Can you help me ?
Best

**Comment by softwareklinic** [comment]
If you are using the graphite.host, port, and namespaces correctly in your cron / sitespeed.io run... your data would be getting posted to graphite correctly.

Your best bet would be to view this data in Grafana instead of graphite web UI itself... which is kind of tedious ....

If you need further help let me know...  Below is how the data in graphite appears -- TREE View

![image](https://user-images.githubusercontent.com/7537289/41662089-ed243fc2-7465-11e8-9603-4c9ab5c0b873.png)

Same data is navigable in Grafana with much ease - as below 

![image](https://user-images.githubusercontent.com/7537289/41662188-287fec24-7466-11e8-99b7-06d73300c18c.png)

Cleaning out OLD data is simple --- you can SSH into the BOX where graphite data folder is located... navigate to a particular folder -- just like what you see in TREE and delete the folder...

**Comment by gpapis** [comment]
Thanks for your answer, it's very clear,
the only datas I see is Carbon, stats, stats_counts and statsd, I don't see sitespeedio... However in Grafana it's good...
And now, I've new problem, my hard drive (500GB) is almost full (it remains 94GB) because for my tests I use cron service to automatise mesures and when I'm doing docker build -t sitespeedio_dashboards . (I stopped it since this morning). I use several commands to clear memory used by docker but it's not sufficient... :-(

**Comment by soulgalore** [comment]
Hi @gpapis checkout point 4 and 5 [here](https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#setup-important), that's how you configure Graphite of what to store and for how long. And read how to configure Graphite https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#configure-graphite

Hope that helps!
Best
Peter

**Comment by softwareklinic** [comment]
Maybe you can remove any dangling images

$ docker rmi $(docker images --quiet --filter "dangling=true")

OR 

$ docker images -qf dangling=true | xargs docker rmi

OR

$ docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi -f

to free up the space,..

**Comment by soulgalore** [comment]
This is answered lets close.
