### ISSUE TITLE
Slack messages not being received when resultBaseURL is set

### ISSUE THREAD

**Issue by createandcode** [sitespeedio/sitespeed.io#2147]
Hey guys,

strange issue for you!

When I run this:

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.3.6 https://sitespeed.io -n 1 http://sitespeed.commercegurus.com/speedreports --slack.hookUrl https://snip --slack.type summary`

I get a Slack message (webook address snipped above)

When I add a `resultBaseURL` as follows:

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.3.6 https://sitespeed.io -n 1 --resultBaseURL http://sitespeed.commercegurus.com/speedreports --slack.hookUrl https://snip --slack.type summary`

I get no Slack message. The url is valid as the report is visible at the the correct url.

Any ideas?

Running via docker on Ubuntu 16.04

Thanks

**Comment by soulgalore** [comment]
Hi @createandcode thanks for reporting the issue! 

Yep I checked the code and right now the Slack message isn't sent if you set a result URL and don't use s3/gc/ftp etc see:
https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/slack/index.js#L139-L162

Let me have a look and fix that.

Best
Peter

**Comment by createandcode** [comment]
ah ok thanks @soulgalore ! I suspected it was a bug but wasn't sure. If I configure s3 will it work in 7.3.6?

**Comment by soulgalore** [comment]
Yes that will work.

**Comment by erickwilder** [comment]
This is a follow-up of my previous [message on Slack](https://sitespeedio.slack.com/archives/C03DHTPSA/p1587145043128700) in order to document it here in the original issue. 

I have it working but without any flag (as suggested by @soulgalore there) and before I can go further I would like to cover some scenarios and your input is appreciated.

Given that Slack messages are sent on a handful of `xxx.finished` messages, what do you think about extending this so that _any_ plugin author can hook into Slack notifications? This way, if you have a custom plugin and want to wait until it finishes its job _before_ anything is posted on Slack, you can:

Let's say I have want to upload my assets to a Netlify account and I wrote a plugin for that. In this plugin I collect all required assets (just as s3/gcs) and send `netlify.finished` message.

Then I could call sitespeed with the following:

```
sitespeed.io --slack.postAfterPlugin=netlify
```

This would override the default behaviour of sending messages on `html.finished` (or  any built-in provider) and only "listen"  for `netlify.finished` message.

**Comment by soulgalore** [comment]
Sounds like a great idea @erickwilder ! If you could split it in multiple PRs thats much appreciated.
