### ISSUE TITLE
Measuring specific request triggered by selenium 

### ISSUE THREAD

**Issue by handre** [sitespeedio/sitespeed.io#2158]
Firstly, I really got impressed by sitespeed capabilities when I first saw it, so thanks for such an amazing tool!

I would like to know if its possible to start measuring a specific javascript request triggered by selenium after the page is loaded.
I.e. 
1. Load a "generic result" page
2. Change results filter that triggers XHR
3. Start sitepeed measuring

Thanks in advance!

**Comment by soulgalore** [comment]
Hi @handre thanks for the kind words!

It depends. You can use the --preScript to run your own Selenium scripts (https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/) that will access the generic result page and do stuff there. Today the "Change results filter that triggers XHR" needs to be done by access the URL with specific parameters. At the moment you cannot choose how to navigate to the page that will be measured. We kind of have prepared for it, but haven't implemented it (because it isn't super easy).

Best
Peter

**Comment by soulgalore** [comment]
With the new scripting in 8.0 this is doable as long as you web app refresh the URL in the browser see https://www.sitespeed.io/documentation/sitespeed.io/scripting/
