### ISSUE TITLE
Google Tag Manager and Google Analytics

### ISSUE THREAD

**Issue by quartex** [sitespeedio/sitespeed.io#2165]
Hi,
we are using the SiteSpeed 7.3.6 and the coach reports very often on real site scan 

"The page is using Google Tag Manager, this is a performance risk since non-tech users can add JavaScript to your page." (with weight: 5 in the code)
or
"The page is using Google Analytics meaning you share your users private information with Google" (with weight: 8 in the code)

with 0/100 score

All the exception are technically correct but Google Tag Manager and / or  Google Analtics penalizes the total score very hard and unfortunately are a standard de facto for a real normal site (ecommerce and or other business).
Typical users would like to reach 100 on score ;-) and ask us if is possible to remove only for score this 2 hints but visualize it because are not fixable in a real world.

Any ideas for this ? Is it a problem only for us ?

Thank you very much

**Comment by soulgalore** [comment]
Hey @quartex 
Google Tag Manager hurt the performance score, because of the risk that people will actually use it to add dependencies. The manager is a performance risk. So the Tag Manager itself doesn't hurt the performance (at least I don't think so but I haven't looked closely at it). 

Where I worked before the Tag Manager was the marketing departments way of side step developers to push whatever code they want it production without going through the steps that the operations or developers has setup. The Tag Manager also have privacy issues (as GA) but we don't penalize for that at the moment.

Google Analytics: The problem is that the company that uses GA share information of what the user do to Google, so the user can be tracked even though she doesn't want to. That's why the GA gives a lower best practice score. Companies uses GA because it is "free" for the company, and the user of the web site pay instead with sharing the information of what she do. There are other tracking solutions where you as a user get information of what the user do on your site but you still keep the privacy of the user.

That's why it's cool to use a tool that aren't made by Google: We can point if these problems. Some of the Google tools for example doesn't categorize Google products as third parties.

>are a standard de facto for a real normal site (ecommerce and or other business). 

Yeah, help us fix the web and change that!  I don't agree that they aren't fixable problems. The easiest way to get 100 score that the customer want is to be nice to their users and skip GA and GTM :)

Best
Peter

**Comment by quartex** [comment]
ok thank you for your explain
