### ISSUE TITLE
Multiple issues when trying to measure performance of landing page after login

### ISSUE THREAD

**Issue by skhilko** [sitespeedio/sitespeed.io#2186]
I can only reliably use sitespeed.io v7.2.1 with my setup. I'm not sure whether that's me doing something wrong or sitespeed.io is not handling my use case correctly. I appreciate any help!

I'm trying to measure the performance of the landing page the user is redirected to after submitting their credentials.

## Scenario
1. Navigate to https://domain/page/login/goHome (`preScript`)
2. Submit login and password. (`preScript`)
3. `preScript` returns `return driver.wait(until.urlContains('page/login/app'));` to wait until the url changes to "logged in" state (aka "landing page").
4. Login page redirects to landing page https://domain.com/page/login/app after validating the credentials.
5. Landing page updates url with a hash while it's loading. https://domain/page/login/app#/dashboard
6. Measure performance of the same page https://domain/page/login/app

### Command
```
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.6.3 --preScript /sitespeed.io/login.js https://domain/page/login/app
```

### preScript
```
module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
      return driver.get(https://domain/page/login/goHome)
        .then(() => {
          const webdriver = context.webdriver;
          const until = webdriver.until;
          const By = webdriver.By;

          driver.wait(until.elementLocated(By.id('loginContainer')));

          driver.wait(until.elementIsVisible(driver.findElement(By.id('form-email'))));
          driver.findElement(By.css('#form-email [name="username"]')).sendKeys(USER_NAME);
          driver.findElement(By.css('#form-email [type="submit"]')).click();

          driver.wait(until.elementIsVisible(driver.findElement(By.id('form-password'))));
          driver.findElement(By.css('#form-password [name="passwd"]')).sendKeys(USER_PASSWORD);

          driver.findElement(By.css('#form-password [type="submit"]')).click();
          return driver.wait(until.urlContains('page/login/app'));
        });
    })
  }
};
```

### sitespeed.io v7.5.2
✅The visual metrics are correct.
✅The video ends right after the last visual change (around 3 seconds).
❌The script runs way longer than the last visual change (around 1.5 minutes)
❌The waterfall is extended 
<img width="1166" alt="screen shot 2018-10-19 at 11 15 12 am" src="https://user-images.githubusercontent.com/970479/47236226-4f0fff80-d390-11e8-9dfc-e99b0fb804ae.png">

### sitespeed.io v7.6.3
❌The visual metrics are incorrect. 
<img width="771" alt="screen shot 2018-10-19 at 11 11 54 am" src="https://user-images.githubusercontent.com/970479/47236068-d9a42f00-d38f-11e8-803e-e097f2c9c6da.png">
✅The video ends right after the last visual change (around 3 seconds).
❌The script runs way longer than the last visual change (around 1.5 minutes)
❌The waterfall is extended
<img width="1243" alt="screen shot 2018-10-19 at 11 14 33 am" src="https://user-images.githubusercontent.com/970479/47236244-664eed00-d390-11e8-9454-4afd791d9bf8.png">

###  sitespeed.io v7.6.3 - Including the hash to the target page
```
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.6.3 --preScript /sitespeed.io/login.js https://domain/page/login/app#/dashboard
```

sitespeed.io seems to start collecting the metrics after `#/dashboard` is appended.
<img width="1318" alt="screen shot 2018-10-19 at 11 47 36 am" src="https://user-images.githubusercontent.com/970479/47237787-f55e0400-d394-11e8-9d68-fe901e971df7.png">

**Comment by soulgalore** [comment]
Hi @skhilko 
thanks for the report!

First I wonder about the wrong visual metrics: In [7.6.0](https://github.com/sitespeedio/sitespeed.io/blob/master/CHANGELOG.md#760---2018-10-15) I did a fix that removed the "white" screen between preScript and the actual tested page. Before it worked like this: 
1. Run preScript
2. We removed the current HTML and made the background white. 
3. The screen turn orange (we used that to be able to catch when the navigation start)
4. We removed the orange (so that the screen is fully blank/white).
5. We navigate to the URL 
6. Visual Metrics looks for the first white screen after the orange screen.

The new flow in 7.6.0:
1. Run preScript
2. Add a layer of orange on top of everything (we used that to be able to catch when the navigation start)
3. We removed the orange layer (the background are now the same as after the first navigation)
4. We navigate to the URL and Visual Metrics looks for the first changed screen after the orange was removed (comparing the first screen with the following).

The way we did it in pre-7.6 was wrong since we removed the current HTML, meaning if your page updated elements on the current page in step 2, they where removed so it didn't work.

If you look at the video from 7.5.2 and compare it with the video from 7.6.3, what do you see? The video from 7.5.2 should start with a white screen, video from 7.6.3 should start with the page you used in the preScript. But when do the firstVisualChange happen? There's an extra parameter that you can use just to see the keep the full video (with preScript etc)  `--browsertime.videoParams.keepOriginalVideo` to see what's happening.

About the long time before it ends: By default we wait on https://github.com/sitespeedio/browsertime/blob/master/lib/core/defaultPageCompleteCheck.js to happen but we after that we also wait for the document uri to change, see https://github.com/sitespeedio/browsertime/blob/master/lib/core/seleniumRunner.js#L157-L162.

I think that last check for URI could be one of the problems (we need to do that smarter or configurable). If you have a URL I can test with I can try to fix it or if you can do a PR with a solution.

Do you run your own pageCompleteCheck?

Best
Peter

**Comment by skhilko** [comment]
> If you look at the video from 7.5.2 and compare it with the video from 7.6.3, what do you see? The video from 7.5.2 should start with a white screen, video from 7.6.3 should start with the page you used in the preScript. But when do the firstVisualChange happen? There's an extra parameter that you can use just to see the keep the full video (with preScript etc) --browsertime.videoParams.keepOriginalVideo to see what's happening.

- The video from 7.5.2 starts with the white screen.
- The video from 7.6.3 starts with the page I'm doing the performance test, not the `preScript` one. After the landing page shows for a split second, it follows by a page reload. At that moment all visual metrics fire up at once.

If I understand correctly what happens, `preScript` detects that we're logged in via `return driver.wait(until.urlContains('page/login/app'))`. After that, selenium navigates to the same page (the reload I mentioned) to do the perf testing.

> I think that last check for URI could be one of the problems (we need to do that smarter or configurable). If you have a URL I can test with I can try to fix it or if you can do a PR with a solution.

Unfortunately, I cannot share the login credentials for the webapp I'm testing. I'll see if I'll be able to fix the issue.
> Do you run your own pageCompleteCheck?

I don't have that.

**Comment by skhilko** [comment]
I'll be happy to help! Thanks!

**Comment by soulgalore** [comment]
You should try out scripting in 8: https://www.sitespeed.io/documentation/sitespeed.io/scripting/ that should cover most if the use cases.
