### ISSUE TITLE
Error : "could not find url"  when tried with option --browsertime.pageCompleteCheck

### ISSUE THREAD

**Issue by Dineshm90** [sitespeedio/sitespeed.io#2194]
Steps:
Pulled docker image sitespeed.io:7.7.2 
Tired to run following command 
no error is observed when tired with out the option --browsertime.pageCompleteCheck

>docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.7.2 https://www.sitespeed.io --browsertime.pageCompleteCheck 'return (function() {try { return (Date.now() - window.performance.timing.loadEventEnd) > 20000;} catch(e) {} return true;})()'
- sitespeed.io:7.7.2 

Attached screen shot for reference
![url not found](https://user-images.githubusercontent.com/16046720/47507833-974b8800-d890-11e8-8ec4-9ef853db0a21.png)

**Comment by soulgalore** [comment]
Hi @Dineshm90 
so if I understand correctly:  the first red one, it looks like Windows is handling the CLI parameters differently (sitespeed.io tries to find a file instead of using the JS in the parameter. I just tested on my Mac and there it works. Have you tried using double instead of single quotes?

Best
Peter

**Comment by Dineshm90** [comment]
@soulgalore 

Thank you. I tired with double quotes and it worked fine.
