### ISSUE TITLE
lighthouse plugin results

### ISSUE THREAD

**Issue by idristarwala** [sitespeedio/sitespeed.io#2197]
Hi Team,
I am evaluating the new lighthouse plugin which is added to the site-speed docker image, I am using the following command :-
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.5.0-plus1 https://www.sitespeed.io/ --plugins.add analysisstorer
Could you help me figure out where the lighthouse results go ?

**Comment by soulgalore** [comment]
Hi @idristarwala you will find in the data folder of the URL with the name **lighthouse.pageSummary.json** but there's one thing missing in the documentation. That Docker container (+1) has a default env setting so that both Lighthouse and GPSI runs automatically, but when you add another plugin, the default is removed. I'll update the docs later. You can just add the Lighthouse plugin and it will work:

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.7.2-plus1 https://www.sitespeed.io/ --plugins.add analysisstorer --plugins.add /lighthouse`

Best
Peter
