### ISSUE TITLE
How to filter dirty data

### ISSUE THREAD

**Issue by chrischjh** [sitespeedio/sitespeed.io#2227]
During my monitoring, the application under test got down for a while and some dirty sampling data were captured, is there a way to exlude or filter them? I'm new to Grafana or Graphite, but seems there are not efficient way to do that from searching around? I'm using WebPagetest to collect metrics.

**Comment by soulgalore** [comment]
HI @chrischjh 
no, there's not an easy way. Either remove those metrics from Graphite but since the metrics is file based you need to go through everyone and remove the ones between certain time span. You could do it in  bash-script but it would be work. Or you need to change all the queries in Grafana to exclude metrics under a threshold but that means changing all dashboards.

I would create an [annotation](http://docs.grafana.org/reference/annotations/) in Grafana where you explain what happened. 

Best
Peter

**Comment by chrischjh** [comment]
Hi @soulgalore , thanks for the tips, I've added filters in the charts to exclude the metrics under a threshhold, also added annotations. Is there really a way to remove the metrics between certain time span? I went through Graphite documents, but no finding how to do that, do you have an example? much appreciated!

**Comment by chrischjh** [comment]
Thanks anyway! I figure that in my context we may have to do it from time to time in future, thus possibly try to port the data source to MySQL :)
