### ISSUE TITLE
URL appear twice in pages

### ISSUE THREAD

**Issue by ckhampus** [sitespeedio/sitespeed.io#2260]
Hi!

I think this might be a similar issue as #265.

When running:

```
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.0.2-plus1 https://www.dn.se -b chrome --mobile
```

I get the following:
![skarmavbild 2019-01-22 kl 15 41 19](https://user-images.githubusercontent.com/173021/51543103-171bcb00-1e5d-11e9-9b25-83b224e001f6.png)

The difference is the `/` at the end of the url.

**Comment by soulgalore** [comment]
Hi @ckhampus thanks for reporting. Yeah, it work like this: Browsertime uses the URL from the browser, so that for example when dn.se gets redirected to dn.se/ the last URL is used, and it seems like the plugins don't. For now I think you get round the problem by testing https://www.dn.se/ and then I'll check for a fix later today (or tomorrow).

Best
Peter

**Comment by ckhampus** [comment]
Ok, that might explain why don't see the Lighthouse and GPSI tabs in the generated reports. Tested again with the slash at the end and now I can see the again.

Thanks!

**Comment by soulgalore** [comment]
I've just pushed 8.0.3 that should fix this.

**Comment by ckhampus** [comment]
Thanks for fixing this! 👍
