### ISSUE TITLE
login.js does not exist, is the path to the file correct?

### ISSUE THREAD

**Issue by karthikamirapu** [sitespeedio/sitespeed.io#2304]
So when I am running scripts through docker compose, I am getting this error "login.js does not exist, is the path to the file correct? I am pretty sure I am running this command from the correct directory, so not able to figure out why the error is displayed.

**Comment by donwalling** [comment]
@karthikamirapu This error means the login.js file isn't available in the expected location inside the docker image. If you can't find the issue, please post enough info for someone else to reproduce the problem

**Comment by soulgalore** [comment]
@karthikamirapu yeah can you show me? You need to make sure that you map the file from outside of the container to the container, so that it can be used. I think something like this would work (though I'm usually using docker run instead of the full compose file):

`docker-compose run -v $(pwd):/sitespeed.io --rm sitespeed.io /sitespeed.io/login.js --multi`

Best
Peter

**Comment by karthikamirapu** [comment]
> @karthikamirapu yeah can you show me? You need to make sure that you map the file from outside of the container to the container, so that it can be used. I think something like this would work (though I'm usually using docker run instead of the full compose file):
> 
> `docker-compose run -v $(pwd):/sitespeed.io --rm sitespeed.io /sitespeed.io/login.js --multi`
> 
> Best
> Peter

Peter - that worked..Thanks.
