### ISSUE TITLE
Integrating with existing performance testing scripts?

### ISSUE THREAD

**Issue by LionOnTheChase** [sitespeedio/sitespeed.io#2327]
Hi,

Sitespeed.io is a great tool. I have used and benefitted from it while profiling an slow web application. 

I want to take it's usage to the next level by adopting it in my org's pipeline. Use it to detect performance degradations and prevent them. However, for accomplishing this, I see that I need to write selenium scripts from scratch and cannot re-use what I already have. 

What does it take to integrate sitespeed.io with java based selenium scripts already written in my project. I'd rather enhance sitespeed.io than port all my selenium scripts to nodejs, if it is easier. 

Similarly I have jmeter scripts for performance testing a user journey. Do you see any possibility of using it  with sitespeed.io to measure client side performance of the user journey?

It doesn't have to be a fool proof integration to begin with. But is there any possibility?

**Comment by soulgalore** [comment]
Hi @LionOnTheChase great that things has worked good for you :)

No I don't see a way for that to work. There's three ways of doing the scripting: Either our commands (that's wrapped Selenium/raw JavaScript), pure Selenium (with our commands to actually do the measurement) or pure JavaScript (executed through our JavaScript command) together with our measurement command. Docs here: https://www.sitespeed.io/documentation/sitespeed.io/scripting/

Whatever way that you use, to get actual metrics you to use https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measurestarturl or https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measurestart and https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measurestop because these commands are the ones that runs the goodies we use to collect data: Start starts the video, clear logs etc preparing for a measurement and stop stops the video, run JavaScript to collect metrics and use browser logs to fetch data.

I can understand that it is much work to rewrite but I would start with one first, if you have one most important use case, so you can verify that it works as it should. What I like how we do the scripting is that if you do multiple (you have a user journey with that goes to 5 pages) and run it multiple times, you will get median/min/max metrics etc for each and every page.

Best
Peter

**Comment by LionOnTheChase** [comment]
Thanks Peter for your detailed explanation. Yes, I will start with one important user journey to begin with.
