### ISSUE TITLE
Automatically add annotation tag with current version of Sitespeed

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2340]
In the same way that tags are automatically created for script steps, site, browser, etc., it would be very useful to automatically add the Sitespeed version number as a tag as well.

**Comment by soulgalore** [comment]
Hi @leathej1 can you explain more how you would use that? I'm just wanna avoid storing extra data :)

Best
Peter

**Comment by leathej1** [comment]
It would be a way to trace a deviation in performance back to a specific build.  This is similar to marking deployments in an APM like New Relic https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-deployments

**Comment by soulgalore** [comment]
The way I do it at work and for sitespeed.io I go into Grafana and create a annotation manually where I write in the description about the update from which version and to. That way I have one annotation that shows when it happens, instead of storing the version per every tag. You could also automate it by using curl etc. Would that do for you?

**Comment by soulgalore** [comment]
This is included now in the annotation title:
![versions](https://user-images.githubusercontent.com/540757/69466226-bbbfaf80-0d83-11ea-9943-00d68c56ca5b.png)
