### ISSUE TITLE
VisualMetrics degradation after update

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#2375]
Hello,

I've been using sitespeed.io 7.7.2 for a long time just to have valid metrics which I can compare from release to release excluding measuring tool influence.
Recently I've updated to 8.7.5 and now see high VisualMetrics (85,95,99) degradation up to 3 times at 3g connectivity network profile (cable looks the same).
I tried different older images and found out that it started from 8.0.0 Sitespeed.io release.

Actually tested web page is SPA and I connect it with SPA testing support starting from Browsertime 4.0.0. Though, there is degradation whether I use --spa flag or not. + I think this flag shouldn't impact Visual Metrics based on video analysis.

Please help to understand this issue.

**Comment by soulgalore** [comment]
Hi @Icecold777 there has been changes in Visual Metric on how to know when a there are no difference in pixels see https://github.com/sitespeedio/browsertime/blob/master/CHANGELOG.md#447---2019-02-21 but that should mean that LastVisualChange happens earlier in newer release. When each screenshot are compared (to find if a screenshot looks the same as other = no change) Visual Metrics use a fuzz factor to try to ignore smal changes. That factor has been increased. I need to look into the changelog if there could be more things.

There could also be Browser version changes (if you use the pre-made Docker containers) that also could influence the metrics. I've seen that with Wikipedia and Chrome (and also Firefox) visual change changes between releases (seen both increase and decrease), so that can matter too. See for example https://bugs.chromium.org/p/chromium/issues/detail?id=887205
That's why I always try to keep updated when a new browser versions comes out (even though it means more work).

Best
Peter

**Comment by soulgalore** [comment]
I'm closing now since I don't think there's anything we can do about it.
