### ISSUE TITLE
[unable to attach budget] ENOENT: no such file or directory, open 'file.json'

### ISSUE THREAD

**Issue by prashanth-sams** [sitespeedio/sitespeed.io#2482]
### steps to reproduce
- I used the `docker-compose.yml` file to spin up `grafana`, `graphite`, and `sitespeed.io` containers
- Created `budget.json` file
```
{
 "budget": {
    "timings": {
      "SpeedIndex":1000
    }
 }
}
```

![image](https://user-images.githubusercontent.com/2948696/58478170-71f46480-8166-11e9-8386-31276ee32c7f.png)

### run command
```
docker-compose run sitespeed.io https://www.somewebsite.com --graphite.host=graphite --budget.configPath budget.json
```

### output error in terminal
```
ENOENT: no such file or directory, open 'budget.json'
```
**Note:** Am not sure if this is the way to attach budget file

it works great when I manually set the budget like this (but I need to feed the data as json file)
```
docker-compose run sitespeed.io https://www.somewebsite.com --graphite.host=graphite --budget.config '{ "budget": { "timings": { "SpeedIndex":1000 } } }'
```

**Comment by soulgalore** [comment]
Hi @prashanth-sams you need to map the volume so it exists inside of the Docker container. Here are one example when you run docker run: https://www.sitespeed.io/documentation/sitespeed.io/docker/#more-about-volumes

It's better to Dcoker run (I'll update the docs) since it's simpler and will work out of the box when you run on different machines (sorry for that example in the docs).

Best
Peter

**Comment by prashanth-sams** [comment]
thank you @soulgalore I get it; let me try that. I will close this issue tomorrow.

**Comment by prashanth-sams** [comment]
I attached the volume through `docker-compose.yml`; and it works like charm

```
volumes:
            - ./sitespeed-result/:/sitespeed.io/sitespeed-result
            - ./:/sitespeed.io
```
