### ISSUE TITLE
setting cookie via request header

### ISSUE THREAD

**Issue by tufandevrim** [sitespeedio/sitespeed.io#2520]
I was able to set `cookie` request header via `--browsertime.requestheader` in ssio 5.x but not anymore in 9.x. 

For example, following command line option was working in 5.x 
`--browsertime.requestheader "cookie: 'foo=bar'"` but does not work in 9.x 

Interestingly following command works fine though 
`--browsertime.requestheader "foo: 'foo=bar'`

It appears `cookie` key in request headers is being stripped out. Is there any other way to set request header cookie?

**Comment by soulgalore** [comment]
Hi @tufandevrim I don't remember that we changed anything, but let me have a look tonight to reproduce and understand whats wrong.

Using Chrome you can use https://chromedevtools.github.io/devtools-protocol/ and scripting but that is some extra work.

I'll look into it and in the long run we should move out the request header functionality for Chrome to use CDP instead of the extension that we use today.

Best
Peter

**Comment by soulgalore** [comment]
This was strange: It works in Firefox but not for Chrome. I made a PR to use CDP instead (meaning it will also work for Android Chrome users) so will push that in the next release (today or tomorrow, I wanna try to fix another bug before the release).

**Comment by soulgalore** [comment]
Pushed a new Browsertime with the new version, pushing sitespeed.io tonight.

**Comment by soulgalore** [comment]
I release 9.4.0 earlier today with a fix, please let me know that it works for you @tufandevrim !

**Comment by tufandevrim** [comment]
yeah I see header cookie is being set in 9.4.0. Thanks for fixing it @soulgalore

**Comment by tufandevrim** [comment]
My issue is being resolved with 9.4.0. Thanks a lot again
