### ISSUE TITLE
No data to collect with 9.4.0

### ISSUE THREAD

**Issue by Rahe** [sitespeedio/sitespeed.io#2533]
Hello,

I have errors on the new version of sitespeed, the 9.0.0 is working fine.

There is the error : 
> [2019-07-04 10:06:46] INFO: Versions OS: linux 4.9.125-linuxkit nodejs: v10.13.0 sitespeed.io: 9.4.0 browsertime: 5.3.0 coach: 3.6.0
> [2019-07-04 10:06:47] INFO: Running tests using Chrome - 10 iteration(s)
> [2019-07-04 10:06:51] INFO: Testing url https://portail.free.fr iteration 1
> [2019-07-04 10:06:51] ERROR: No page that could be associated with the error:header.split is not a function
> [2019-07-04 10:06:51] ERROR: TypeError: header.split is not a function
>     at ChromeDelegate.onStartIteration (/usr/src/app/node_modules/browsertime/lib/chrome/webdriver/chromeDelegate.js:127:30)
> [2019-07-04 10:06:51] ERROR: No data to collect

This is applying on every run.

- Exact how you run (the exact parameters)
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:9.4.0 --thirdParty.cpu --cpu -run 10  https://portail.free.fr

- Which version you are using
9.4.0
- OS (if you use Docker, report the base OS)
MacOS and checked on CentOS

Nicolas,

**Comment by soulgalore** [comment]
Hi @Rahe thanks for reporting the issue!

You can fix it yourself by changing `-run 10` to `--iterations 10` (or `-n 10`). We don't validate the cli parameters (so that we can pass on whatever we got to plugins etc) and `-run` doesn't exist (but `-r `do for setting up request headers). In 9.4 we added a change for setting the request headers via CDP and then it started to fail. So I guess in earlier versions it didn't throw an error but it didn't work either.

I can add a check so it doesn't give errors but for it to work you need switch parameters.

Best
Peter

**Comment by soulgalore** [comment]
Hi @Rahe just release 9.5.0, let me know if it works for you now.

Best
Peter

**Comment by Rahe** [comment]
Hello,

With -n 10 and the new version this is working great !
Thank you :)

Nicolas
