### ISSUE TITLE
Mark response codes as tags in influxDB.

### ISSUE THREAD

**Issue by Naverin89** [sitespeedio/sitespeed.io#2648]
Hi guys!
I really love to use **sitespeed**! It's really helpful tool. But today I bumped into a problem. 
Site that I tested went down  with _(503)_ and my performance score _(I use lighthouse plugin)_ hit 100 _(was 40-50)_. I've tried to separate results with code 200 and other. 
I wasn't able to make a query with two measurements _(score and 200)_. 
This would be very nice if you help me with this. 
Thanks.

**Comment by soulgalore** [comment]
Hi @Naverin89 I think this is an upstream issue in Lighthouse, so that they don't report 100 on errors? Do you also run Browsertime tests? I wonder if we have missed sending some data to InfluxDB, to Graphite we send errors (failures) https://dashboard.sitespeed.io/d/YrbijEumk/alerts?orgId=1 (scroll down to Testing Errors) or ... could it be that we don't check the HTTP code? Let me look into that.

Best
Peter

**Comment by Naverin89** [comment]
Thanks for your fast response. 
Its more like page return (**503 Service Unavailable**) error. And it has only 1 request and response as blank page with plain html, so all of the metrics are the best (100, green, etc). 
But it appears in influx as "503" measure. Actually all of the response codes becomes separate measurements. 
I think more convenient would be, if they become just tags (also it'll save some disk space). 
Example ( **_SELECT "value" FROM "score" WHERE "audit"='performance' AND "responceCode"='200'_** )
![Codes](https://user-images.githubusercontent.com/36934860/65310633-6acee780-db97-11e9-923e-07d194a04cdd.png)

**Comment by soulgalore** [comment]
Aha then I see. Thanks for the explanation. The numbers you are seeing are numbers of response codes right? The page had X 404 and so on? At the moment we don't handle a response code of a main page in a specific way.

**Comment by Naverin89** [comment]
Thanks!
