### ISSUE TITLE
Make it possible to configure which slack metrics to use

### ISSUE THREAD

**Issue by sydneybmunizaga** [sitespeedio/sitespeed.io#2669]
I am trying to add an array to the `--slack.limitMetric` command and I keep getting an error that the second index `does not exist`. 

```docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io --network=host sitespeedio/sitespeed.io:latest --preScript ./sitespeedio/templates/login.js ./sitespeedio/templates/urls.txt --useHash --slack.hookUrl https://hooks.slack.com/services/XXXX -n 1 --slack.limitWarning 70 --slack.limitError 60 --slack.limitMetric ['speedIndex', 'coachScore']```

Ideally, I do not want ALL of the info on the slack channel. My hope and dream is that I just get the Speed Index and the Coach Score, but for now, I would like to understand how to write the array for the `--slack.limitMetric` command so that I do not get the error.

Do I write `--slack.limitMetric speedIndex coachScore` with no quotes and no brackets? So far every combination of quotes, brackets, and commas that I can think of hasn't worked. It looks like I can only use 1 option and that the array option is broken.

**Comment by soulgalore** [comment]
Hi @sydneybarlow I think the docs isn't clear, let me update them tomorrow. 

At the moment you can only have one metric that is the one magic one that chooses if it should limit has been reached or not. I've spent so much time on Slack plugin, and if you have ideas how it could work better, that would great. 

For alerting I personally only use Grafana (sending metrics ot Graphite). The reason is that those alerts are so much more flexible: https://www.sitespeed.io/documentation/sitespeed.io/alerts/ 

Best
Peter

**Comment by sydneybarlow** [comment]
Okay, great. That is good to know. Only using one _seemed_ to be what was happening but I wanted to make sure. Thank you for the quick response. I think Grafana might be a better option as well. Thank you for the recommendation!

**Comment by sydneybarlow** [comment]
As a suggestion on how Slack notifications could work better: It would be good to create an option to filter only the data that you care about instead of sending "summary", "all" or "errors". Such as only seeing either one option or a mixture of 2 to several options. Being able to pick and chose which scores you care the most about.

I also don't understand how it only seems to show the bottom 11 scores. For instance, in my 
"summary" and "all" options I only see the; **First paint, Speed Index, First Visual Change, Visual Complete 85%, Last Visual Change, Fully Loaded, domContentLoadedTime, RUM Speed Index, Coach score, Page transfer size, and Requests**. 

I would like to see the **Overall score, Performance score, Accessibility score, and Best Practice score** in my summary or all (or any other score not mentioned in the previous list above).

**Comment by soulgalore** [comment]
Yeah I see your point. At the moment isn't super clean to implement (we are having the same kind of problem for what metrics to show in the summary HTML page for example, wanna make that configurable too).  

One way to do it is to reuse (and move out) https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/budget/friendlynames.js. Yeah that would probably. Sorry a little detailed, but writing it down so I remember it in the future :)

**Comment by sydneybarlow** [comment]
Thank you for the quick response!

**Comment by soulgalore** [comment]
Since we haven't done anything with this for a +1 year I don't think it will be implemented the coming year(s) so closing.
