### ISSUE TITLE
make report folder path configurable

### ISSUE THREAD

**Issue by matti** [sitespeedio/sitespeed.io#2757]
In grafana I can create panel links and use variables like `$path`, but since the results are stored with path like `/www.domain.com/` I can not use `$domain` (which doesn't exist in the link autocomplete options, or in variables, but it is visible in the default dashboard (strange?)) because the domain will be `www_domain_com`

**Comment by soulgalore** [comment]
I think they way to fix that is to make it configurable. That magic should probably happen in https://github.com/sitespeedio/sitespeed.io/blob/master/lib/core/resultsStorage/pathToFolder.js. (and the same thing in Browsertime), so that you could configure paths on disk to be named as `www_domain_com`

**Comment by soulgalore** [comment]
This has been implemented as default for some time, so that the folder on disk is named with underscore. Now they have the same name in Graphite and on disk.
