### ISSUE TITLE
disable GPSI plugin

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#2849]
Hello,
Please help me with following issue.
I'm trying to disable GPSI plugin from plus1 container version. I use --plugins.remove but looks like without any luck. Please look through example below. Other plugins are being disabled successfully.
Ps I tried 9.8.1-plus1 and the latest 11.9.3-plus1

sudo docker run --network cable --shm-size=1g --rm -v /home/centos/sitespeed:/sitespeed.io sitespeedio/sitespeed.io:9.8.1-plus1 https://sitespeed.io -c cable -n 1 **--plugins.remove /gpsi** --plugins.list
Google Chrome 76.0.3809.87
Mozilla Firefox 68.0
[2020-01-20 15:52:47] INFO: Versions OS: linux 3.10.0-862.9.1.el7.x86_64 nodejs: v10.13.0 sitespeed.io: 9.8.1 browsertime: 5.7.3 coach: 3.6.0
[2020-01-20 15:52:47] INFO: The following plugins are enabled: assets, browsertime, budget, coach, domains, harstorer, html, metrics, pagexray, text, thirdparty, tracestorer, /lighthouse, **/gpsi**
[2020-01-20 15:52:48] INFO: Will run Lighthouse tests after Browsertime has finished
[2020-01-20 15:52:48] INFO: **Sending url https://sitespeed.io to test on Page Speed Insights**

**Comment by soulgalore** [comment]
Hi @Icecold777 the Docker container automatically add those plugins to the list, so you cannot override that. It the same thing as we had with video in https://github.com/sitespeedio/sitespeed.io/issues/2692. This hasn't high prio for me but I'll think about a pattern to solve it.

**Comment by Yivan** [comment]
Hello @soulgalore 
First thanks for this wonderfull tool I discovered recently. I love it : )

I would like to give my experience on this issue.
We use plus1 container version (because we really like to have lighthouse reports on the same report), but GPSI send an error if domain is internal.
As we use sitespeed io for our continuous integration with budget rules, it breaks totally the workflow (internal domain on a local test docker infra).
Even if all budget rules are OK, the process finish in error. :(
And we cannot differentiate budget rules error or GPSI dns error, as both return at the end the code 1.

I hope you could priorise this because this is a stop breaker for CI with budget rules (including lighthouse budget rules, so plus1 container).
Possibility to disable GPSI would be the best (will improve time to render the test), or at least specific code error.

Thanks for reading me!
Best regards.

**Comment by soulgalore** [comment]
Hi @Yivan yes I understand. I got the other way around, I need to run the GPSI plugin but wants to avoid the Lighthouse one. So I think I have a solution, I'll have a go tomorrow night and try it out.

Best

**Comment by soulgalore** [comment]
FYI: https://github.com/sitespeedio/sitespeed.io/pull/2926 

I got one more bug I want to fix, hopefully I can do that tonight and then rollout the fix late tonight or tomorrow.

**Comment by soulgalore** [comment]
@Icecold777 and @Yivan I just pushed 12.2.1 that should fix the problem. To remove GPSI:
`--plugins.remove /gpsi `

Remove Lighthouse:
`--plugins.remove /lighthouse `

I'm gonna update the documentation tonight.

**Comment by Yivan** [comment]
@soulgalore Thanks a lot for this lucky luke fix ; ) Very fast!
I will try it as soon the docker image is updated. Should it take long time ?

**Comment by soulgalore** [comment]
Great! Thanks for getting back and verify!
