### ISSUE TITLE
Make a climate friendly plugin

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#2866]
I'll start by just setup a new structure for a plugin and create a branch and then iterate. I'll make the plugin run by default and then we decide how we wanna do when we release it. Either its a standalone plugin or bundled with sitespeed.io. 

Ping @mrchrisadams

**Comment by soulgalore** [comment]
There's a branch now called green that we can use as a start: https://github.com/sitespeedio/sitespeed.io/tree/green/lib/plugins/green

It doesn't do anything at the moment except generates the tabs, but no data included.

**Comment by mrchrisadams** [comment]
Oh @soulgalore, I'm so happy you started this!

I've been trying to work out how to build plugins for sitespeed to make this possible, but hadn't fully understood the API well enough to start myself, so this is so wonderful to see.

### Some background for using this to work out emissions on digital projects or products

I think it's worth pointing you to this spreadsheet I use as a basis for working out the emissions associated with an _entire_ digital project, including the servers and use of officespace, as it effectively shows what I've been doing manually to arrive at numbers for CO2 emissions, based on the reports and papers I've been able to read so far.

https://docs.google.com/spreadsheets/d/1dO2cFUu-IhK6wPwaemdxmWiQBn3WmD5vqnJXaA63yZw/edit#gid=2017551638

For a first version to iterate, I reckon it would be helpful to simply take figures for data transfer and convert them to carbon using an existing emissions factor, from a published report.

In more detail, I think there are three levels, where it would help to know where the carbon emissions associated with a page view are to inform decisions:

- **a page level**, to provide total co2 per page view - the spreadsheet I linked shows how I've been using sitespeed and analytics software to work out some indicative CO2 per month, or projected emissions for a year, for existing projects, to inform product decisions.
- **a domain level**, to work out where in your supply chain the emissions are occurring, so you know what to change, or which of your vendors to speak to, about not running on fossil fuels, for example. In my work at the green web foundation, we publish datasets of which providers run on green energy as a SQLite, as open data, to make this easier (infra running on green energy will have lower carbon emission than fossil fuels, which is why we track this).
- **a resource level**, so you can work out what measures to take in terms of WPO, from optimising assets, or making changes server-side to reduce what gets sent over the wire. You can see an example of this where @hanopcan helped [me make a change on a wordress theme to reduce page weight by around 90%](https://github.com/thegreenwebfoundation/tgwf2015/issues/1).

Working at the page level seems the obvious place to start to me. I'm not sure where I'd look to find this number yet though - I figured this would be saved in the Xray JSON object after a run, but I'm very, very new to sitespeed's internals, and wasn't sure how I'd display it after a run.

### Converting data transfer to carbon

You can see this notebook here to play with it to get an idea of what the key factors are for carbon emissions associated with loading websites, but the TLDR, is that _performance budgets are pretty much the same as carbon budgets_.

You can read a bit more in this post on [the Green Web Foundation website](https://www.thegreenwebfoundation.org/news/packets-yet-another-lever-for-a-low-carbon-internet/), but the notebook linked below is probably the fastest way to interactively get an idea of these numbers.

https://observablehq.com/@mrchrisadams/carbon-footprint-of-sending-data-around

While the model has some critics for overestimating energy use, I think the [1byte model](https://theshiftproject.org/wp-content/uploads/2018/10/Lean-ICT-Materials-1byte-Model-2018.xlsx) as described in [the French Lean ICT report](https://theshiftproject.org/en/lean-ict-2/) is a decent starting point to take a figure for data transfer, and turn it to carbon emissions.

It also has the benefit of there being an implementation in the carbonanalyser browser plugin for us to refer to for how folks have done this before. See [my issue on the carbonalyser project](https://github.com/carbonalyser/Carbonalyser/issues/2) where I explored this to use in places like sitespeed or lighthouse previously.

I'm totally up for working on this, but I'm not very confident with the sitespeed plugin API - if we wanted a tab, with a single callout box containing a figure for CO2 emissions for a page load, based on average carbon intensity of a country, I don't know which bits of sitespeed would be involved in making this yet.

I'm assuming I'd need to read [this page here on showing the boxes for plugins](https://www.sitespeed.io/documentation/sitespeed.io/plugins/#create-html-for-your-plugin), then working out how the metrics are exposed - this is the part I think i got lost on when I last looked.

Thanks again so much for pinging me on this - building knowledge about our impacts on the climate into the tools we use as professionals is what I've been trying to work out how to do for the last few years, and this is exactly the kind of the stuff I wish existed.

_*Aside:* My sister is visiting me in Berlin this weekend for the first time since I moved from the UK, so I won't be around too much over the weekend, and can't make promises about being responsive but hopefully this should give a few pointers for anyone interested in this idea._

**Comment by soulgalore** [comment]
Thanks for all the info @mrchrisadams ! Yep, with the PageXray data we should be able to do most of it. I'll have some free time tomorrow evening and will have a go at doing parts of the work :)

**Comment by soulgalore** [comment]
I've a pushed a couple of changes to the branch. Now there's base functionality and a stub for co2 calculations (but I didn't add anything there).

For checking if the server runs on green energy, I think it would be cool to use the open sqlite db, but I want to avoid adding to many dependencies to the project.  Need to think about it.

@mrchrisadams if you use Slack, you can join https://sitespeedio.herokuapp.com and we can discuss the plugin there!

**Comment by mrchrisadams** [comment]
Thanks Peter! I've joined the slack now, and I should have a bit of time this evening, and on Wednesday to look into this.

On the server check, the sqlite db is a basically an offline version of the API visible at

https://api.thegreenwebfoundation.org

TBH, I think would be super cool, but just having a carbon/climate tab with one metric would be fantastic, and help me understand how to make the others as a separate plugin.

**Comment by mrchrisadams** [comment]
Hi @soulgalore, can I check the command I should be using to see something?

I've checked this green branch out, but I think I'm using the plugins wrong, as I can't seem to get anything to appear in the generated html report, when I run sitespeed like so, from the sitespeed.io directory

```
./bin/sitespeed.js https://some-website.com/ --headless --plugins.add sustainable
```

I've tried checking my command [against the docs for plugins][docs], I've tried this too, without much luck.

[docs]: https://www.sitespeed.io/documentation/sitespeed.io/plugins/#testing-your-plugin

```
./bin/sitespeed.js https://blog.chrisadams.me.uk/ --headless --plugins.add lib/plugins/sustainable
```

If I'm developing locally can you let me know the correct incantation I should be using?

**Comment by soulgalore** [comment]
If you checked out the branch this should be enough (I've added so the plugin runs automatically for now):

```
~/git/sitespeed.io green
❯ bin/sitespeed.js https://blog.chrisadams.me.uk/  --headless -n 1
```

<img width="1332" alt="Screenshot 2020-02-10 at 20 51 00" src="https://user-images.githubusercontent.com/540757/74184442-195aee00-4c47-11ea-9e8d-a75c56fd581d.png">

**Comment by soulgalore** [comment]
You should have access to the repo, so if you cloned it before:
```
git fetch origin
git checkout green
```

should be enough I think :)

**Comment by soulgalore** [comment]
Woho this was released some time ago!
