### ISSUE TITLE
question: tti with sitespeed.io

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#3024]
Hello, @soulgalore 
I'm just curious why there is no time to interactive and first cpu idle metrics collected with chrome using sitespeed.io?

Best Regards

**Comment by soulgalore** [comment]
Hi @Icecold777 I tested out TTI a couple years ago on Wikipedia see https://phabricator.wikimedia.org/T176369 and it was a really unstable metric for us (see the graphs) and I've been really skeptical how people would use it. It was a lot of propaganda for the metric when it was released and I was skeptical (but maybe it works better on other web sites that Wikipedia?). The Chromium team removed TTI from their RUM because its too noisy https://bugs.chromium.org/p/chromium/issues/detail?id=1039782. I think I was right (but that is probably the first time :D).

CPU Idle, yeah, maybe we could add that by parsing the trace log. What I've seen problematic when using TTI (that also need the idle time) is to know how long time to wait for it to become idle. I think most definitions use 5 seconds right? That means that when you normally ends your test you need to wait X seconds to know that it is idle. For example if you run Firefox and want TTI will mostly not be included (because the normal end test time is too early so TTI hasn't been populated yet. I like Firefox approach though that they includes it in the browser instead of (in Chromes case) you need to go though the trace log and calculate it yourself).

**Comment by Icecold777** [comment]
Hi @soulgalore. thank you for your answer. I understand that TTI maybe unstable and confusing but at least First CPU Idle will be useful.
