### ISSUE TITLE
Is there a way to run mobile test on Windows

### ISSUE THREAD

**Issue by chenghuangu** [sitespeedio/sitespeed.io#3035]

**Comment by soulgalore** [comment]
Hi @chenghuangu I hope so but I haven't tested it, since I don't have Windows. If you run without Docker and install the requirements as in https://github.com/sitespeedio/browsertime/blob/master/.github/workflows/windows.yml -

I can try to guide you if you run into problems, it would be interesting to know if it works or if we can make it work.

**Comment by soulgalore** [comment]
Closing, let me know if it didn't work out.
