### ISSUE TITLE
Incorrect metric's name for PageXray assets (array index instead of full name)

### ISSUE THREAD

**Issue by mklpanasiuk** [sitespeedio/sitespeed.io#3296]
Hi, it should be similar to - https://github.com/sitespeedio/sitespeed.io/pull/1341
**Steps to reproduce:**
1. Run command: `docker run --shm-size=2g --rm -v "C:/Users/mykola.panasiuk/myDockerVolumes/sitespeed:/sitespeed.io" sitespeedio/sitespeed.io:16.9.2-plus1 --plugins.remove /gpsi --plugins.remove /lighthouse --config config.json -n 1 --graphite.host=host.docker.internal --graphite.namespace demo3.test2 --html.showScript myscript.js --multi --metrics.filterList --metrics.list`
2. Check data in configuredMetrics.txt and metrics.txt
3. Go to Graphite and find your metrics

**Actual result:**
Array index instead of full name of asset
**Expected result:**
The same name as in metrics.txt, like: `pagexray.pageSummary.assets.https___ng_example_css.contentSize`
Also I keep in mind youe advice: _However: Please don't send all the assets to Graphite, it will fill your disk._
Hope for your help as for me there is a couple of files I want to track to
![2021-03-03_18-40-17](https://user-images.githubusercontent.com/53987913/109841169-75792180-7c51-11eb-981a-b436c826178c.png)

**Comment by SkynetKoks** [comment]
Sorry for off topic, but also a quick question: Is there a way to pass boolean value from CLI? So far it works for me only when I set it directly in config, otherwise I get it as string which is wrong, example:
![2021-03-02_09-00-29](https://user-images.githubusercontent.com/53987913/109841885-2e3f6080-7c52-11eb-92b3-52c6577d54b5.png)

**Comment by soulgalore** [comment]
Hmm, what do you want to do? Like what so you want to accomplish with the data in Graphite? Keep track of an all assets sizes individually?

**Comment by SkynetKoks** [comment]
@soulgalore Hi, thank you for your response. I meant the next:
1. When looking at metrics.txt (with the command `--metrics.list`) I have found the metrics I was looking for:
`pagexray.pageSummary.assets.EXAMPLE_FILE_OR_LINK.contentSize`
2. Following to specs from Sitespeed.io I have an option to save it to Graphite like:
`--metrics.filter pagexray.pageSummary.assets.*.contentSize` or to be more specific `--metrics.filter pagexray.pageSummary.assets.EXAMPLE_*_css.contentSize`
3. Then I'm expecting to get this metric in Graphite with:
`sitespeed_io.desktop.pageSummary.my_domain.my_path.chrome.native.pagexray.assets.EXAMPLE_file_css.contentSize`
but instead of `EXAMPLE_file_css` I have array index of asset:
`sitespeed_io.desktop.pageSummary.my_domain.my_path.chrome.native.pagexray.assets.1.contentSize`
What is not expected. I thought that you fixed it in https://github.com/sitespeedio/sitespeed.io/pull/1341
**Note:** you will be able to see assets metric in Graphite only with whole metric name regex:
`--metrics.filter pagexray.pageSummary.assets.*.contentSize`, with `--metrics.filter pagexray.pageSummary.assets.EXAMPLE_*_css.contentSize` it will not save anything.
I tried to be as clear as possible as I very interested in fixing this issue, please let me know if you need more info or assist

**Comment by soulgalore** [comment]
Yes, but I meant your goal is to track the size of each file individually in Graphite? Isn't better to either track the total size for CSS or for first party content and then if you reach a threshold look in the HTML result to see what's has changed? For tracking individual assets I think another data storage will be better but I haven't implemented any yet.

**Comment by SkynetKoks** [comment]
@soulgalore Total is good by default, my developers are very interested to track specific files (a few), mostly JS files, this should be a huge challenge for Graphite. It seems that Sitespeed is able to do that simple task out of the box, except proper naming of metric, at least index of an asset in the metric name is weird and useless at the moment

**Comment by SkynetKoks** [comment]
Hi, @soulgalore. Any hope to get it fixed in the near future?

**Comment by soulgalore** [comment]
No but PRs are open if you have rime :) I had a quick look and it looks like `--metrics.filter "pagexray.pageSummary.assets.*"` gets the asset name correct? But adding either the name or the metric makes it fails.

**Comment by soulgalore** [comment]
I still don't think tracking individual assets is the way to go in Graphite, so closing.
