### ISSUE TITLE
Slow triggering of DOMContentLoaded due to larger page size

### ISSUE THREAD

**Issue by amtanq** [sitespeedio/sitespeed.io#3410]
I have noted a large size of bundles, which cascades in the slow triggering of **DOMContentLoaded**. This in turn makes the page tab initialization slow for both non saved and saved tab routes.
![](https://i.imgur.com/Qbmg7ye.png)

**Benchmark**
![](https://i.imgur.com/ThC2rCv.png)

**Benifits**
Not only fixing this issue will speed up tab switches but also the overall initialization time of the page

**Suggested Fixes**
Splitting of javascript file from the HTML page
Handling DOM elements as soon as they load instead of waiting for the page to load completely

**Discussion**
In order to fix the issue I need to alter the page structure ie I need to rearrange the scripts and embed some code between HTML to efficiently handle this issue. Should I go ahead or I need to look for some other way instead of changing the structure of scripts.

Edit: Another popular way used by most of the sites is by tackling this issue is to show a user friendly loader until DOM loads completely.

**Comment by soulgalore** [comment]
Hi @amtanq I think the problem here is. that the HAR file is included in the HTML by default. As it is now the HAR file keeps all the runs in one file. If you do X runs, all those runs are in the same HAR and the HTML-blob becomes bigger.

if you serve the HTML result from a server, you can configure ` --html.fetchHARFiles true` to instead load the HAR from a URL instead.

**Comment by amtanq** [comment]
Yes! I checked out with multiple runs with different values of n and found out this is the case. So I'll close the issue, feel free to open it again if we need to do something else for the issue.
