### ISSUE TITLE
Usage of sitespeed.io for SPA.

### ISSUE THREAD

**Issue by vishnusn656** [sitespeedio/sitespeed.io#3411]
Hi,
I have a react js application which works in spa model mostly. There will be few full page loads(with URL changes), and I also have to test clientside performance for various steps which doesnot have URL changes associated with them. Does sitespeed successfully records metrices(Web vitals) for UI changes which does not have URL changes? I noted in several instances that measure() is not designed for this purpose. Your inputs will be very useful.

Thanks in advance!!

**Comment by soulgalore** [comment]
Hi @vishnusn656 so browsers do not at the moment have a good support for measuring GoogleWebVitals or other metrics since they are focused on navigation. So for example first contentful paint  in Crome are tied to a navigation, so if you in a SPA navigate to multiple pages it will report that metric for the first navigation. 

If you use sitespeed.io you should add `--spa` to your test, that will make sure a that the page complete check (that waits for the page to finish) waits on that there's no network traffic. By default sitespeeed.io waits on for the unload event to happen but if you use a SPA that only happens once. You can read more in the docs https://www.sitespeed.io/documentation/sitespeed.io/spa/

You can use the video to measure when things happens on a SPA. For example last visual change usually works fine. However if your URL do not change its harder since most things are tied to a URL in sitespeed.io.  You can try use the stop watch functionality: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#stop-watch

**Comment by Icecold777** [comment]
Hello,

@vishnusn656 please take a look at https://github.com/sitespeedio/sitespeed.io/issues/3273#issuecomment-775598691 maybe you'll find it useful.
It solved the issue with no changing page URL for me.
