### ISSUE TITLE
Getting ERROR: Error: connect ECONNREFUSED 127.0.0.1:2003 from Ubuntu

### ISSUE THREAD

**Issue by palanir2** [sitespeedio/sitespeed.io#3450]
Hi - Currently we are working on migrating the sitespeed to AWS Ubuntu instances. For POC purpose installed both sitespeed and docker compose on the same instances. When I ran the below commands i'm getting 2021-08-30 23:58:24] ERROR: Error: connect ECONNREFUSED 127.0.0.1:2003    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16).
Commands i have tried:
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:19.2.0 --graphite.host 127.0.0.1 https://www.sitespeed.io/ --graphite.port=2003
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:19.2.0 --graphite.host = 27.0.0.1 https://www.sitespeed.io/
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:19.2.0 --graphite.host localhost https://www.sitespeed.io/

**Comment by soulgalore** [comment]
Hi @palanir2 when you run inside Docker, localhost/127.0.0.1 point inside the same container = sitespeed.io in this case, not the Graphite container. Here are docs depending on your OS: https://www.sitespeed.io/documentation/sitespeed.io/docker/#access-localhost

**Comment by palanir2** [comment]
Hi @soulgalore - I'm new to docker, can you please help me with how/what (in the above command what I need to change) I need to run the command when sitespeed and docker compose on the same instance?

**Comment by soulgalore** [comment]
Hi @palanir2 it should be there in the docs I linked https://www.sitespeed.io/documentation/sitespeed.io/docker/#access-localhost ?  Depending if you use Linux or Mac/Windows its different ways of accessing localhost in the real machine from inside of docker. Either use `host.docker.internal` or  add `--network=host`

**Comment by palanir2** [comment]
Hi @soulgalore - I'm using Linux (ubuntu), installed sitespeed and docker compose in the same machine for POC. when I ran the below command it's working
 **docker run --shm-size 2g --rm -v "$(pwd):/sitespeed.io" --network host sitespeedio/sitespeed.io:19.2.0 -b firefox https://www.sitespeed.io**
but how to send the metrics to graphite: what will be value for this **graphite.host=** whether I need to give **localhost** or **instance IP address**?

**Comment by soulgalore** [comment]
Hi @palanir2 in the docs  https://www.sitespeed.io/documentation/sitespeed.io/docker/#access-localhost you should use localhost on Linux, so add `--network=host` and use `--graphite.host localhost` hopefully that will fix it!

**Comment by palanir2** [comment]
Hi @soulgalore - I have tried this command "**docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:19.2.0 --graphite.host=localhost --network host https://www.sitespeed.io/ --slug yourTestName --graphite.addSlugToKey true**". But still getting **[2021-08-31 13:16:55] ERROR: Error: connect ECONNREFUSED 127.0.0.1:2003
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)**

**Comment by soulgalore** [comment]
When I try top debug, I usually send metrics directly from the server to see that it works, something like  https://graphiteapp.org/quick-start-guides/feeding-metrics.html . If that works, then I would try to login to the container (https://www.sitespeed.io/documentation/sitespeed.io/docker/#inspect-the-container) and then to try send a test metric.

**Comment by soulgalore** [comment]
Closing but please let me know if this is still an issue.

**Comment by tprocter1984** [comment]
For anyone coming across this error, it's due to putting `--network host` in the wrong place. 

The command should be as follows: 
`docker run --rm -v "$(pwd):/sitespeed.io" --network host sitespeedio/sitespeed.io:26.1.0 --graphite.host localhost https://www.sitespeed.io/ --slug yourTestName --graphite.addSlugToKey true`

@soulgalore I would strongly recommend adding this to the docs as it would save a lot of time for other people.

**Comment by soulgalore** [comment]
Hi @tprocter1984 cool, can you help which doc you were looking at so I can fix it? In the Docker section to access localhost it seems to look correct: https://www.sitespeed.io/documentation/sitespeed.io/docker/#access-localhost

**Comment by tprocter1984** [comment]
@soulgalore yeah, you're quite right. It is correct there, however it's not clear that you have to put `--network host` before `sitespeedio/sitespeed.io:26.1.0` 

I would suggest simply adding the example I provided instead of: "(running on Linux? [Check how to access localhost])" on step 3 here: https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-almost-5-minutes

The error that @palanir2 made, and myself, (putting `--network host` in the wrong place) suggests that it's not clear where you put `--network host` in the documentation. 

A clear example command would be good to see along side the Windows example. 

Hope this helps.
