### ISSUE TITLE
Can sitespeed support playwright's js script？

### ISSUE THREAD

**Issue by heavenmyth** [sitespeedio/sitespeed.io#3452]
Can sitespeed support playwright's js script？

I use sitespeed to run playwright's js script prompt Cannot find module'playwright'

![image](https://user-images.githubusercontent.com/26155539/131853877-95dee0d6-2bf3-4b28-9831-defec9ecf5db.png)

**Comment by soulgalore** [comment]
Hi @heavenmyth the short answer is no. The long answer:
At the moment the backend for starting/driving/stopping the browser is Selenium that follows the WebDriver specification. The reason we started to use it is that when we first implemented puppeteer and playwright wasn't there yet. I've been looking into adding support for other backends, but since puppeteer do not work on mobile phones (or at least didn't) I don't see the reasons to spend time to implement it.


For using either libraries when you run a Dockerised version of sitespeed.io you need to make sure that the npm package is installed in the node_modules folder so that the script can find it.

**Comment by soulgalore** [comment]
Hi @deena9291 I haven't followed along, do Playwright work with iOS/Android now?

**Comment by deena9291** [comment]
Seems like they support on an experimental basis, please have a look here;
https://github.com/microsoft/playwright/issues/6906

**Comment by 2343909** [comment]
@soulgalore I am a new user of the sitespeed.io and I was curious if there has been any progress or plans on implementing playwright with Sitespeed or if this is not in plans yet?
