### ISSUE TITLE
odd metrics when using --preURL

### ISSUE THREAD

**Issue by zer0kool** [sitespeedio/sitespeed.io#3527]
## Use-case scenario
my intention was to fill the cache by loading the homepage and then running the test on a category page. 

## Questionable metrics
Filmstrip:  [Bed Bath & Beyond](https://4007ftte7ouct8f30vts4rh1bapj7hl42ta3fda6esnb6581ffp2gb0.siasky.net/pages/www_bedbathandbeyond_com/store/category/kitchen/10002/index.html#filmstrip) 
There are some metrics seen in the filmstrip that seem to be capture during the --preURL. For example the First Contentful Paint on the test sample is 675ms, but the rendering happens around 750ms.

is it possible that im missing something on my configuration? 

## Settings that will help replicate it
Docker image
`image: sitespeedio/sitespeed.io:21.1.0-plus1`

The command prefix
``` bash
sitespeed.io --preURL https://www.bedbathandbeyond.com/ https://www.bedbathandbeyond.com/store/category/kitchen/10002/ --slug pwa --config mobile.json
```
The configuration
``` json
{
    "mobile": true,
    "cpu": true,
    "utc": true,
    "gzipHAR": true,
    "axe": {
        "enable": true
    },
    "sustainable": {
        "enable": true
    },
    "browsertime": {
        "mobile": true,
        "visualElements": true,
        "iterations": 2,
        "browser": "chrome",
        "video": true,
        "visualMetric": true,
        "chrome": {
            "CPUThrottlingRate": 2,
            "collectConsoleLog": true,
            "includeResponseBodies": "html",
            "enableTraceScreenshots": true
        }
    },
    "screenshot": {
        "type": "jpg"
    },
    "graphite": {
        "host": "graphite",
        "namespace": "grafana.sitespeed"
    },
    "slack": {
        "hookUrl": "a.hook"
    },
    "gpsi": {
        "key": "a.key"
    },
    "resultBaseURL": "IP_Addrs",
    "copyLatestFilesToBase": true
}
```

**Comment by soulgalore** [comment]
Hi @zer0kool thanks for the bug report!  Your configuration looks good. I usually use the trick https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measure-multiple-pages-and-start-white when I measure a page with filled cache. You need to change then so the first is just a navigation. That will fix your visual metrics (that comes from the video). For example in your filmstrip the first visual change is picking up some minor changes that probably will be fixed by the start white. 

First Contentful Paint comes directly from Chrome and not by the video so that should be as correct as it can be in Chrome and sometimes that is off. If you first try the "start white" trick and you still have metrics that seems off, I can look deeper.


Best
Peter

**Comment by zer0kool** [comment]
Hi @soulgalore, that seems to be working. Thank you!
