### ISSUE TITLE
Configure https grafana docker-compose

### ISSUE THREAD

**Issue by JosueMal** [sitespeedio/sitespeed.io#3663]
### Your question

Hi, 
I would kike to know if are there a tutorial or docker-compose file version, with the configuration for HTTPS in grafana? 

Regards, 
Josue

**Comment by soulgalore** [comment]
Hi @JosueMal I think the easiest is to use a reverse proxy as in https://grafana.com/tutorials/run-grafana-behind-a-proxy/

Best
Peter

**Comment by JosueMal** [comment]
Hi @soulgalore thanks for the advice, let me check into the documentation.

I forgot to mention, that I am using your sitespeed docker-compose file, and also I am collecting some data for some pages, I just would like access thru HTTPS to grafana. But let me check into the documentation 

Regards,
Josue M

**Comment by soulgalore** [comment]
Ok! For https://dashboard.sitespeed.io we use the reverse proxy setup with nginx described in the Grafana docs.

**Comment by ClementToche** [comment]
> Hi @JosueMal I think the easiest is to use a reverse proxy as in https://grafana.com/tutorials/run-grafana-behind-a-proxy/

It's unfortunatelly not a good idea because the connection between your proxy and grafana will still be unencrypted.
So if your system is hacked and hacker to listen on your localhost port, then he can retrieve user/password exchange between proxy and grafana.

**Comment by ClementToche** [comment]
Hi @JosueMal ,

I do not have docker compose script because I do my own script for docker without using compose but here is the hint that can be easily transposed to docker composer.

Put your key/cert in a folder where your grafana docker can read (ex. /mydata/grafana/certs/).
Run docker by mounting this folder to your docker image.
Override your grafana configuration parameters : 
* Pattern doc : https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
* Docker conf overriding doc : https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#use-environment-variables-to-configure-grafana

It should result in something like this :
docker run -p 3000:3000 \
    -d \
    --restart=always \
    --name=grafana \
    --user $(id -u grafana-user):$(id -g grafana-user) \
    -v /etc/passwd:/etc/passwd:ro \
    -v /mydata/grafana/data/:/var/lib/grafana/ \
    -v /mydata/grafana/certs/:/etc/certs/ \
    -e "GF_SERVER_PROTOCOL=https" \
    -e "GF_SERVER_PORT=3000" \
    -e "GF_SERVER_DOMAIN=yourcertdomain" \
    -e "GF_SERVER_ENFORCE_DOMAIN=true" \
    -e "GF_SERVER_ROOT_URL=yourcertdomain:3000" \
    -e "GF_SERVER_CERT_KEY=/etc/certs/privkey.pem" \
    -e "GF_SERVER_CERT_FILE=/etc/certs/fullchain.pem" \
    grafana/grafana:8.5.25

**Comment by soulgalore** [comment]
Thanks for adding the example.

**Comment by benjisho** [comment]
Feel free to use my repo for Grafana + Nginx for HTTPS setup with docker-compose.
https://github.com/benjisho/grafana-container
It's pretty much plug-n-play and I use it for my personal labs. - but it's a good starting point.

> note that you should update the Grafana and Nginx versions to whatever you prefer

Hope it helped 😃

**Comment by benjisho** [comment]
> ### Your question
> Hi, I would kike to know if are there a tutorial or docker-compose file version, with the configuration for HTTPS in grafana?
> 
> Regards, Josue

Feel free to use my repo for Grafana + Nginx for HTTPS setup with docker-compose as reference.
https://github.com/benjisho/grafana-container
It's pretty much plug-n-play and I use it for my personal labs. - but it's a good starting point.

> note that you should update the Grafana and Nginx versions to whatever you prefer

Hope it helped 😃
