### ISSUE TITLE
Pa11y in Sitespeed

### ISSUE THREAD

**Issue by JosueMal** [sitespeedio/sitespeed.io#3713]
### Your question

Hi, 
I see sitespeed is using AXE to scan accessibility web pages.
But, could you let me know if it is possible to run the Pa11y tool and if graphing the results?

Regards, 
Josue M.

**Comment by soulgalore** [comment]
Hi Josue, there's no pre made plugin that I know of for getting pa11y metrics, so you need to build that yourself. I could help out if you need. When I looked at it many years ago there was no way to run pa11y tests in the current browser session (like first we run the performance tests and the pa11y), instead it will open a new browser and run the tests, but maybe that has changed since then, I haven't looked.

Best
Peter

**Comment by JosueMal** [comment]
Hi @soulgalore 
Thanks for the advice.
Pa11y use a ci and also a dashboard that probably could help to attach the numbers in the dashboard, could you help me a guidance about how to create this new plugin?

Also, regarding AXE, I checked the documentation page[https://www.sitespeed.io/documentation/sitespeed.io/axe/](Axe) and I would like to run axe with the option wcag2aa, but the command "**--axe.enable --axe.checks wcag2aa**" didn't works could you advice if I am doing correctly, please

Regards
Josue M.

**Comment by soulgalore** [comment]
Hi Josue, sorry for the late answer.

There are some documentation on how to build a plugin in https://www.sitespeed.io/documentation/sitespeed.io/plugins/#how-to-create-your-own-plugin

Then since my guess is Pa11y will use there own browser to run the test, that needs to wait until browser time has finished. That's how the Lighthouse plugin to do run their tests. There's hack there that waits on Browsertime to finish and then sends a job in the queue for running a Lighthouse audit (looking at the code, I think it could be simplified): https://github.com/sitespeedio/plugin-lighthouse/blob/main/index.js#L86-L107

**Comment by JosueMal** [comment]
Thanks for the answer @soulgalore 

About the AXE, could you give me an example to run it with the wcag2aa standard? I suppose AXE could help me if I got the same numbers as Pa11y. 

I just need to figure out how to indicate to AXE run under the standard wcag2aa, the command I am using is:
**--axe.enable --axe.checks wcag2aa**
but it is not working, could you advise please?

Regards
Josue M.

**Comment by soulgalore** [comment]
It's complicated using the cli so it's better to use a configuration JSON. 

However I think there's a bug in the code where not everything is passed on to AXE when we try to configure it and it's also confusion in the sitespeed.io code when to use the configuration object versus the option object when you AXE (https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#api-name-axeconfigure). 

In your case I think the "runOnly" option should be used, but that will not work until I've done some fixes.

**Comment by JosueMal** [comment]
Thanks for the update @soulgalore  
Please let me know if I need to run a new release of sitespeed (in docker) or if I just to modify my command

Regards
Josue Maldonado

**Comment by soulgalore** [comment]
I need to do a new release for it to work, I'll do that this weekend and I'll ping the thread when its done.

**Comment by soulgalore** [comment]
@JosueMal try out 25.11.0 and then use a runOnly section see https://www.sitespeed.io/documentation/sitespeed.io/axe/#configure-axe. We pass on everything to AXE  but in two steps. AXE documentation is here: https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#api-name-axeconfigure 

I'm gonna update our docs, it's not super clear at the moment but I added one example with the thing you tried to do.

**Comment by JosueMal** [comment]
Hi @soulgalore 
thanks for the update. 
the fix works perfectly!!, but still I cannot see the same numbers in AXE, as I got in Pa11y, but it is probably some extra command or value.

Thanks for the help, and we can close the issue if you want

Regards
Josue Maldonado

**Comment by soulgalore** [comment]
Ok closing, let me know if you still get different values, it would be interesting to understand the difference.
