### ISSUE TITLE
Is Sitespeed version 33.6.1 out?

### ISSUE THREAD

**Issue by edruizTA** [sitespeedio/sitespeed.io#4162]
### Your question

Hi there, I tried updating to 33.6.1, but I'm getting this error:

```
Unable to find image 'sitespeedio/sitespeed.io:33.6.1' locally
33.6.1: Pulling from sitespeedio/sitespeed.io
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.

```

The [changelog](https://github.com/sitespeedio/sitespeed.io/blob/main/CHANGELOG.md) mentions 33.6.1 contains a fix I think I need for GPSI, but [Sitespeed.io](https://www.sitespeed.io/) points at 33.6.0 as the most recent version. So, I'm a bit confused about whether 33.6.1 has been released. To give you some background, I was hoping the newer version would fix this error I'm having for the GPSI plugin:

```
TypeError: Cannot read properties of undefined (reading 'score')
    at repackagePageSummary (file:///gpsi/lib/pageSummary.js:19:58)
    at file:///gpsi/lib/index.js:92:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Thanks!

**Comment by soulgalore** [comment]
Hi @edruizTA 33.6.1 is out but only for AMD, sorry. The problem was that when GPSI changed Lighthouse version that removed the PWA metrics, the plugin broke, but I'm in the middle of releasing a new major and couldn't use the normal release flow (it's an GitHub action that pushes the release). The new major release will drop on the coming Monday by the latest.

**Comment by edruizTA** [comment]
@soulgalore Got it! Thanks for the quick response. I'll keep an eye out for the next mayor release.
