### ISSUE TITLE
Replicate First View and Repeat View type functionality from WPT

### ISSUE THREAD

**Issue by yashgarde** [sitespeedio/sitespeed.io#4235]
### Your question

Is there an easy way using the configuration flags within sitespeed.io to perform a First View and Repeat View functionality that WebPageTest provides (without actually running on WPT)?

I understand that when given more than 1 iteration (`-n 5` for example) that each iteration starts up a new browser session with a cleared cache. Would this be equivalent to a first view from WPT then?

Additionally, the documentation suggests that to test cached pages, we should use the `--preURL` or scripting. Since a majority of my tests will involve user journeys and hence need to be performed via scripting, what is the recommended way to test cached pages in this case? How does the `--multi` flag work in these cases as well, the documentation was not super clear about this.

All help is appreciated!

**Comment by soulgalore** [comment]
The repeat view in WebPageTest tests one page, closes the browser and then open it again and access the same page, I never implemented that because I never seen the use case meaning never seen that user behaviour.

However if you want to test something the similar, you could navigate to the page, navigate to about:blank and then measure the page. For a user journey scenario where you measure multiple pages in a journey, I think you could do the same. I guess it depends on your site and user behaviour, I try to optimise the journey between pages and not between visits. So for example if a have journey with 5 pages, I try to get information of how long time the user stay at one page before moving to the next page so my test is like this:
1. Measure first page
2. Scroll/ wait on the page for X seconds simulating the user reading the page
3. Click on to the next page 

And then I focus on the time each page takes to load and see how I can make sure assets are cached between different pages.

**Comment by yashgarde** [comment]
I have moved forward with simply performing the same actions within the script twice and measuring them as two separate pages with aliases. This seems to work for repeat view calculation for the time being.
