### ISSUE TITLE
All results must be generated as json and HTML files should be optional

### ISSUE THREAD

**Issue by nitinprakash** [sitespeedio/sitespeed.io#548]
Hey,
I think it would be better to make HTML files for summary and all be optional.
What if someone needs only the results not the HTML views ??
I dont know whether output folder path is customizable but it should be customizable too

**Comment by soulgalore** [comment]
hey @NitinMaaraj 
we've added a Vagrant setup for CentOS 7, you can check there how to install:
https://github.com/sitespeedio/sitespeed.io-vagrant/tree/master/sitespeed-centos7

Best
Peter

**Comment by NitinMaaraj** [comment]
Thanks Peter,

I am looking forward to it.. i will check it up soon.
Got delayed because github got banned in my country unfortunately but its
up and running now

On Mon, Jan 12, 2015 at 4:16 AM, Peter Hedenskog <notifications@github.com>
wrote:

> hey @NitinMaaraj <https://github.com/NitinMaaraj>
> we've added a Vagrant setup for CentOS 7, you can check there how to
> install:
>
> https://github.com/sitespeedio/sitespeed.io-vagrant/tree/master/sitespeed-centos7
>
> Best
> Peter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sitespeedio/sitespeed.io/issues/548#issuecomment-69515751>
> .
>



-- 

*Regards Nitin Prakash*

**** CAUTION - Disclaimer ****

This e-mail contains PRIVILEGED AND CONFIDENTIAL INFORMATION intended
solely for the use of the addressee(s). If you are not the intended
recipient, please notify the sender by e-mail and delete the original
message. Further, you are not to copy, disclose, or distribute this e-mail
or its contents to any other person and any such actions are unlawful. This
e-mail may contain viruses. MaaRaj Strategic Development, has taken every
reasonable precaution to minimize this risk, but is not liable for any
damage you may sustain as a result of any virus in this e-mail. You should
carry out your own virus checks before opening the e-mail or attachment. MaaRaj
Strategic Developmentreserves the right to monitor and review the content
of all messages sent to or from this e-mail address. Messages sent to or
from this e-mail address may be stored on theMaaRaj Strategic
Development, e-mail
system.

  *** MaaRaj Strategic Development, USA *** End of Disclaimer ***
