### ISSUE TITLE
Add a flag for suppressing the creation of files and folders

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#555]
In 3.0.3 we added the flag of not creating HTML files, would be cool though when you send the data to Graphite to not create any data at all (except the logs).

**Comment by soulgalore** [comment]
ping @tobli lets discuss this later today: either at a check where we create the files or just remove everything?

**Comment by prein** [comment]
+1
Also, or alternatively, it would be great results could be rotated without external scripting. Some sort of result data retention paraneter like --keep-results=7d would be great.

**Comment by soulgalore** [comment]
@prein yep, that's a good idea thanks, a lot of work I think to accomplish now first I think. Will do a fix release in one/two days to at least remove the files.

**Comment by soulgalore** [comment]
discussed this with @tobli and the easiest way right now should be to set the result base dir to /tmp:
<code>-r /tmp</code>

I will update the documentation tonight and then close the issue.

**Comment by tobli** [comment]
@prein - to keep sitespeed.io maintainable and focused, things like log rotation are best kept outside the core. If you'd like, you could write your own [post task script](http://www.sitespeed.io/documentation/#postTasks) to clean up old logs.

Otherwise a shell script oneliner should do it, like:
"find sitespeed-result -type d -d 2 -Btime -7d  -exec rm -r {} +"

**Comment by soulgalore** [comment]
closing this now (updated the docs). @prein please get back if there's something that don't work for you.

**Comment by prein** [comment]
Thanks @tobli, I wasn't aware of post task feature. I'm currently running shell oneliner, but post task job seems more elegant way to do it.
