### ISSUE TITLE
Graphite: pagemetric only available as summary

### ISSUE THREAD

**Issue by JeroenVdb** [sitespeedio/sitespeed.io#557]
Pagemetrics (like domElements, Requests w/o Gzip) are only available under the summary node in Graphite. Is this a bug? 
When I analyze multiple pages I now can't pinpoint which page has how many domElements.

```
# Works
sitespeed.summary.site.com.pagemetric.imageWeight.median

# Not available
sitespeed.http.site.com.slash.imageWeight
```

**Comment by soulgalore** [comment]
Hi @JeroenVdb ,
yes could be that I've missed some of them, I will check and verify tomorrow. For the domElements you should be able to see it by the score, something like sitespeed.http.site.com.slash.rules.domElements.

Best
Peter

**Comment by soulgalore** [comment]
Hi again Jeroen,
ok, checked now, it's incredible how fast you forget ... ok.
To get sizes of things like images, check <code>sitespeed.http.site.com.slash.assets</code> there you see size and how many.

DomElements & requests with & without gzip can only be found right now with the rule score <code>sitespeed.http.site.com.slash.rules</code>, so that is not perfect. The problem right now is that it can't be automated in a good way (the values is kind hacked in getting them from YSlow). I think the long term solution should be to create our own "engine" that check the rules and how the pages is built. @tobli  and me want it, but don't know when in time we can invest the time to do it.

best
Peter

**Comment by soulgalore** [comment]
Closing too old issues. Lets start with new clean sheet for 4.0.
