### ISSUE TITLE
Pass request headers to WebPageTest

### ISSUE THREAD

**Issue by thebostik** [sitespeedio/sitespeed.io#568]
Right now we don't pass headers to WPT.

In WPT script syntax you can provide headers with [addHeader](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-addHeader). 

The node WPT API wrapper replaces URL in order to accept script.

So... would it make sense to support to headers passed in to WPT via script, and give a new sitespeed option to enable this mechanism? 
The WPT script would become:
    addHeader {first header from the header file}
    addHeader {next header that the user passes}
    .......
    navigate {current sitespeed url}

I searched to find a more optimal way to provide URL and just add headers via option to WPT and couldn't find anything. Does this alternative seem workable?

**Comment by soulgalore** [comment]
Hi Stephen,
thanks, hadn't checked the script syntax before. Yes that could actually be the way to do it!

I think like this: We would probably not add the possibility to add other script functionality, so that hack would be a good way forward.

Could probably start testing it out next week, have a couple of other things to do first.

Best
Peter

**Comment by soulgalore** [comment]
Haven't implemented this but maybe the script support for WebPageTest will do it for now?

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
