### ISSUE TITLE
Bad argument error when running sitespeed.io command

### ISSUE THREAD

**Issue by tfayyaz** [sitespeedio/sitespeed.io#590]
Hi,

I have installed sitespeed.io globally and I get the following error when I try to use the sitespeed.io command. 

I am running this on OS X 10.8.3

This is an example command

```
sitespeed.io --url http://www.bbc.co.uk -m 2
```

This the error that comes up

```
usr/local/lib/node_modules/sitespeed.io/node_modules/phantomjs/lib/location.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              ^
TypeError: Bad argument
    at ChildProcess.spawn (child_process.js:915:24)
    at exports.spawn (child_process.js:715:9)
    at Object.exports.execFile (child_process.js:607:15)
    at async.parallel.childProcess.exec.timeout (/usr/local/lib/node_modules/sitespeed.io/lib/util/util.js:345:24)
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:570:21
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:249:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:46:24)
    at async.each (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:124:9)
```

Not sure if it's because I have an old version of Phantomjs already installed but even tried to update that and still no luck.

Thanks

Tahir

**Comment by soulgalore** [comment]
Hey Tahir,
thanks for the report! Hmm, what happens is that it times out when sitespeed tries to run <code>phantomjs --version</code>. If you run it in your command line, what version do you have and does it work? The one that will be installed with sitespeed.io is 1.9.8. If you can try it out (we don't use 2 yet since it doesn't exist in Linux yet) and see if it works outside of sitespeed, that would really help.

Best
Peter

**Comment by soulgalore** [comment]
hello @tfayyaz
closing this issue now, please re-open if it is still an issue.
