### ISSUE TITLE
Not getting repeatView while driving WebPageTest through sitespeed.io

### ISSUE THREAD

**Issue by darraghgrace** [sitespeedio/sitespeed.io#663]
Hi, 
I am using sitespeed.io to drive testing on a private webpagetest instance and send data to Graphite. I am only getting results for firstViewOnly but I also want to test repeatView.
My json looks like this
{
  "pollResults": "10",
  "timeout": "2400",
  "firstViewOnly": "false",
  "runs": "3", 
  "private": "false",
  "aftRenderingTime": "true",
  "location": "eu-west-1:Chrome",
  "video": "true"
}
I have also tried "first": "false" in place of firstViewOnly, same result.
I've checked the documentation but maybe I am missing something?
Many thanks

**Comment by soulgalore** [comment]
Hi @darraghgrace ,
do you see that the configuration gets picked up correctly? It looks right except that the true/false values doesn't need to be strings., test change them to just *false*. Else you can just remove the line 
"firstViewOnly": "false"
because it configured by default (the config is merged with the default one so you only need to configure things that needs to be changed/override).

If it doesn't work, could you share the logs so I can see what happen? You can turn on *--verbose* and the response will be logged from WPT, sometimes that helps to see what's wrong.

Best
Peter

**Comment by darraghgrace** [comment]
Hi @soulgalore . Thank you for the suggestions, I left the firstViewOnly entry out altogether and got the results for repeatView.
Much appreciated!
Darragh
