### ISSUE TITLE
Timings like firstPaint should be relative to first request

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#731]
Now if we have redirects, the first paint time is not including the first redirect time:
<img width="1156" alt="screen shot 2015-08-22 at 09 53 57" src="https://cloud.githubusercontent.com/assets/540757/9424931/edd29fd0-48b3-11e5-9527-aa8d80af59e7.png">

**Comment by StephaneColson** [comment]
I have a First paint result which is 1473340138700 ms, i.e. 467 years. It seems to be completely wrong ;)

**Comment by tobli** [comment]
Hi @StephaneColson 
We need some additional information to be able to give an answer. What version of sitespeed.io are you running? What browser etc.
Also where are you seeing the firstPaint number? In a har file, in the browsertime json output or elsewhere?

1473340138700 ms is 46.7 years since 1970 (unix epoch), so it's probably the correct time. However when testing both the latest stable release (3.11.7) and the latest 4.0 beta I only see relative numbers for first paint.

**Comment by StephaneColson** [comment]
Hi @tobli,

I'm using version 4.0.0-beta.1, with ChromeDriver. I see this result in sitespeed-result page:
![selection_742](https://cloud.githubusercontent.com/assets/1481595/18380759/353e2fd0-7679-11e6-96a9-9f21346063d6.png)

**Comment by soulgalore** [comment]
Yep it seems wrong :)

 Can you share how you run and Chrome version so we can try to reproduce?

**Comment by StephaneColson** [comment]
I run this way

`$ bin/sitespeed.js -n 1 --preScript login.js http://mysite`

Chrome version is Version 53.0.2785.92 (64-bit) on Linux Debian

**Comment by StephaneColson** [comment]
Same without  `-n 1`  (then default 3 iterations)

**Comment by StephaneColson** [comment]
@soulgalore @tobli I can create a new ticket with these informations if you think it can help.

**Comment by soulgalore** [comment]
no worries, I'll try tonight on another site, if I cannot reproduce I'll need the URL and login script.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
