### ISSUE TITLE
Add documentation for using config JSON

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#757]
can you please provide a sample of configfile.json... since my intent is only to run wptScript.. and im getting an error as below...

To give you the background i have 4 docker images
sitespeedio/sitespeed.io 
sitespeedio/graphite --> localhost:8080
grafana/grafana --> localhost:3000
nowol/webpagetest  --> running @ 172.17.0.1

How would I run sitespeed io with wpt in this case...?

docker run --privileged --rm -v /sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://www.myurl.com  --wptHost 172.17.0.1 -d 0

**Comment by soulgalore** [comment]
we should add some docs for this.

**Comment by soulgalore** [comment]
I've added some docs some time ago: https://www.sitespeed.io/documentation/sitespeed.io/configuration/#configuration-as-json

**Comment by antinescience** [comment]
@soulgalore what's the best way to run this within Docker using a config file? Clearly something like `docker-compose run sitespeed.io --config=config.json https://www.site.com --graphite.host=graphite` won't work because config.json won't be in the sitespeed container. Is it worth adding a volume line in to map `config.json/config.json`?

**Comment by soulgalore** [comment]
@antinescience yes you should mount a volume. you need that too if you wanna read a file with URLs etc.

I'll add how we run on dashboard.sitespeed.io when we do the next release to the docs so we have a full example.

**Comment by antinescience** [comment]
Awesome. Thanks dude!
