### ISSUE TITLE
Usage of performance.mark

### ISSUE THREAD

**Issue by geekdave** [sitespeedio/sitespeed.io#775]
Hi,

We noticed on your sitespeed.io main page, that you're measuring the logo load time using:

```
<p>
    <img alt="Sitespeed.io logo" class="pull-left img-big" height="200"
      onload= "window.performance.clearMarks('logoTime'); window.performance.mark('logoTime');"
      src="img/sitespeed.io-logo-large2.png" width="188"> 
    <script>
                window.performance.clearMarks('logoTime'); window.performance.mark('logoTime'); 
    </script>
</p>
```

This seems a bit different than what Steve Souders recommends in [his example](http://www.stevesouders.com/blog/2015/05/12/hero-image-custom-metrics/):

```
<img src="hero.jpg" onload="performance.mark('hero1')">
<script>performance.mark('hero2')</script>
```

For this example he says:

> You need to take the max value of the hero1 and hero2 marks

It seems that in the sitespeed example, rather than taking the max value, we're just overwriting the same mark with whichever one happens later.  

I was wondering if you're using perhaps a _newer_ best practice, or if this was intentional?  

Thanks!

**Comment by soulgalore** [comment]
Hi @geekdave ,
I don't think his example is uptodate, you should clear it first (or does it happen automatically, I don't have the spec in my head). The thing is that you should take the mark that happens the last, in Steves example you should take the value with the highest value, in mine example take just the value. If the onload of the image happens first, the CSS takes time to load and the image is not not displayed because we wait of the css. If the script happens first, we dont want that value because the image will be displayed on the onload.

Hmm. did I make myself clear? I think the sitespeed.io version is the new and improved version but please let me know if I'm wrong :)
Best
Peter

**Comment by geekdave** [comment]
@soulgalore That makes perfect sense!  Thanks so much for explaining!
