### ISSUE TITLE
--phantomjsPath gives "phantomjs.exe is not an executable file!" given correct path to phantomjs under Windows

### ISSUE THREAD

**Issue by twirls** [sitespeedio/sitespeed.io#781]
Hi,

I'm trying to use phantomjs 2.0 with sitespeed.io under Windows.
It looks like npm fs mode for executable is not supported under Windows, so checkPermissionSynch(stats.mode, 1) in cli.js thinks that exe file doesn't have execute permissions.

Kind Regards,
Evgeny

**Comment by soulgalore** [comment]
Ah sorry. You could run it through Docker though? The problem is that we don't have a Windows setup for automatic testing + since both me & @tobli haven't used windows for the last 10 years it will cost to much time to also test there, so maybe in 4.0 we make it more clear that we don't support Windows. Sorry!

Best
Peter

**Comment by twirls** [comment]
Thanks for your reply.
I'll investigate the possibility to use Docker.

/Evgeny
