### ISSUE TITLE
PageWeight numbers are weird when running sitespeed.io using seleniumServer

### ISSUE THREAD

**Issue by protos** [sitespeedio/sitespeed.io#797]
Hi,

I'm running sitespeed.io through a shell script as a jenkins job, so that after every build, it runs against some urls, checks the pageWeight against the budget and fails if the pageWeight is too large.
This worked fine when using it with xvfb and firefox, but now I want to switch to using a remote seleniumServer, but the pageWeight numbers I'm getting back are way bigger than they should be (as observed in chrome developer tools) 

Is there a bug in the selenium stuff ? I would prefer to use phantomJS but saw the mention of a bug there where page sizes are also reports incorrectly.

OS: 'linux 3.2.0-72-generic', Node.js: 'v0.10.29', sitespeed.io: '3.8.1', PhantomJS: '1.9.8', java: '1.8.0_51', browsertime: '0.10.2'

Thanks in advance for any help you can give me.
Cheers,
Colm

**Comment by soulgalore** [comment]
Hi @protos !
Thanks for reporting. Hmm, could be it isn't documented anywhere. It works like this: To get correct size you need to use Chrome or Firefox locally, because then we use a proxy to get the correct size (we use the browser mob proxy). In coming versions (but it is a couple of months away) there will be a way of get the correct version from remote Firefox/Chrome.

Best
Peter

**Comment by protos** [comment]
Hi Peter,
OK - no worries. We'll stick to using xvfb for the moment then and will keep an eye out for your updates on using browsers remotely. 
Thanks for getting back to me.

Cheers,
Colm

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
