### ISSUE TITLE
Error occurs at random: Catched an uncaught expection:Error: Callback was already called...

### ISSUE THREAD

**Issue by choongmanee** [sitespeedio/sitespeed.io#821]
I had a successfully running cron job for a few days but this error appeared out of nowhere and now my cron job doesn't complete. There has't been any changes to my configuration to trigger this error.

Fetching http://www.amazon.com/ (1 of 3)
Fetching http://www.amazon.com/ (2 of 3)
Stopping proxy
Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called.
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:43:36
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:723:17
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:167:37
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:94:7
    at webdriver.EventEmitter.emit (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/events.js:55:17)
    at promise.ControlFlow.abortNow_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2023:10)
    at webdriver.EventEmitter.emit (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/events.js:55:17)
    at goog.defineClass.abort (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2192:12)
    at promise.ControlFlow.abortFrame_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1811:9)
    at promise.Promise.notifyAll_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:547:16)

**Comment by soulgalore** [comment]
Hey @chungmankim 
thanks for the report. I cannot see the actual error but the symptom is known, we have a problem today of catching errors browsertime and retry when it happens, we have a new version coming out later this year.

Best
Peter

**Comment by DPiskai** [comment]
Is anyone aware of a potential workaround for this? Thanks

**Comment by soulgalore** [comment]
Hey @DPiskai on what OS do you run it? For Linux it seems like using the Selenium jar is more stable than nodejs version. If you use the Docker version make sure to pass <code>--seleniumServer http://127.0.0.1:4444/wd/hub</code> when you start, then you will use the selenium jar (it will be started automatically).

Best
Peter

**Comment by chungmankim** [comment]
thanks @soulgalore !
I'm running a docker container on RHEL 7 if that would be useful. I don't think the OS should matter since it's on docker but I may stand corrected. I have tried `--seleniumServer http://127.0.0.1:4444/wd/hub` and I'm getting a mixed bag of success and failure but the adjustment seems positive overall.

**Comment by eripa** [comment]
I'm seeing the same issue on our environment. Also Docker (tag 3.11.5), but on Ubuntu 14.04 LTS with the more recent kernel, 3.19.0-56-generic #62~14.04.1-Ubuntu SMP.

It seems like Docker is now defaulting  to use --seleniumServer http://127.0.0.1:4444/wd/hub (correct?) so there is no win there. The jobs have intermittent failures like the above.

This is the command I run (domain redacted):

    docker run --rm --net=sitespeed_default -v /var/lib/jenkins/jobs/sitespeed-graphite-sodw-prod/workspace:/sitespeed.io sitespeedio/sitespeed.io:3.11.5 sitespeed.io -u https://example.com -b firefox -d 1 --connection cable --graphiteHost sitespeed_graphite_1 --no-html --seleniumServer http://127.0.0.1:4444/wd/hub

**Comment by soulgalore** [comment]
Hey @eripa ,
> It seems like Docker is now defaulting to use --seleniumServer http://127.0.0.1:4444/wd/hub (correct?) 

No, it starts the server automatically but you still need to add the parameter to use like you did in the example with <code>--seleniumServer</code> (so you can choose between the running Javas Selenium or NodeJS).

We will not fix anything in the current 3.x version but 4 is rolling out soon (alpha) with a much cleaner implementation for handling Selenium. Though, some problems can still be there, seems that Chrome/Chromedriver have problems on some OS (but still in the new version take care of the errors).

Best
Peter

**Comment by eripa** [comment]
thanks for the quick reply @soulgalore!

I did run the last round with `--seleniumServer http://127.0.0.1:4444/wd/hub`, unfortunately it ended up with the same results. 

Could it be some kind of timeout issue? It seems like this, because it's only failing sometimes. And a much smaller site is working 100% of the time.

Ideas?

**Comment by soulgalore** [comment]
The timeouts are configurable (or at least should), but if it's a timeout you should see it in the logs (there should be an error before the uncaught exception), can you check if see something before the uncaught? 

One thing that I've seen that sometimes Selenium and Chromedriver gets out of sync, so that Selenium tries to contact chrome on the wrong port. Another thing that I've seen is that Chrome crashes and fails. But usually you could see that (the reason) in the log.

**Comment by eripa** [comment]
How would I go about and configure the timeout? Checking the log files shows the same output as above and I guess it's browsertime that is failing given they are listed  in the browsertime.log.

This is what's shown before the uncaught exception (it stops on different URLs/levels on each crash):

    [32minfo[39m: Running browsertime for firefox https://example.com/videos/yxIhVfI-3AU/article1/
    Fetching https://exampley.com/videos/yxIhVfI-3AU/article1/ (1 of 3)


I'm currently using Firefox due to the fact that I experience some weirdness with the Chrome driver.

**Comment by soulgalore** [comment]
Hey @eripa sorry for the late answer. Changing the timeouts is a little hacky. You can use --btConfig to send parameters directly to Browsertime (that handles the browser).But now when I did a quick check I couldn't see any options (the default timeout is 2 minutes though). I'll check tomorrow,

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
