### ISSUE TITLE
How to use sitespeed.io on angular web apps

### ISSUE THREAD

**Issue by VikramBPurohit** [sitespeedio/sitespeed.io#831]
Hi There,

How to use site speed to dynamically analyze web application.

1. When site can't be crawled without passing a login screen?
2. Web layout changes based on operation being performed on the site. (Angular application)
3. Any integration possibility when running test automation using selenium or protractor.

--Vikram

**Comment by soulgalore** [comment]
Hey @VikramBPurohit,
in the current version there is no good way to catch layout changes. I think [Boomerang](https://github.com/lognormal/boomerang) has some things to catch that but I don't know if it is in the Open Source version yet, you can check with @bluesmoon 

1. Right now you need to login the user from whatever tool you can use, and then take the cookie and pass that as a request header. In the 4.0 comining this summer you can login the user using a selenium script.

2. What you can do is change the timeout time (when to stop testing) and then if your application use the User Timing API and push metrics sitespeed.io will catch them. 

3. You can use a Selenium grid but using that you need to turn of the local proxy that creates the HAR file.

So isn't perfect for handling Angular, sorry!

Best
Peter

**Comment by FJLopezGarcia** [comment]
Hi @VikramBPurohit @all, Did you try? What was your experience? 
I would like to add a gulp task for performance monitoring in an Angular website, do you know any?

**Comment by bluesmoon** [comment]
@nicjansma or @andreas-marschke can help on the angular usage with boomerang.

**Comment by andreas-marschke** [comment]
Hi @VikramBPurohit !

Head over to https://github.com/bluesmoon/boomerang and clone the repository you'll find the [Angular plugin](https://github.com/bluesmoon/boomerang/blob/master/plugins/angular.js) and [documentation on how to use it](https://github.com/bluesmoon/boomerang/blob/master/doc/api/SPA.html) over there.

We're happy to help! 

Also feel free to raise an issue if you encounter anything that seems unintuitive or problematic for you.

**Comment by sgilroy** [comment]
Does Boomerang (with the Angular plugin) address issues of routing/urls when AngularJS is used in hasbang mode and has urls with a `#` in them?

I ran sitespeed.io my AngularJS app using `sitespeed.io -f urls.txt --screenshot` where `urls.txt` contained two URLs like this:

```
http://0.0.0.0:9000/#/coach/enrolled?login=coach-clarisa@example.com
http://0.0.0.0:9000/#/coach/patient/57a91824f536854bb344b39d/overview
```

The result only contained one file in pages (`0_0_0_0.html`), one screenshot, and one yslow.json file instead of the expected two for each. Is there a way to get sitespeed.io to include the anchor tag (the part of the url after the hash symbol) so that a single page application like ours that uses Angular (or any framework using similar navigation) can capture results for multiple pages/routes? Or do I need to switch to using [html5mode](https://scotch.io/tutorials/pretty-urls-in-angularjs-removing-the-hashtag)?

**Comment by bluesmoon** [comment]
better to ask on https://github.com/soasta/boomerang/issues so the boomerang team can respond in detail.

boomerang does hook into Angular's router, so should capture any URL, but it will also strip out anything after the `#` before sending the URL to the server. This is probably what you're seeing.

As far as why boomerang does this, it's because of a few notes from the URL spec:
> No fragmentid part of a WWW URI (the hash sign and following) is  sent with the request

and the HTTP spec:
> 14.36 ... The URI MUST NOT include a fragment.

And while this refers to the Referrer, we take it to mean in spirit, that the fragment is not intended to be sent to a server.
