### ISSUE TITLE
Error running browsertime

### ISSUE THREAD

**Issue by VikramBPurohit** [sitespeedio/sitespeed.io#854]
Hi @soulgalore 

I am getting below error when running sitespeed.io -

 sitespeed.io -u https://dev2.com --graphiteHost localhost -m 5 --graphiteNamespace  
test.20160402 -b chrome -n 11
info: OS: 'linux 2.6.32-431.5.1.el6.x86_64', Node.js: 'v4.2.0', sitespeed.io: '3                                      .11.5', PhantomJS: '2.1.1', java: '1.8.0_11', browsertime: '0.12.2'
info: Will crawl from start point https://dev2.com with crawl depth                                       1
info: Will analyze 1 page
info: Running YSlow for https://dev2.com [phantomjs]
Starting proxy on port 2001, will wait at most 15000 ms
info: Queueing browsertime for https://dev2.com chrome
info: Running browsertime for chrome https://dev2.com
Fetching https://dev2.com (1 of 11)
[Error: Server terminated early with status 1]
error: Error running browsertime: [Error: Server terminated early with status 1]
Stopping proxy
error: Could not generate HAR for https://dev2.com { [Error: ENOENT                                      : no such file or directory, open '/home/sitespeed-result/dev2.com/2016-04-01-20-32-23/data/har/chrome/s-dev2_com.har']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/sitespeed-result/dev2.com/2016-04-01-20-32-2                                      3/data/har/chrome/s-dev2_com.har' }

**Comment by tobli** [comment]
Hi @VikramBPurohit!
Hard to really tell since it's not a public server. However I think the error message (Server terminated early with status 1) is coming from Selenium. Please make sure you're using a recent version of Chrome and a version of ChromeDriver that matches it. You can see in the [ChromeDriver release notes](http://chromedriver.storage.googleapis.com/2.21/notes.txt) what version of Chrome they work with.

BR
/Tobias

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
