### ISSUE TITLE
Selenium timeout running sitespeed.io with firefox on Jenkins 

### ISSUE THREAD

**Issue by tdmoneybanks** [sitespeedio/sitespeed.io#858]
Hi, I am trying to run the sitespeed tool as part of our build process through Jenkins. I have been able to run the tool with the headless browser Phantom successfully but am unable to run the tool with the -b firefox browser flag. The error I am getting is: 
[Error: Timed out waiting for the WebDriver server at http://127.0.0.1:34620/hub]
once it tries to fetch a url with firefox. Could you give me any information on what could be causing this error or potential fixes?
Thanks

**Comment by abhagupta** [comment]
How about chrome?  Is your Jenkins box a Unix machine?  Are you running the sitespeed.io in docker container?  I  have similar issue  but I am running the test on Firefox in an XVFB inside a docker container by sitespeed.io.  and for some reason, incompatibility between the host unix version and docker container's unix version is not letting firefox to open in XVFB.

**Comment by tdmoneybanks** [comment]
Hi, I am running it on a linux machine and it is not in a container. We are trying to install and use XVFB but have not done it yet. Did installing XVFB fix the issues on your end?

**Comment by abhagupta** [comment]
My use case is quite different from yours.  Our Jenkins box is a Unix machine with no GUI. Hence, there was no question of running Chrome or FF without XVFB.  For me, sitespeed.io docker container worked great. Although, I had some hiccups running chrome in the docker container (which has XVFB packaged), it got fixed by passing a browsertime config, but I am still not able to run FF inside the docker container).  FYI, the issue https://github.com/sitespeedio/sitespeed.io-docker/issues/5  which fixed chrome in my case.   

To troubleshoot your scenario, try running a simple selenium script in your Linux environment (if it has GUI). In my experience, I have always started with Chrome. If that does not work, it is the selenium issue and not sitespeed.io.

**Comment by soulgalore** [comment]
Hi @tdmoneybanks yep you need xvfb. There's a Jenkins plugin you can use that start xvfb.

Best
Peter

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
