### ISSUE TITLE
Graphs/charts on the result page

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#870]
With the new design we could start using graphs. For example to display page composition of content types (number of request/sizes).

Lets look at https://gionkunz.github.io/chartist-js/ and http://www.chartjs.org/. Or is there another chart library we should use (want to stay away from JQuery).

**Comment by beenanner** [comment]
@soulgalore I threw together a prototype of using chartjs on the detailed page report for # of requests let me know what you think

![screenshot from 2016-06-27 00 53 38](https://cloud.githubusercontent.com/assets/723985/16368907/e7521b08-3c01-11e6-9a99-8d6362d0a501.png)

**Comment by soulgalore** [comment]
@beenanner looks great!!!

**Comment by soulgalore** [comment]
@beenanner looks great!!!

**Comment by soulgalore** [comment]
@beenanner what else do you think we should have? one thing is that when we run in Docker with visualMetrics we have the visual progress so we can make a line chart how the page is painted.

**Comment by beenanner** [comment]
I like the idea of a visual progress line chart for visualMetrics. I'll look more into running a test that outputs everything and review the areas available. I think charts will be very nice, but we probably want to be selective as to not overwhelm/clutter the results pages with charts everywhere just because we can generate them. :-) Here are a few I can think we can leverage of off the top of my head.

### Straight forward charts
1. "Requests per response code"(1 chart) and "Requests and sizes per content type" (4 charts) could be [doughnut/pie charts](http://www.chartjs.org/docs/#doughnut-pie-chart) or [polar area charts](http://www.chartjs.org/docs/#polar-area-chart)
2. [Line chart](http://www.chartjs.org/docs/#line-chart) for the visualMetrics when requested (1 chart)
3. Third party vs First Party can be a [doughnut/pie chart](http://www.chartjs.org/docs/#doughnut-pie-chart) when requested (1 chart)


### Advance charting thoughts
1. I think the http://www.chartjs.org/docs/#radar-chart could provide some interesting visuals for a single domain and it's timings. (New feature: n charts maybe click through to domain summary standalone pages?)
2. Maybe a [bubble chart](https://github.com/chartjs/Chart.js/blob/master/docs/08-Bubble-Chart.md) for showing domains and # of requests on the domain result page with tool tip for click or tap on bubbles (1 chart)


As for the generating the JS to create the charts I'm thinking we should split that logic out into it's own helper file or/and template file(s). What do you think?

**Comment by soulgalore** [comment]
Yes I agree lets focus on what we think will add value :) If you have time chose the one you think would add most value and add it.

> As for the generating the JS to create the charts I'm thinking we should split that logic out into it's own helper file or/and template file(s). What do you think?

Yes sounds great.

**Comment by soulgalore** [comment]
This is perfect for someone outside the members of the project to test out to try get into the project :)

**Comment by sarvaratchagan** [comment]
Hi @soulgalore, I would like to help with you in this project

**Comment by soulgalore** [comment]
Hi @sarvaratchagan wow yes that would be great! Me, @beenanner or @tobli can help guide/help you to get started. I think the first data that could be converted to a graph is the visual metrics (But to get that you need to run the Docker container with video):

![vp](https://cloud.githubusercontent.com/assets/540757/25005871/ea576234-205a-11e7-9390-beff39f78b02.png)

Else let us know what you wanna do and we'll help out.
Best
Peter

**Comment by sarvaratchagan** [comment]
@soulgalore I need some help to setup in my local machine. can you guide me ?

**Comment by soulgalore** [comment]
Hey @sarvaratchagan I need to add that to the docs! But until I do that:

On your local you need: 
* [Install NodeJS](https://nodejs.org/en/download/) latest LTS version
* Fork sitespeed.io and clone
* run *npm install*

Then you are ready. To run locally: *bin/sitespeed.io https://www.sitespeed.io -n 1* do changes to the pug and re-run.

To run the Docker version:
* Install [Docker Community Edition](https://docs.docker.com/engine/installation/)
* You need to fork and clone sitespeed.
* Go to development/ in the cloned dir and read the index.md
* Build the sitespeed.io container: *docker-compose build sitespeed*
* Run: *docker-compose run sitespeed http://www.sitespeed.io*
* Make your changes and rebuild the container *docker-compose build sitespeed* and test again

You can also dump the data structure and then just change the pug files, but I need to make some updates to make that easier. If I'll fix that then you don't need to rerun sitespeed.io to check your changes. Let me fix that the following days and write some docs. 

Best
Peter

**Comment by sarvaratchagan** [comment]
Hello @soulgalore, I followed everything what you suggested above. but its not working here . Could you help me to start ?

**Comment by soulgalore** [comment]
yes show me the error you get and I will try to help!

**Comment by soulgalore** [comment]
Added a branch where I tried out chartist, but could be chartjs would work better for us (there are still some fine tuning needed). I've added a size and a request graph on the PageXray tab:
<img width="958" alt="screen shot 2017-06-27 at 10 10 33 pm" src="https://user-images.githubusercontent.com/540757/27607919-cfc12c0a-5b85-11e7-8123-f4b0b1dcf517.png">

But we miss a way to see the exact value right now.

Then for visual progress:
<img width="932" alt="screen shot 2017-06-27 at 10 10 21 pm" src="https://user-images.githubusercontent.com/540757/27607937-e1c39c3a-5b85-11e7-8092-4c9cede88b9a.png">
Missing config there for the x-axel.

@beenanner we should be able to use what I did and just change to chartjs: there are pug-files to each chart that we should, change, include the right css/js and then change the hack in the tabs.pug files that re-draw the charts.

**Comment by beenanner** [comment]
@soulgalore what's left for this one for 6.0? I should have time to focus on it over the next few weeks. Looks like we have a few things in master already. Just wasn't sure if we had some polishing to do or if this is good enough to close.

**Comment by soulgalore** [comment]
released.
