### ISSUE TITLE
Help method for displaying URLs

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#874]
Today we display the full URL for an asset, check this out:
<img width="978" alt="screen shot 2016-04-14 at 00 59 35" src="https://cloud.githubusercontent.com/assets/540757/14512071/4910cf98-01dc-11e6-89df-5330c99c1b25.png">

Ooops that is quite long. We could try to do something magical like displaying the domain and the end of the filename and skip parameters? I think webpagetest has an ok way of doing it in the waterfalls, perfcascade has something like that too.

**Comment by dmillerme7** [comment]
There might be a way to do this in PHP if you're using that, looks like WPT is. Unfortunately I am not a PHP person. Perfcascade is using SVG so that it a different story altogether. Using JS and jQuery we can use replace() and split() to get something similar happening. If there was a class on all those anchor tags it would make it easier. Are you going to use jQuery in v4.0?

**Comment by dmillerme7** [comment]
A very scruffy jsfiddle https://jsfiddle.net/dmillerme7/v4ga3uv3/4/

**Comment by soulgalore** [comment]
Hey @dmillerme7 thanks for the jsfiddle :) We will avoid JQuery but we can hack around that. We can do it in the layer when parsing the output and we can add some tests for it.  Do you have to give it a go or I can set something up.

**Comment by dmillerme7** [comment]
Hi @soulgalore I'll clone the project and have a go at it. If I get something working I'll make a pull request.

**Comment by beenanner** [comment]
@soulgalore / @dmillerme7 I threw together a quick hack for this issue that we should clean up as well as it definitely can be improve upon. Check it out and let me know if it gives us what we need for now.
