### ISSUE TITLE
WebpageTest wptScript is not working

### ISSUE THREAD

**Issue by BKarthikeyan** [sitespeedio/sitespeed.io#954]
I try to test wptscript for URL navigation but getting error. Help me to fix the issue.

**wptscript.txt:**
logData 1
navigate https://www.sitespeed.io/documentation/

D:\>sitespeed.io.cmd --wptScript wptscript.txt --wptHost www.webpagetest.org --w
ptKey A.  -u https://sitespeed.io

URL navigation is not working. I also tried with below given option.
logData 1
navigate {{{https://www.sitespeed.io/documentation/}}}

Error Log:
error: WebPageTest couldn't fetch info for url
navigate {https://www.sitespeed.io/documentation/}{ statusCode: 400,
  statusText: 'Please enter a Valid URL.  <b>{https</b> is not a valid Internet
host name' }

**Comment by soulgalore** [comment]
Hey @BKarthikeyan 
when you want to use a script, it usually because you want to login or access a specific page before the page you want to measure. In your template every occurrence of <pre>{{{URL}}} </pre> will be changed to the URL WebPageTest want to test (feed from sitespeed). So a script file would look something like this
<pre>
logData 0
navigate https://www.example.com/start
logData 1
navigate {{{URL}}} 
</pre>

**Comment by BKarthikeyan** [comment]
Thanks Peter.Now its working for me.
