### ISSUE TITLE
How to add load runner script with sitespeed

### ISSUE THREAD

**Issue by BKarthikeyan** [sitespeedio/sitespeed.io#960]
I need to pass values as parameters to navigate one page to another page. Is it possible to add load runner script in sitespeed. I used Webpagetest script and authenticated userid and password successfully but passing more parameters doesn't working using wptscript. 

Can you also tell me how to pass cookies value in sitespeed and test the URL. If you provide some sample example,that will be great.

**Comment by soulgalore** [comment]
Hey @BKarthikeyan we will support selenium scripts in 4.0. That will look something like this: 
https://github.com/tobli/browsertime/blob/1.0/test/preposttasks/preLoginExample.js

I know a lot of people waits on 4.0 lets see if we can make the tight schedule :)

Best
Peter

**Comment by softwareklinic** [comment]
I was able to test 1 page flow taking the userid... using the selenium script in 4.0 alpha... will try out more today with a continuous flow of4-5 pages after the signin... to see how it reflects the metrics...

Also, do we know how this data will be recorded in graphite... i will try and shed light otherwise...

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
